// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsSagittalAthenian extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accSagittal7v11KleismaUp,
        SmuflGlyph.accSagittal7v11KleismaDown,
        SmuflGlyph.accSagittal17CommaUp,
        SmuflGlyph.accSagittal17CommaDown,
        SmuflGlyph.accSagittal55CommaUp,
        SmuflGlyph.accSagittal55CommaDown,
        SmuflGlyph.accSagittal7v11CommaUp,
        SmuflGlyph.accSagittal7v11CommaDown,
        SmuflGlyph.accSagittal5v11SmallDiesisUp,
        SmuflGlyph.accSagittal5v11SmallDiesisDown,
        SmuflGlyph.accSagittalSharp5v11SDown,
        SmuflGlyph.accSagittalFlat5v11SUp,
        SmuflGlyph.accSagittalSharp7v11CDown,
        SmuflGlyph.accSagittalFlat7v11CUp,
        SmuflGlyph.accSagittalSharp55CDown,
        SmuflGlyph.accSagittalFlat55CUp,
        SmuflGlyph.accSagittalSharp17CDown,
        SmuflGlyph.accSagittalFlat17CUp,
        SmuflGlyph.accSagittalSharp7v11kDown,
        SmuflGlyph.accSagittalFlat7v11kUp,
        SmuflGlyph.accSagittalSharp7v11kUp,
        SmuflGlyph.accSagittalFlat7v11kDown,
        SmuflGlyph.accSagittalSharp17CUp,
        SmuflGlyph.accSagittalFlat17CDown,
        SmuflGlyph.accSagittalSharp55CUp,
        SmuflGlyph.accSagittalFlat55CDown,
        SmuflGlyph.accSagittalSharp7v11CUp,
        SmuflGlyph.accSagittalFlat7v11CDown,
        SmuflGlyph.accSagittalSharp5v11SUp,
        SmuflGlyph.accSagittalFlat5v11SDown,
        SmuflGlyph.accSagittalDoubleSharp5v11SDown,
        SmuflGlyph.accSagittalDoubleFlat5v11SUp,
        SmuflGlyph.accSagittalDoubleSharp7v11CDown,
        SmuflGlyph.accSagittalDoubleFlat7v11CUp,
        SmuflGlyph.accSagittalDoubleSharp55CDown,
        SmuflGlyph.accSagittalDoubleFlat55CUp,
        SmuflGlyph.accSagittalDoubleSharp17CDown,
        SmuflGlyph.accSagittalDoubleFlat17CUp,
        SmuflGlyph.accSagittalDoubleSharp7v11kDown,
        SmuflGlyph.accSagittalDoubleFlat7v11kUp,
      ];

  static const accSagittal7v11KleismaUp = SmuflGlyph.accSagittal7v11KleismaUp;

  static const accSagittal7v11KleismaDown =
      SmuflGlyph.accSagittal7v11KleismaDown;

  static const accSagittal17CommaUp = SmuflGlyph.accSagittal17CommaUp;

  static const accSagittal17CommaDown = SmuflGlyph.accSagittal17CommaDown;

  static const accSagittal55CommaUp = SmuflGlyph.accSagittal55CommaUp;

  static const accSagittal55CommaDown = SmuflGlyph.accSagittal55CommaDown;

  static const accSagittal7v11CommaUp = SmuflGlyph.accSagittal7v11CommaUp;

  static const accSagittal7v11CommaDown = SmuflGlyph.accSagittal7v11CommaDown;

  static const accSagittal5v11SmallDiesisUp =
      SmuflGlyph.accSagittal5v11SmallDiesisUp;

  static const accSagittal5v11SmallDiesisDown =
      SmuflGlyph.accSagittal5v11SmallDiesisDown;

  static const accSagittalSharp5v11SDown = SmuflGlyph.accSagittalSharp5v11SDown;

  static const accSagittalFlat5v11SUp = SmuflGlyph.accSagittalFlat5v11SUp;

  static const accSagittalSharp7v11CDown = SmuflGlyph.accSagittalSharp7v11CDown;

  static const accSagittalFlat7v11CUp = SmuflGlyph.accSagittalFlat7v11CUp;

  static const accSagittalSharp55CDown = SmuflGlyph.accSagittalSharp55CDown;

  static const accSagittalFlat55CUp = SmuflGlyph.accSagittalFlat55CUp;

  static const accSagittalSharp17CDown = SmuflGlyph.accSagittalSharp17CDown;

  static const accSagittalFlat17CUp = SmuflGlyph.accSagittalFlat17CUp;

  static const accSagittalSharp7v11kDown = SmuflGlyph.accSagittalSharp7v11kDown;

  static const accSagittalFlat7v11kUp = SmuflGlyph.accSagittalFlat7v11kUp;

  static const accSagittalSharp7v11kUp = SmuflGlyph.accSagittalSharp7v11kUp;

  static const accSagittalFlat7v11kDown = SmuflGlyph.accSagittalFlat7v11kDown;

  static const accSagittalSharp17CUp = SmuflGlyph.accSagittalSharp17CUp;

  static const accSagittalFlat17CDown = SmuflGlyph.accSagittalFlat17CDown;

  static const accSagittalSharp55CUp = SmuflGlyph.accSagittalSharp55CUp;

  static const accSagittalFlat55CDown = SmuflGlyph.accSagittalFlat55CDown;

  static const accSagittalSharp7v11CUp = SmuflGlyph.accSagittalSharp7v11CUp;

  static const accSagittalFlat7v11CDown = SmuflGlyph.accSagittalFlat7v11CDown;

  static const accSagittalSharp5v11SUp = SmuflGlyph.accSagittalSharp5v11SUp;

  static const accSagittalFlat5v11SDown = SmuflGlyph.accSagittalFlat5v11SDown;

  static const accSagittalDoubleSharp5v11SDown =
      SmuflGlyph.accSagittalDoubleSharp5v11SDown;

  static const accSagittalDoubleFlat5v11SUp =
      SmuflGlyph.accSagittalDoubleFlat5v11SUp;

  static const accSagittalDoubleSharp7v11CDown =
      SmuflGlyph.accSagittalDoubleSharp7v11CDown;

  static const accSagittalDoubleFlat7v11CUp =
      SmuflGlyph.accSagittalDoubleFlat7v11CUp;

  static const accSagittalDoubleSharp55CDown =
      SmuflGlyph.accSagittalDoubleSharp55CDown;

  static const accSagittalDoubleFlat55CUp =
      SmuflGlyph.accSagittalDoubleFlat55CUp;

  static const accSagittalDoubleSharp17CDown =
      SmuflGlyph.accSagittalDoubleSharp17CDown;

  static const accSagittalDoubleFlat17CUp =
      SmuflGlyph.accSagittalDoubleFlat17CUp;

  static const accSagittalDoubleSharp7v11kDown =
      SmuflGlyph.accSagittalDoubleSharp7v11kDown;

  static const accSagittalDoubleFlat7v11kUp =
      SmuflGlyph.accSagittalDoubleFlat7v11kUp;
}
