// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsJohnston extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalJohnstonPlus,
        SmuflGlyph.accidentalJohnstonMinus,
        SmuflGlyph.accidentalJohnstonEl,
        SmuflGlyph.accidentalJohnstonSeven,
        SmuflGlyph.accidentalJohnstonUp,
        SmuflGlyph.accidentalJohnstonDown,
        SmuflGlyph.accidentalJohnston13,
        SmuflGlyph.accidentalJohnston31,
      ];

  static const accidentalJohnstonPlus = SmuflGlyph.accidentalJohnstonPlus;

  static const accidentalJohnstonMinus = SmuflGlyph.accidentalJohnstonMinus;

  static const accidentalJohnstonEl = SmuflGlyph.accidentalJohnstonEl;

  static const accidentalJohnstonSeven = SmuflGlyph.accidentalJohnstonSeven;

  static const accidentalJohnstonUp = SmuflGlyph.accidentalJohnstonUp;

  static const accidentalJohnstonDown = SmuflGlyph.accidentalJohnstonDown;

  static const accidentalJohnston13 = SmuflGlyph.accidentalJohnston13;

  static const accidentalJohnston31 = SmuflGlyph.accidentalJohnston31;
}
