// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsSteinZimmermann extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalQuarterToneFlatStein,
        SmuflGlyph.accidentalThreeQuarterTonesFlatZimmermann,
        SmuflGlyph.accidentalQuarterToneSharpStein,
        SmuflGlyph.accidentalThreeQuarterTonesSharpStein,
        SmuflGlyph.accidentalNarrowReversedFlat,
        SmuflGlyph.accidentalNarrowReversedFlatAndFlat,
        SmuflGlyph.accidentalReversedFlatArrowUp,
        SmuflGlyph.accidentalReversedFlatArrowDown,
        SmuflGlyph.accidentalFilledReversedFlatArrowUp,
        SmuflGlyph.accidentalFilledReversedFlatArrowDown,
        SmuflGlyph.accidentalReversedFlatAndFlatArrowUp,
        SmuflGlyph.accidentalReversedFlatAndFlatArrowDown,
        SmuflGlyph.accidentalFilledReversedFlatAndFlat,
        SmuflGlyph.accidentalFilledReversedFlatAndFlatArrowUp,
        SmuflGlyph.accidentalFilledReversedFlatAndFlatArrowDown,
        SmuflGlyph.accidentalHalfSharpArrowUp,
        SmuflGlyph.accidentalHalfSharpArrowDown,
        SmuflGlyph.accidentalOneAndAHalfSharpsArrowUp,
        SmuflGlyph.accidentalOneAndAHalfSharpsArrowDown,
      ];

  static const accidentalQuarterToneFlatStein =
      SmuflGlyph.accidentalQuarterToneFlatStein;

  static const accidentalThreeQuarterTonesFlatZimmermann =
      SmuflGlyph.accidentalThreeQuarterTonesFlatZimmermann;

  static const accidentalQuarterToneSharpStein =
      SmuflGlyph.accidentalQuarterToneSharpStein;

  static const accidentalThreeQuarterTonesSharpStein =
      SmuflGlyph.accidentalThreeQuarterTonesSharpStein;

  static const accidentalNarrowReversedFlat =
      SmuflGlyph.accidentalNarrowReversedFlat;

  static const accidentalNarrowReversedFlatAndFlat =
      SmuflGlyph.accidentalNarrowReversedFlatAndFlat;

  static const accidentalReversedFlatArrowUp =
      SmuflGlyph.accidentalReversedFlatArrowUp;

  static const accidentalReversedFlatArrowDown =
      SmuflGlyph.accidentalReversedFlatArrowDown;

  static const accidentalFilledReversedFlatArrowUp =
      SmuflGlyph.accidentalFilledReversedFlatArrowUp;

  static const accidentalFilledReversedFlatArrowDown =
      SmuflGlyph.accidentalFilledReversedFlatArrowDown;

  static const accidentalReversedFlatAndFlatArrowUp =
      SmuflGlyph.accidentalReversedFlatAndFlatArrowUp;

  static const accidentalReversedFlatAndFlatArrowDown =
      SmuflGlyph.accidentalReversedFlatAndFlatArrowDown;

  static const accidentalFilledReversedFlatAndFlat =
      SmuflGlyph.accidentalFilledReversedFlatAndFlat;

  static const accidentalFilledReversedFlatAndFlatArrowUp =
      SmuflGlyph.accidentalFilledReversedFlatAndFlatArrowUp;

  static const accidentalFilledReversedFlatAndFlatArrowDown =
      SmuflGlyph.accidentalFilledReversedFlatAndFlatArrowDown;

  static const accidentalHalfSharpArrowUp =
      SmuflGlyph.accidentalHalfSharpArrowUp;

  static const accidentalHalfSharpArrowDown =
      SmuflGlyph.accidentalHalfSharpArrowDown;

  static const accidentalOneAndAHalfSharpsArrowUp =
      SmuflGlyph.accidentalOneAndAHalfSharpsArrowUp;

  static const accidentalOneAndAHalfSharpsArrowDown =
      SmuflGlyph.accidentalOneAndAHalfSharpsArrowDown;
}
