// Generated by tool.

part of "../glyph_class.dart";

class Accidentals72EDOWyschnegradsky extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalWyschnegradsky1TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky2TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky3TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky4TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky5TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky6TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky7TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky8TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky9TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky10TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky11TwelfthsSharp,
        SmuflGlyph.accidentalWyschnegradsky1TwelfthsFlat,
        SmuflGlyph.accidentalWyschnegradsky2TwelfthsFlat,
        SmuflGlyph.accidentalWyschnegradsky3TwelfthsFlat,
        SmuflGlyph.accidentalWyschnegradsky4TwelfthsFlat,
        SmuflGlyph.accidentalWyschnegradsky5TwelfthsFlat,
        SmuflGlyph.accidentalWyschnegradsky6TwelfthsFlat,
        SmuflGlyph.accidentalWyschnegradsky7TwelfthsFlat,
        SmuflGlyph.accidentalWyschnegradsky8TwelfthsFlat,
        SmuflGlyph.accidentalWyschnegradsky9TwelfthsFlat,
        SmuflGlyph.accidentalWyschnegradsky10TwelfthsFlat,
        SmuflGlyph.accidentalWyschnegradsky11TwelfthsFlat,
      ];

  static const accidentalWyschnegradsky1TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky1TwelfthsSharp;

  static const accidentalWyschnegradsky2TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky2TwelfthsSharp;

  static const accidentalWyschnegradsky3TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky3TwelfthsSharp;

  static const accidentalWyschnegradsky4TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky4TwelfthsSharp;

  static const accidentalWyschnegradsky5TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky5TwelfthsSharp;

  static const accidentalWyschnegradsky6TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky6TwelfthsSharp;

  static const accidentalWyschnegradsky7TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky7TwelfthsSharp;

  static const accidentalWyschnegradsky8TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky8TwelfthsSharp;

  static const accidentalWyschnegradsky9TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky9TwelfthsSharp;

  static const accidentalWyschnegradsky10TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky10TwelfthsSharp;

  static const accidentalWyschnegradsky11TwelfthsSharp =
      SmuflGlyph.accidentalWyschnegradsky11TwelfthsSharp;

  static const accidentalWyschnegradsky1TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky1TwelfthsFlat;

  static const accidentalWyschnegradsky2TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky2TwelfthsFlat;

  static const accidentalWyschnegradsky3TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky3TwelfthsFlat;

  static const accidentalWyschnegradsky4TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky4TwelfthsFlat;

  static const accidentalWyschnegradsky5TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky5TwelfthsFlat;

  static const accidentalWyschnegradsky6TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky6TwelfthsFlat;

  static const accidentalWyschnegradsky7TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky7TwelfthsFlat;

  static const accidentalWyschnegradsky8TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky8TwelfthsFlat;

  static const accidentalWyschnegradsky9TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky9TwelfthsFlat;

  static const accidentalWyschnegradsky10TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky10TwelfthsFlat;

  static const accidentalWyschnegradsky11TwelfthsFlat =
      SmuflGlyph.accidentalWyschnegradsky11TwelfthsFlat;
}
