// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsPersian extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalKoron,
        SmuflGlyph.accidentalSori,
      ];

  static const accidentalKoron = SmuflGlyph.accidentalKoron;

  static const accidentalSori = SmuflGlyph.accidentalSori;
}
