// Generated by tool.

part of "../glyph_class.dart";

class Accidentals53EDOTurkish extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidental1CommaSharp,
        SmuflGlyph.accidental2CommaSharp,
        SmuflGlyph.accidental3CommaSharp,
        SmuflGlyph.accidental5CommaSharp,
        SmuflGlyph.accidental1CommaFlat,
        SmuflGlyph.accidental2CommaFlat,
        SmuflGlyph.accidental3CommaFlat,
        SmuflGlyph.accidental4CommaFlat,
      ];

  static const accidental1CommaSharp = SmuflGlyph.accidental1CommaSharp;

  static const accidental2CommaSharp = SmuflGlyph.accidental2CommaSharp;

  static const accidental3CommaSharp = SmuflGlyph.accidental3CommaSharp;

  static const accidental5CommaSharp = SmuflGlyph.accidental5CommaSharp;

  static const accidental1CommaFlat = SmuflGlyph.accidental1CommaFlat;

  static const accidental2CommaFlat = SmuflGlyph.accidental2CommaFlat;

  static const accidental3CommaFlat = SmuflGlyph.accidental3CommaFlat;

  static const accidental4CommaFlat = SmuflGlyph.accidental4CommaFlat;
}
