// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsSims extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalSims12Down,
        SmuflGlyph.accidentalSims6Down,
        SmuflGlyph.accidentalSims4Down,
        SmuflGlyph.accidentalSims12Up,
        SmuflGlyph.accidentalSims6Up,
        SmuflGlyph.accidentalSims4Up,
      ];

  static const accidentalSims12Down = SmuflGlyph.accidentalSims12Down;

  static const accidentalSims6Down = SmuflGlyph.accidentalSims6Down;

  static const accidentalSims4Down = SmuflGlyph.accidentalSims4Down;

  static const accidentalSims12Up = SmuflGlyph.accidentalSims12Up;

  static const accidentalSims6Up = SmuflGlyph.accidentalSims6Up;

  static const accidentalSims4Up = SmuflGlyph.accidentalSims4Up;
}
