// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsSagittalPromethean extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accSagittal19SchismaUp,
        SmuflGlyph.accSagittal19SchismaDown,
        SmuflGlyph.accSagittal17KleismaUp,
        SmuflGlyph.accSagittal17KleismaDown,
        SmuflGlyph.accSagittal143CommaUp,
        SmuflGlyph.accSagittal143CommaDown,
        SmuflGlyph.accSagittal11v49CommaUp,
        SmuflGlyph.accSagittal11v49CommaDown,
        SmuflGlyph.accSagittal19CommaUp,
        SmuflGlyph.accSagittal19CommaDown,
        SmuflGlyph.accSagittal7v19CommaUp,
        SmuflGlyph.accSagittal7v19CommaDown,
        SmuflGlyph.accSagittal49SmallDiesisUp,
        SmuflGlyph.accSagittal49SmallDiesisDown,
        SmuflGlyph.accSagittal23SmallDiesisUp,
        SmuflGlyph.accSagittal23SmallDiesisDown,
        SmuflGlyph.accSagittal5v13MediumDiesisUp,
        SmuflGlyph.accSagittal5v13MediumDiesisDown,
        SmuflGlyph.accSagittal11v19MediumDiesisUp,
        SmuflGlyph.accSagittal11v19MediumDiesisDown,
        SmuflGlyph.accSagittal49MediumDiesisUp,
        SmuflGlyph.accSagittal49MediumDiesisDown,
        SmuflGlyph.accSagittal5v49MediumDiesisUp,
        SmuflGlyph.accSagittal5v49MediumDiesisDown,
        SmuflGlyph.accSagittal49LargeDiesisUp,
        SmuflGlyph.accSagittal49LargeDiesisDown,
        SmuflGlyph.accSagittal11v19LargeDiesisUp,
        SmuflGlyph.accSagittal11v19LargeDiesisDown,
        SmuflGlyph.accSagittal5v13LargeDiesisUp,
        SmuflGlyph.accSagittal5v13LargeDiesisDown,
        SmuflGlyph.accSagittalSharp23SDown,
        SmuflGlyph.accSagittalFlat23SUp,
        SmuflGlyph.accSagittalSharp49SDown,
        SmuflGlyph.accSagittalFlat49SUp,
        SmuflGlyph.accSagittalSharp7v19CDown,
        SmuflGlyph.accSagittalFlat7v19CUp,
        SmuflGlyph.accSagittalSharp19CDown,
        SmuflGlyph.accSagittalFlat19CUp,
        SmuflGlyph.accSagittalSharp11v49CDown,
        SmuflGlyph.accSagittalFlat11v49CUp,
        SmuflGlyph.accSagittalSharp143CDown,
        SmuflGlyph.accSagittalFlat143CUp,
        SmuflGlyph.accSagittalSharp17kDown,
        SmuflGlyph.accSagittalFlat17kUp,
        SmuflGlyph.accSagittalSharp19sDown,
        SmuflGlyph.accSagittalFlat19sUp,
        SmuflGlyph.accSagittalSharp19sUp,
        SmuflGlyph.accSagittalFlat19sDown,
        SmuflGlyph.accSagittalSharp17kUp,
        SmuflGlyph.accSagittalFlat17kDown,
        SmuflGlyph.accSagittalSharp143CUp,
        SmuflGlyph.accSagittalFlat143CDown,
        SmuflGlyph.accSagittalSharp11v49CUp,
        SmuflGlyph.accSagittalFlat11v49CDown,
        SmuflGlyph.accSagittalSharp19CUp,
        SmuflGlyph.accSagittalFlat19CDown,
        SmuflGlyph.accSagittalSharp7v19CUp,
        SmuflGlyph.accSagittalFlat7v19CDown,
        SmuflGlyph.accSagittalSharp49SUp,
        SmuflGlyph.accSagittalFlat49SDown,
        SmuflGlyph.accSagittalSharp23SUp,
        SmuflGlyph.accSagittalFlat23SDown,
        SmuflGlyph.accSagittalSharp5v13MUp,
        SmuflGlyph.accSagittalFlat5v13MDown,
        SmuflGlyph.accSagittalSharp11v19MUp,
        SmuflGlyph.accSagittalFlat11v19MDown,
        SmuflGlyph.accSagittalSharp49MUp,
        SmuflGlyph.accSagittalFlat49MDown,
        SmuflGlyph.accSagittalSharp5v49MUp,
        SmuflGlyph.accSagittalFlat5v49MDown,
        SmuflGlyph.accSagittalSharp49LUp,
        SmuflGlyph.accSagittalFlat49LDown,
        SmuflGlyph.accSagittalSharp11v19LUp,
        SmuflGlyph.accSagittalFlat11v19LDown,
        SmuflGlyph.accSagittalSharp5v13LUp,
        SmuflGlyph.accSagittalFlat5v13LDown,
        SmuflGlyph.accSagittalUnused3,
        SmuflGlyph.accSagittalUnused4,
        SmuflGlyph.accSagittalDoubleSharp23SDown,
        SmuflGlyph.accSagittalDoubleFlat23SUp,
        SmuflGlyph.accSagittalDoubleSharp49SDown,
        SmuflGlyph.accSagittalDoubleFlat49SUp,
        SmuflGlyph.accSagittalDoubleSharp7v19CDown,
        SmuflGlyph.accSagittalDoubleFlat7v19CUp,
        SmuflGlyph.accSagittalDoubleSharp19CDown,
        SmuflGlyph.accSagittalDoubleFlat19CUp,
        SmuflGlyph.accSagittalDoubleSharp11v49CDown,
        SmuflGlyph.accSagittalDoubleFlat11v49CUp,
        SmuflGlyph.accSagittalDoubleSharp143CDown,
        SmuflGlyph.accSagittalDoubleFlat143CUp,
        SmuflGlyph.accSagittalDoubleSharp17kDown,
        SmuflGlyph.accSagittalDoubleFlat17kUp,
        SmuflGlyph.accSagittalDoubleSharp19sDown,
        SmuflGlyph.accSagittalDoubleFlat19sUp,
      ];

  static const accSagittal19SchismaUp = SmuflGlyph.accSagittal19SchismaUp;

  static const accSagittal19SchismaDown = SmuflGlyph.accSagittal19SchismaDown;

  static const accSagittal17KleismaUp = SmuflGlyph.accSagittal17KleismaUp;

  static const accSagittal17KleismaDown = SmuflGlyph.accSagittal17KleismaDown;

  static const accSagittal143CommaUp = SmuflGlyph.accSagittal143CommaUp;

  static const accSagittal143CommaDown = SmuflGlyph.accSagittal143CommaDown;

  static const accSagittal11v49CommaUp = SmuflGlyph.accSagittal11v49CommaUp;

  static const accSagittal11v49CommaDown = SmuflGlyph.accSagittal11v49CommaDown;

  static const accSagittal19CommaUp = SmuflGlyph.accSagittal19CommaUp;

  static const accSagittal19CommaDown = SmuflGlyph.accSagittal19CommaDown;

  static const accSagittal7v19CommaUp = SmuflGlyph.accSagittal7v19CommaUp;

  static const accSagittal7v19CommaDown = SmuflGlyph.accSagittal7v19CommaDown;

  static const accSagittal49SmallDiesisUp =
      SmuflGlyph.accSagittal49SmallDiesisUp;

  static const accSagittal49SmallDiesisDown =
      SmuflGlyph.accSagittal49SmallDiesisDown;

  static const accSagittal23SmallDiesisUp =
      SmuflGlyph.accSagittal23SmallDiesisUp;

  static const accSagittal23SmallDiesisDown =
      SmuflGlyph.accSagittal23SmallDiesisDown;

  static const accSagittal5v13MediumDiesisUp =
      SmuflGlyph.accSagittal5v13MediumDiesisUp;

  static const accSagittal5v13MediumDiesisDown =
      SmuflGlyph.accSagittal5v13MediumDiesisDown;

  static const accSagittal11v19MediumDiesisUp =
      SmuflGlyph.accSagittal11v19MediumDiesisUp;

  static const accSagittal11v19MediumDiesisDown =
      SmuflGlyph.accSagittal11v19MediumDiesisDown;

  static const accSagittal49MediumDiesisUp =
      SmuflGlyph.accSagittal49MediumDiesisUp;

  static const accSagittal49MediumDiesisDown =
      SmuflGlyph.accSagittal49MediumDiesisDown;

  static const accSagittal5v49MediumDiesisUp =
      SmuflGlyph.accSagittal5v49MediumDiesisUp;

  static const accSagittal5v49MediumDiesisDown =
      SmuflGlyph.accSagittal5v49MediumDiesisDown;

  static const accSagittal49LargeDiesisUp =
      SmuflGlyph.accSagittal49LargeDiesisUp;

  static const accSagittal49LargeDiesisDown =
      SmuflGlyph.accSagittal49LargeDiesisDown;

  static const accSagittal11v19LargeDiesisUp =
      SmuflGlyph.accSagittal11v19LargeDiesisUp;

  static const accSagittal11v19LargeDiesisDown =
      SmuflGlyph.accSagittal11v19LargeDiesisDown;

  static const accSagittal5v13LargeDiesisUp =
      SmuflGlyph.accSagittal5v13LargeDiesisUp;

  static const accSagittal5v13LargeDiesisDown =
      SmuflGlyph.accSagittal5v13LargeDiesisDown;

  static const accSagittalSharp23SDown = SmuflGlyph.accSagittalSharp23SDown;

  static const accSagittalFlat23SUp = SmuflGlyph.accSagittalFlat23SUp;

  static const accSagittalSharp49SDown = SmuflGlyph.accSagittalSharp49SDown;

  static const accSagittalFlat49SUp = SmuflGlyph.accSagittalFlat49SUp;

  static const accSagittalSharp7v19CDown = SmuflGlyph.accSagittalSharp7v19CDown;

  static const accSagittalFlat7v19CUp = SmuflGlyph.accSagittalFlat7v19CUp;

  static const accSagittalSharp19CDown = SmuflGlyph.accSagittalSharp19CDown;

  static const accSagittalFlat19CUp = SmuflGlyph.accSagittalFlat19CUp;

  static const accSagittalSharp11v49CDown =
      SmuflGlyph.accSagittalSharp11v49CDown;

  static const accSagittalFlat11v49CUp = SmuflGlyph.accSagittalFlat11v49CUp;

  static const accSagittalSharp143CDown = SmuflGlyph.accSagittalSharp143CDown;

  static const accSagittalFlat143CUp = SmuflGlyph.accSagittalFlat143CUp;

  static const accSagittalSharp17kDown = SmuflGlyph.accSagittalSharp17kDown;

  static const accSagittalFlat17kUp = SmuflGlyph.accSagittalFlat17kUp;

  static const accSagittalSharp19sDown = SmuflGlyph.accSagittalSharp19sDown;

  static const accSagittalFlat19sUp = SmuflGlyph.accSagittalFlat19sUp;

  static const accSagittalSharp19sUp = SmuflGlyph.accSagittalSharp19sUp;

  static const accSagittalFlat19sDown = SmuflGlyph.accSagittalFlat19sDown;

  static const accSagittalSharp17kUp = SmuflGlyph.accSagittalSharp17kUp;

  static const accSagittalFlat17kDown = SmuflGlyph.accSagittalFlat17kDown;

  static const accSagittalSharp143CUp = SmuflGlyph.accSagittalSharp143CUp;

  static const accSagittalFlat143CDown = SmuflGlyph.accSagittalFlat143CDown;

  static const accSagittalSharp11v49CUp = SmuflGlyph.accSagittalSharp11v49CUp;

  static const accSagittalFlat11v49CDown = SmuflGlyph.accSagittalFlat11v49CDown;

  static const accSagittalSharp19CUp = SmuflGlyph.accSagittalSharp19CUp;

  static const accSagittalFlat19CDown = SmuflGlyph.accSagittalFlat19CDown;

  static const accSagittalSharp7v19CUp = SmuflGlyph.accSagittalSharp7v19CUp;

  static const accSagittalFlat7v19CDown = SmuflGlyph.accSagittalFlat7v19CDown;

  static const accSagittalSharp49SUp = SmuflGlyph.accSagittalSharp49SUp;

  static const accSagittalFlat49SDown = SmuflGlyph.accSagittalFlat49SDown;

  static const accSagittalSharp23SUp = SmuflGlyph.accSagittalSharp23SUp;

  static const accSagittalFlat23SDown = SmuflGlyph.accSagittalFlat23SDown;

  static const accSagittalSharp5v13MUp = SmuflGlyph.accSagittalSharp5v13MUp;

  static const accSagittalFlat5v13MDown = SmuflGlyph.accSagittalFlat5v13MDown;

  static const accSagittalSharp11v19MUp = SmuflGlyph.accSagittalSharp11v19MUp;

  static const accSagittalFlat11v19MDown = SmuflGlyph.accSagittalFlat11v19MDown;

  static const accSagittalSharp49MUp = SmuflGlyph.accSagittalSharp49MUp;

  static const accSagittalFlat49MDown = SmuflGlyph.accSagittalFlat49MDown;

  static const accSagittalSharp5v49MUp = SmuflGlyph.accSagittalSharp5v49MUp;

  static const accSagittalFlat5v49MDown = SmuflGlyph.accSagittalFlat5v49MDown;

  static const accSagittalSharp49LUp = SmuflGlyph.accSagittalSharp49LUp;

  static const accSagittalFlat49LDown = SmuflGlyph.accSagittalFlat49LDown;

  static const accSagittalSharp11v19LUp = SmuflGlyph.accSagittalSharp11v19LUp;

  static const accSagittalFlat11v19LDown = SmuflGlyph.accSagittalFlat11v19LDown;

  static const accSagittalSharp5v13LUp = SmuflGlyph.accSagittalSharp5v13LUp;

  static const accSagittalFlat5v13LDown = SmuflGlyph.accSagittalFlat5v13LDown;

  static const accSagittalUnused3 = SmuflGlyph.accSagittalUnused3;

  static const accSagittalUnused4 = SmuflGlyph.accSagittalUnused4;

  static const accSagittalDoubleSharp23SDown =
      SmuflGlyph.accSagittalDoubleSharp23SDown;

  static const accSagittalDoubleFlat23SUp =
      SmuflGlyph.accSagittalDoubleFlat23SUp;

  static const accSagittalDoubleSharp49SDown =
      SmuflGlyph.accSagittalDoubleSharp49SDown;

  static const accSagittalDoubleFlat49SUp =
      SmuflGlyph.accSagittalDoubleFlat49SUp;

  static const accSagittalDoubleSharp7v19CDown =
      SmuflGlyph.accSagittalDoubleSharp7v19CDown;

  static const accSagittalDoubleFlat7v19CUp =
      SmuflGlyph.accSagittalDoubleFlat7v19CUp;

  static const accSagittalDoubleSharp19CDown =
      SmuflGlyph.accSagittalDoubleSharp19CDown;

  static const accSagittalDoubleFlat19CUp =
      SmuflGlyph.accSagittalDoubleFlat19CUp;

  static const accSagittalDoubleSharp11v49CDown =
      SmuflGlyph.accSagittalDoubleSharp11v49CDown;

  static const accSagittalDoubleFlat11v49CUp =
      SmuflGlyph.accSagittalDoubleFlat11v49CUp;

  static const accSagittalDoubleSharp143CDown =
      SmuflGlyph.accSagittalDoubleSharp143CDown;

  static const accSagittalDoubleFlat143CUp =
      SmuflGlyph.accSagittalDoubleFlat143CUp;

  static const accSagittalDoubleSharp17kDown =
      SmuflGlyph.accSagittalDoubleSharp17kDown;

  static const accSagittalDoubleFlat17kUp =
      SmuflGlyph.accSagittalDoubleFlat17kUp;

  static const accSagittalDoubleSharp19sDown =
      SmuflGlyph.accSagittalDoubleSharp19sDown;

  static const accSagittalDoubleFlat19sUp =
      SmuflGlyph.accSagittalDoubleFlat19sUp;
}
