// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsSagittalTrojan extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accSagittal23CommaUp,
        SmuflGlyph.accSagittal23CommaDown,
        SmuflGlyph.accSagittal5v19CommaUp,
        SmuflGlyph.accSagittal5v19CommaDown,
        SmuflGlyph.accSagittal5v23SmallDiesisUp,
        SmuflGlyph.accSagittal5v23SmallDiesisDown,
        SmuflGlyph.accSagittalSharp5v23SDown,
        SmuflGlyph.accSagittalFlat5v23SUp,
        SmuflGlyph.accSagittalSharp5v19CDown,
        SmuflGlyph.accSagittalFlat5v19CUp,
        SmuflGlyph.accSagittalSharp23CDown,
        SmuflGlyph.accSagittalFlat23CUp,
        SmuflGlyph.accSagittalSharp23CUp,
        SmuflGlyph.accSagittalFlat23CDown,
        SmuflGlyph.accSagittalSharp5v19CUp,
        SmuflGlyph.accSagittalFlat5v19CDown,
        SmuflGlyph.accSagittalSharp5v23SUp,
        SmuflGlyph.accSagittalFlat5v23SDown,
        SmuflGlyph.accSagittalDoubleSharp5v23SDown,
        SmuflGlyph.accSagittalDoubleFlat5v23SUp,
        SmuflGlyph.accSagittalDoubleSharp5v19CDown,
        SmuflGlyph.accSagittalDoubleFlat5v19CUp,
        SmuflGlyph.accSagittalDoubleSharp23CDown,
        SmuflGlyph.accSagittalDoubleFlat23CUp,
      ];

  static const accSagittal23CommaUp = SmuflGlyph.accSagittal23CommaUp;

  static const accSagittal23CommaDown = SmuflGlyph.accSagittal23CommaDown;

  static const accSagittal5v19CommaUp = SmuflGlyph.accSagittal5v19CommaUp;

  static const accSagittal5v19CommaDown = SmuflGlyph.accSagittal5v19CommaDown;

  static const accSagittal5v23SmallDiesisUp =
      SmuflGlyph.accSagittal5v23SmallDiesisUp;

  static const accSagittal5v23SmallDiesisDown =
      SmuflGlyph.accSagittal5v23SmallDiesisDown;

  static const accSagittalSharp5v23SDown = SmuflGlyph.accSagittalSharp5v23SDown;

  static const accSagittalFlat5v23SUp = SmuflGlyph.accSagittalFlat5v23SUp;

  static const accSagittalSharp5v19CDown = SmuflGlyph.accSagittalSharp5v19CDown;

  static const accSagittalFlat5v19CUp = SmuflGlyph.accSagittalFlat5v19CUp;

  static const accSagittalSharp23CDown = SmuflGlyph.accSagittalSharp23CDown;

  static const accSagittalFlat23CUp = SmuflGlyph.accSagittalFlat23CUp;

  static const accSagittalSharp23CUp = SmuflGlyph.accSagittalSharp23CUp;

  static const accSagittalFlat23CDown = SmuflGlyph.accSagittalFlat23CDown;

  static const accSagittalSharp5v19CUp = SmuflGlyph.accSagittalSharp5v19CUp;

  static const accSagittalFlat5v19CDown = SmuflGlyph.accSagittalFlat5v19CDown;

  static const accSagittalSharp5v23SUp = SmuflGlyph.accSagittalSharp5v23SUp;

  static const accSagittalFlat5v23SDown = SmuflGlyph.accSagittalFlat5v23SDown;

  static const accSagittalDoubleSharp5v23SDown =
      SmuflGlyph.accSagittalDoubleSharp5v23SDown;

  static const accSagittalDoubleFlat5v23SUp =
      SmuflGlyph.accSagittalDoubleFlat5v23SUp;

  static const accSagittalDoubleSharp5v19CDown =
      SmuflGlyph.accSagittalDoubleSharp5v19CDown;

  static const accSagittalDoubleFlat5v19CUp =
      SmuflGlyph.accSagittalDoubleFlat5v19CUp;

  static const accSagittalDoubleSharp23CDown =
      SmuflGlyph.accSagittalDoubleSharp23CDown;

  static const accSagittalDoubleFlat23CUp =
      SmuflGlyph.accSagittalDoubleFlat23CUp;
}
