// Generated by tool.

part of "../glyph_class.dart";

class Accidentals24EDOArrows extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalQuarterToneFlatArrowUp,
        SmuflGlyph.accidentalThreeQuarterTonesFlatArrowDown,
        SmuflGlyph.accidentalQuarterToneSharpNaturalArrowUp,
        SmuflGlyph.accidentalQuarterToneFlatNaturalArrowDown,
        SmuflGlyph.accidentalThreeQuarterTonesSharpArrowUp,
        SmuflGlyph.accidentalQuarterToneSharpArrowDown,
        SmuflGlyph.accidentalFiveQuarterTonesSharpArrowUp,
        SmuflGlyph.accidentalThreeQuarterTonesSharpArrowDown,
        SmuflGlyph.accidentalThreeQuarterTonesFlatArrowUp,
        SmuflGlyph.accidentalFiveQuarterTonesFlatArrowDown,
        SmuflGlyph.accidentalArrowUp,
        SmuflGlyph.accidentalArrowDown,
      ];

  static const accidentalQuarterToneFlatArrowUp =
      SmuflGlyph.accidentalQuarterToneFlatArrowUp;

  static const accidentalThreeQuarterTonesFlatArrowDown =
      SmuflGlyph.accidentalThreeQuarterTonesFlatArrowDown;

  static const accidentalQuarterToneSharpNaturalArrowUp =
      SmuflGlyph.accidentalQuarterToneSharpNaturalArrowUp;

  static const accidentalQuarterToneFlatNaturalArrowDown =
      SmuflGlyph.accidentalQuarterToneFlatNaturalArrowDown;

  static const accidentalThreeQuarterTonesSharpArrowUp =
      SmuflGlyph.accidentalThreeQuarterTonesSharpArrowUp;

  static const accidentalQuarterToneSharpArrowDown =
      SmuflGlyph.accidentalQuarterToneSharpArrowDown;

  static const accidentalFiveQuarterTonesSharpArrowUp =
      SmuflGlyph.accidentalFiveQuarterTonesSharpArrowUp;

  static const accidentalThreeQuarterTonesSharpArrowDown =
      SmuflGlyph.accidentalThreeQuarterTonesSharpArrowDown;

  static const accidentalThreeQuarterTonesFlatArrowUp =
      SmuflGlyph.accidentalThreeQuarterTonesFlatArrowUp;

  static const accidentalFiveQuarterTonesFlatArrowDown =
      SmuflGlyph.accidentalFiveQuarterTonesFlatArrowDown;

  static const accidentalArrowUp = SmuflGlyph.accidentalArrowUp;

  static const accidentalArrowDown = SmuflGlyph.accidentalArrowDown;
}
