// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsSagittalPure extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalNatural,
        SmuflGlyph.accSagittalSharp25SDown,
        SmuflGlyph.accSagittalFlat25SUp,
        SmuflGlyph.accSagittalSharp7CDown,
        SmuflGlyph.accSagittalFlat7CUp,
        SmuflGlyph.accSagittalSharp5CDown,
        SmuflGlyph.accSagittalFlat5CUp,
        SmuflGlyph.accSagittalSharp5v7kDown,
        SmuflGlyph.accSagittalFlat5v7kUp,
        SmuflGlyph.accSagittalSharp,
        SmuflGlyph.accSagittalFlat,
        SmuflGlyph.accSagittalUnused1,
        SmuflGlyph.accSagittalUnused2,
        SmuflGlyph.accSagittalSharp5v7kUp,
        SmuflGlyph.accSagittalFlat5v7kDown,
        SmuflGlyph.accSagittalSharp5CUp,
        SmuflGlyph.accSagittalFlat5CDown,
        SmuflGlyph.accSagittalSharp7CUp,
        SmuflGlyph.accSagittalFlat7CDown,
        SmuflGlyph.accSagittalSharp25SUp,
        SmuflGlyph.accSagittalFlat25SDown,
        SmuflGlyph.accSagittalSharp35MUp,
        SmuflGlyph.accSagittalFlat35MDown,
        SmuflGlyph.accSagittalSharp11MUp,
        SmuflGlyph.accSagittalFlat11MDown,
        SmuflGlyph.accSagittalSharp11LUp,
        SmuflGlyph.accSagittalFlat11LDown,
        SmuflGlyph.accSagittalSharp35LUp,
        SmuflGlyph.accSagittalFlat35LDown,
        SmuflGlyph.accSagittalDoubleSharp25SDown,
        SmuflGlyph.accSagittalDoubleFlat25SUp,
        SmuflGlyph.accSagittalDoubleSharp7CDown,
        SmuflGlyph.accSagittalDoubleFlat7CUp,
        SmuflGlyph.accSagittalDoubleSharp5CDown,
        SmuflGlyph.accSagittalDoubleFlat5CUp,
        SmuflGlyph.accSagittalDoubleSharp5v7kDown,
        SmuflGlyph.accSagittalDoubleFlat5v7kUp,
        SmuflGlyph.accSagittalDoubleSharp,
        SmuflGlyph.accSagittalDoubleFlat,
      ];

  static const accidentalNatural = SmuflGlyph.accidentalNatural;

  static const accSagittalSharp25SDown = SmuflGlyph.accSagittalSharp25SDown;

  static const accSagittalFlat25SUp = SmuflGlyph.accSagittalFlat25SUp;

  static const accSagittalSharp7CDown = SmuflGlyph.accSagittalSharp7CDown;

  static const accSagittalFlat7CUp = SmuflGlyph.accSagittalFlat7CUp;

  static const accSagittalSharp5CDown = SmuflGlyph.accSagittalSharp5CDown;

  static const accSagittalFlat5CUp = SmuflGlyph.accSagittalFlat5CUp;

  static const accSagittalSharp5v7kDown = SmuflGlyph.accSagittalSharp5v7kDown;

  static const accSagittalFlat5v7kUp = SmuflGlyph.accSagittalFlat5v7kUp;

  static const accSagittalSharp = SmuflGlyph.accSagittalSharp;

  static const accSagittalFlat = SmuflGlyph.accSagittalFlat;

  static const accSagittalUnused1 = SmuflGlyph.accSagittalUnused1;

  static const accSagittalUnused2 = SmuflGlyph.accSagittalUnused2;

  static const accSagittalSharp5v7kUp = SmuflGlyph.accSagittalSharp5v7kUp;

  static const accSagittalFlat5v7kDown = SmuflGlyph.accSagittalFlat5v7kDown;

  static const accSagittalSharp5CUp = SmuflGlyph.accSagittalSharp5CUp;

  static const accSagittalFlat5CDown = SmuflGlyph.accSagittalFlat5CDown;

  static const accSagittalSharp7CUp = SmuflGlyph.accSagittalSharp7CUp;

  static const accSagittalFlat7CDown = SmuflGlyph.accSagittalFlat7CDown;

  static const accSagittalSharp25SUp = SmuflGlyph.accSagittalSharp25SUp;

  static const accSagittalFlat25SDown = SmuflGlyph.accSagittalFlat25SDown;

  static const accSagittalSharp35MUp = SmuflGlyph.accSagittalSharp35MUp;

  static const accSagittalFlat35MDown = SmuflGlyph.accSagittalFlat35MDown;

  static const accSagittalSharp11MUp = SmuflGlyph.accSagittalSharp11MUp;

  static const accSagittalFlat11MDown = SmuflGlyph.accSagittalFlat11MDown;

  static const accSagittalSharp11LUp = SmuflGlyph.accSagittalSharp11LUp;

  static const accSagittalFlat11LDown = SmuflGlyph.accSagittalFlat11LDown;

  static const accSagittalSharp35LUp = SmuflGlyph.accSagittalSharp35LUp;

  static const accSagittalFlat35LDown = SmuflGlyph.accSagittalFlat35LDown;

  static const accSagittalDoubleSharp25SDown =
      SmuflGlyph.accSagittalDoubleSharp25SDown;

  static const accSagittalDoubleFlat25SUp =
      SmuflGlyph.accSagittalDoubleFlat25SUp;

  static const accSagittalDoubleSharp7CDown =
      SmuflGlyph.accSagittalDoubleSharp7CDown;

  static const accSagittalDoubleFlat7CUp = SmuflGlyph.accSagittalDoubleFlat7CUp;

  static const accSagittalDoubleSharp5CDown =
      SmuflGlyph.accSagittalDoubleSharp5CDown;

  static const accSagittalDoubleFlat5CUp = SmuflGlyph.accSagittalDoubleFlat5CUp;

  static const accSagittalDoubleSharp5v7kDown =
      SmuflGlyph.accSagittalDoubleSharp5v7kDown;

  static const accSagittalDoubleFlat5v7kUp =
      SmuflGlyph.accSagittalDoubleFlat5v7kUp;

  static const accSagittalDoubleSharp = SmuflGlyph.accSagittalDoubleSharp;

  static const accSagittalDoubleFlat = SmuflGlyph.accSagittalDoubleFlat;
}
