// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsSagittalDiacritics extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accSagittalShaftUp,
        SmuflGlyph.accSagittalShaftDown,
        SmuflGlyph.accSagittalAcute,
        SmuflGlyph.accSagittalGrave,
      ];

  static const accSagittalShaftUp = SmuflGlyph.accSagittalShaftUp;

  static const accSagittalShaftDown = SmuflGlyph.accSagittalShaftDown;

  static const accSagittalAcute = SmuflGlyph.accSagittalAcute;

  static const accSagittalGrave = SmuflGlyph.accSagittalGrave;
}
