// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsStockhausen extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalRaisedStockhausen,
        SmuflGlyph.accidentalLoweredStockhausen,
        SmuflGlyph.accidentalFlatRaisedStockhausen,
        SmuflGlyph.accidentalFlatLoweredStockhausen,
        SmuflGlyph.accidentalNaturalRaisedStockhausen,
        SmuflGlyph.accidentalNaturalLoweredStockhausen,
        SmuflGlyph.accidentalSharpRaisedStockhausen,
        SmuflGlyph.accidentalSharpLoweredStockhausen,
        SmuflGlyph.accidentalOneQuarterToneSharpStockhausen,
        SmuflGlyph.accidentalOneQuarterToneFlatStockhausen,
        SmuflGlyph.accidentalThreeQuarterTonesSharpStockhausen,
        SmuflGlyph.accidentalFlatRepeatedSpaceStockhausen,
        SmuflGlyph.accidentalFlatRepeatedLineStockhausen,
        SmuflGlyph.accidentalSharpRepeatedSpaceStockhausen,
        SmuflGlyph.accidentalSharpRepeatedLineStockhausen,
      ];

  static const accidentalRaisedStockhausen =
      SmuflGlyph.accidentalRaisedStockhausen;

  static const accidentalLoweredStockhausen =
      SmuflGlyph.accidentalLoweredStockhausen;

  static const accidentalFlatRaisedStockhausen =
      SmuflGlyph.accidentalFlatRaisedStockhausen;

  static const accidentalFlatLoweredStockhausen =
      SmuflGlyph.accidentalFlatLoweredStockhausen;

  static const accidentalNaturalRaisedStockhausen =
      SmuflGlyph.accidentalNaturalRaisedStockhausen;

  static const accidentalNaturalLoweredStockhausen =
      SmuflGlyph.accidentalNaturalLoweredStockhausen;

  static const accidentalSharpRaisedStockhausen =
      SmuflGlyph.accidentalSharpRaisedStockhausen;

  static const accidentalSharpLoweredStockhausen =
      SmuflGlyph.accidentalSharpLoweredStockhausen;

  static const accidentalOneQuarterToneSharpStockhausen =
      SmuflGlyph.accidentalOneQuarterToneSharpStockhausen;

  static const accidentalOneQuarterToneFlatStockhausen =
      SmuflGlyph.accidentalOneQuarterToneFlatStockhausen;

  static const accidentalThreeQuarterTonesSharpStockhausen =
      SmuflGlyph.accidentalThreeQuarterTonesSharpStockhausen;

  static const accidentalFlatRepeatedSpaceStockhausen =
      SmuflGlyph.accidentalFlatRepeatedSpaceStockhausen;

  static const accidentalFlatRepeatedLineStockhausen =
      SmuflGlyph.accidentalFlatRepeatedLineStockhausen;

  static const accidentalSharpRepeatedSpaceStockhausen =
      SmuflGlyph.accidentalSharpRepeatedSpaceStockhausen;

  static const accidentalSharpRepeatedLineStockhausen =
      SmuflGlyph.accidentalSharpRepeatedLineStockhausen;
}
