// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsArabic extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalDoubleFlatArabic,
        SmuflGlyph.accidentalThreeQuarterTonesFlatArabic,
        SmuflGlyph.accidentalFlatArabic,
        SmuflGlyph.accidentalQuarterToneFlatArabic,
        SmuflGlyph.accidentalNaturalArabic,
        SmuflGlyph.accidentalQuarterToneSharpArabic,
        SmuflGlyph.accidentalSharpArabic,
        SmuflGlyph.accidentalThreeQuarterTonesSharpArabic,
        SmuflGlyph.accidentalDoubleSharpArabic,
      ];

  static const accidentalDoubleFlatArabic =
      SmuflGlyph.accidentalDoubleFlatArabic;

  static const accidentalThreeQuarterTonesFlatArabic =
      SmuflGlyph.accidentalThreeQuarterTonesFlatArabic;

  static const accidentalFlatArabic = SmuflGlyph.accidentalFlatArabic;

  static const accidentalQuarterToneFlatArabic =
      SmuflGlyph.accidentalQuarterToneFlatArabic;

  static const accidentalNaturalArabic = SmuflGlyph.accidentalNaturalArabic;

  static const accidentalQuarterToneSharpArabic =
      SmuflGlyph.accidentalQuarterToneSharpArabic;

  static const accidentalSharpArabic = SmuflGlyph.accidentalSharpArabic;

  static const accidentalThreeQuarterTonesSharpArabic =
      SmuflGlyph.accidentalThreeQuarterTonesSharpArabic;

  static const accidentalDoubleSharpArabic =
      SmuflGlyph.accidentalDoubleSharpArabic;
}
