// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsAEU extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalBuyukMucennebFlat,
        SmuflGlyph.accidentalKucukMucennebFlat,
        SmuflGlyph.accidentalBakiyeFlat,
        SmuflGlyph.accidentalKomaFlat,
        SmuflGlyph.accidentalKomaSharp,
        SmuflGlyph.accidentalBakiyeSharp,
        SmuflGlyph.accidentalKucukMucennebSharp,
        SmuflGlyph.accidentalBuyukMucennebSharp,
      ];

  static const accidentalBuyukMucennebFlat =
      SmuflGlyph.accidentalBuyukMucennebFlat;

  static const accidentalKucukMucennebFlat =
      SmuflGlyph.accidentalKucukMucennebFlat;

  static const accidentalBakiyeFlat = SmuflGlyph.accidentalBakiyeFlat;

  static const accidentalKomaFlat = SmuflGlyph.accidentalKomaFlat;

  static const accidentalKomaSharp = SmuflGlyph.accidentalKomaSharp;

  static const accidentalBakiyeSharp = SmuflGlyph.accidentalBakiyeSharp;

  static const accidentalKucukMucennebSharp =
      SmuflGlyph.accidentalKucukMucennebSharp;

  static const accidentalBuyukMucennebSharp =
      SmuflGlyph.accidentalBuyukMucennebSharp;
}
