// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsSagittalMixed extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalFlat,
        SmuflGlyph.accidentalNatural,
        SmuflGlyph.accidentalSharp,
        SmuflGlyph.accidentalDoubleFlat,
        SmuflGlyph.accSagittal5v7KleismaUp,
        SmuflGlyph.accSagittal5v7KleismaDown,
        SmuflGlyph.accSagittal5CommaUp,
        SmuflGlyph.accSagittal5CommaDown,
        SmuflGlyph.accSagittal7CommaUp,
        SmuflGlyph.accSagittal7CommaDown,
        SmuflGlyph.accSagittal25SmallDiesisUp,
        SmuflGlyph.accSagittal25SmallDiesisDown,
        SmuflGlyph.accSagittal35MediumDiesisUp,
        SmuflGlyph.accSagittal35MediumDiesisDown,
        SmuflGlyph.accSagittal11MediumDiesisUp,
        SmuflGlyph.accSagittal11MediumDiesisDown,
        SmuflGlyph.accSagittal11LargeDiesisUp,
        SmuflGlyph.accSagittal11LargeDiesisDown,
        SmuflGlyph.accSagittal35LargeDiesisUp,
        SmuflGlyph.accSagittal35LargeDiesisDown,
        SmuflGlyph.accidentalLargeDoubleSharp,
      ];

  static const accidentalFlat = SmuflGlyph.accidentalFlat;

  static const accidentalNatural = SmuflGlyph.accidentalNatural;

  static const accidentalSharp = SmuflGlyph.accidentalSharp;

  static const accidentalDoubleFlat = SmuflGlyph.accidentalDoubleFlat;

  static const accSagittal5v7KleismaUp = SmuflGlyph.accSagittal5v7KleismaUp;

  static const accSagittal5v7KleismaDown = SmuflGlyph.accSagittal5v7KleismaDown;

  static const accSagittal5CommaUp = SmuflGlyph.accSagittal5CommaUp;

  static const accSagittal5CommaDown = SmuflGlyph.accSagittal5CommaDown;

  static const accSagittal7CommaUp = SmuflGlyph.accSagittal7CommaUp;

  static const accSagittal7CommaDown = SmuflGlyph.accSagittal7CommaDown;

  static const accSagittal25SmallDiesisUp =
      SmuflGlyph.accSagittal25SmallDiesisUp;

  static const accSagittal25SmallDiesisDown =
      SmuflGlyph.accSagittal25SmallDiesisDown;

  static const accSagittal35MediumDiesisUp =
      SmuflGlyph.accSagittal35MediumDiesisUp;

  static const accSagittal35MediumDiesisDown =
      SmuflGlyph.accSagittal35MediumDiesisDown;

  static const accSagittal11MediumDiesisUp =
      SmuflGlyph.accSagittal11MediumDiesisUp;

  static const accSagittal11MediumDiesisDown =
      SmuflGlyph.accSagittal11MediumDiesisDown;

  static const accSagittal11LargeDiesisUp =
      SmuflGlyph.accSagittal11LargeDiesisUp;

  static const accSagittal11LargeDiesisDown =
      SmuflGlyph.accSagittal11LargeDiesisDown;

  static const accSagittal35LargeDiesisUp =
      SmuflGlyph.accSagittal35LargeDiesisUp;

  static const accSagittal35LargeDiesisDown =
      SmuflGlyph.accSagittal35LargeDiesisDown;

  static const accidentalLargeDoubleSharp =
      SmuflGlyph.accidentalLargeDoubleSharp;
}
