// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsStandard extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalFlat,
        SmuflGlyph.accidentalNatural,
        SmuflGlyph.accidentalSharp,
        SmuflGlyph.accidentalDoubleSharp,
        SmuflGlyph.accidentalDoubleFlat,
        SmuflGlyph.accidentalTripleSharp,
        SmuflGlyph.accidentalTripleFlat,
        SmuflGlyph.accidentalNaturalFlat,
        SmuflGlyph.accidentalNaturalSharp,
        SmuflGlyph.accidentalSharpSharp,
        SmuflGlyph.accidentalParensLeft,
        SmuflGlyph.accidentalParensRight,
      ];

  static const accidentalFlat = SmuflGlyph.accidentalFlat;

  static const accidentalNatural = SmuflGlyph.accidentalNatural;

  static const accidentalSharp = SmuflGlyph.accidentalSharp;

  static const accidentalDoubleSharp = SmuflGlyph.accidentalDoubleSharp;

  static const accidentalDoubleFlat = SmuflGlyph.accidentalDoubleFlat;

  static const accidentalTripleSharp = SmuflGlyph.accidentalTripleSharp;

  static const accidentalTripleFlat = SmuflGlyph.accidentalTripleFlat;

  static const accidentalNaturalFlat = SmuflGlyph.accidentalNaturalFlat;

  static const accidentalNaturalSharp = SmuflGlyph.accidentalNaturalSharp;

  static const accidentalSharpSharp = SmuflGlyph.accidentalSharpSharp;

  static const accidentalParensLeft = SmuflGlyph.accidentalParensLeft;

  static const accidentalParensRight = SmuflGlyph.accidentalParensRight;
}
