// Generated by tool.

part of "../glyph_class.dart";

class AccidentalsHelmholtzEllis extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.accidentalDoubleFlatOneArrowDown,
        SmuflGlyph.accidentalFlatOneArrowDown,
        SmuflGlyph.accidentalNaturalOneArrowDown,
        SmuflGlyph.accidentalSharpOneArrowDown,
        SmuflGlyph.accidentalDoubleSharpOneArrowDown,
        SmuflGlyph.accidentalDoubleFlatOneArrowUp,
        SmuflGlyph.accidentalFlatOneArrowUp,
        SmuflGlyph.accidentalNaturalOneArrowUp,
        SmuflGlyph.accidentalSharpOneArrowUp,
        SmuflGlyph.accidentalDoubleSharpOneArrowUp,
        SmuflGlyph.accidentalDoubleFlatTwoArrowsDown,
        SmuflGlyph.accidentalFlatTwoArrowsDown,
        SmuflGlyph.accidentalNaturalTwoArrowsDown,
        SmuflGlyph.accidentalSharpTwoArrowsDown,
        SmuflGlyph.accidentalDoubleSharpTwoArrowsDown,
        SmuflGlyph.accidentalDoubleFlatTwoArrowsUp,
        SmuflGlyph.accidentalFlatTwoArrowsUp,
        SmuflGlyph.accidentalNaturalTwoArrowsUp,
        SmuflGlyph.accidentalSharpTwoArrowsUp,
        SmuflGlyph.accidentalDoubleSharpTwoArrowsUp,
        SmuflGlyph.accidentalDoubleFlatThreeArrowsDown,
        SmuflGlyph.accidentalFlatThreeArrowsDown,
        SmuflGlyph.accidentalNaturalThreeArrowsDown,
        SmuflGlyph.accidentalSharpThreeArrowsDown,
        SmuflGlyph.accidentalDoubleSharpThreeArrowsDown,
        SmuflGlyph.accidentalDoubleFlatThreeArrowsUp,
        SmuflGlyph.accidentalFlatThreeArrowsUp,
        SmuflGlyph.accidentalNaturalThreeArrowsUp,
        SmuflGlyph.accidentalSharpThreeArrowsUp,
        SmuflGlyph.accidentalDoubleSharpThreeArrowsUp,
        SmuflGlyph.accidentalLowerOneSeptimalComma,
        SmuflGlyph.accidentalRaiseOneSeptimalComma,
        SmuflGlyph.accidentalLowerTwoSeptimalCommas,
        SmuflGlyph.accidentalRaiseTwoSeptimalCommas,
        SmuflGlyph.accidentalLowerOneUndecimalQuartertone,
        SmuflGlyph.accidentalRaiseOneUndecimalQuartertone,
        SmuflGlyph.accidentalLowerOneTridecimalQuartertone,
        SmuflGlyph.accidentalRaiseOneTridecimalQuartertone,
        SmuflGlyph.accidentalCombiningLower17Schisma,
        SmuflGlyph.accidentalCombiningRaise17Schisma,
        SmuflGlyph.accidentalCombiningLower19Schisma,
        SmuflGlyph.accidentalCombiningRaise19Schisma,
        SmuflGlyph.accidentalCombiningLower23Limit29LimitComma,
        SmuflGlyph.accidentalCombiningRaise23Limit29LimitComma,
        SmuflGlyph.accidentalCombiningLower31Schisma,
        SmuflGlyph.accidentalCombiningRaise31Schisma,
        SmuflGlyph.accidentalCombiningOpenCurlyBrace,
        SmuflGlyph.accidentalCombiningCloseCurlyBrace,
        SmuflGlyph.accidentalDoubleFlatEqualTempered,
        SmuflGlyph.accidentalFlatEqualTempered,
        SmuflGlyph.accidentalNaturalEqualTempered,
        SmuflGlyph.accidentalSharpEqualTempered,
        SmuflGlyph.accidentalDoubleSharpEqualTempered,
        SmuflGlyph.accidentalQuarterFlatEqualTempered,
        SmuflGlyph.accidentalQuarterSharpEqualTempered,
        SmuflGlyph.accidentalCombiningLower53LimitComma,
        SmuflGlyph.accidentalCombiningRaise53LimitComma,
        SmuflGlyph.accidentalEnharmonicTilde,
        SmuflGlyph.accidentalEnharmonicAlmostEqualTo,
        SmuflGlyph.accidentalEnharmonicEquals,
        SmuflGlyph.accidentalCombiningLower29LimitComma,
        SmuflGlyph.accidentalCombiningRaise29LimitComma,
        SmuflGlyph.accidentalCombiningLower37Quartertone,
        SmuflGlyph.accidentalCombiningRaise37Quartertone,
        SmuflGlyph.accidentalCombiningLower41Comma,
        SmuflGlyph.accidentalCombiningRaise41Comma,
        SmuflGlyph.accidentalCombiningLower43Comma,
        SmuflGlyph.accidentalCombiningRaise43Comma,
        SmuflGlyph.accidentalCombiningLower47Quartertone,
        SmuflGlyph.accidentalCombiningRaise47Quartertone,
      ];

  static const accidentalDoubleFlatOneArrowDown =
      SmuflGlyph.accidentalDoubleFlatOneArrowDown;

  static const accidentalFlatOneArrowDown =
      SmuflGlyph.accidentalFlatOneArrowDown;

  static const accidentalNaturalOneArrowDown =
      SmuflGlyph.accidentalNaturalOneArrowDown;

  static const accidentalSharpOneArrowDown =
      SmuflGlyph.accidentalSharpOneArrowDown;

  static const accidentalDoubleSharpOneArrowDown =
      SmuflGlyph.accidentalDoubleSharpOneArrowDown;

  static const accidentalDoubleFlatOneArrowUp =
      SmuflGlyph.accidentalDoubleFlatOneArrowUp;

  static const accidentalFlatOneArrowUp = SmuflGlyph.accidentalFlatOneArrowUp;

  static const accidentalNaturalOneArrowUp =
      SmuflGlyph.accidentalNaturalOneArrowUp;

  static const accidentalSharpOneArrowUp = SmuflGlyph.accidentalSharpOneArrowUp;

  static const accidentalDoubleSharpOneArrowUp =
      SmuflGlyph.accidentalDoubleSharpOneArrowUp;

  static const accidentalDoubleFlatTwoArrowsDown =
      SmuflGlyph.accidentalDoubleFlatTwoArrowsDown;

  static const accidentalFlatTwoArrowsDown =
      SmuflGlyph.accidentalFlatTwoArrowsDown;

  static const accidentalNaturalTwoArrowsDown =
      SmuflGlyph.accidentalNaturalTwoArrowsDown;

  static const accidentalSharpTwoArrowsDown =
      SmuflGlyph.accidentalSharpTwoArrowsDown;

  static const accidentalDoubleSharpTwoArrowsDown =
      SmuflGlyph.accidentalDoubleSharpTwoArrowsDown;

  static const accidentalDoubleFlatTwoArrowsUp =
      SmuflGlyph.accidentalDoubleFlatTwoArrowsUp;

  static const accidentalFlatTwoArrowsUp = SmuflGlyph.accidentalFlatTwoArrowsUp;

  static const accidentalNaturalTwoArrowsUp =
      SmuflGlyph.accidentalNaturalTwoArrowsUp;

  static const accidentalSharpTwoArrowsUp =
      SmuflGlyph.accidentalSharpTwoArrowsUp;

  static const accidentalDoubleSharpTwoArrowsUp =
      SmuflGlyph.accidentalDoubleSharpTwoArrowsUp;

  static const accidentalDoubleFlatThreeArrowsDown =
      SmuflGlyph.accidentalDoubleFlatThreeArrowsDown;

  static const accidentalFlatThreeArrowsDown =
      SmuflGlyph.accidentalFlatThreeArrowsDown;

  static const accidentalNaturalThreeArrowsDown =
      SmuflGlyph.accidentalNaturalThreeArrowsDown;

  static const accidentalSharpThreeArrowsDown =
      SmuflGlyph.accidentalSharpThreeArrowsDown;

  static const accidentalDoubleSharpThreeArrowsDown =
      SmuflGlyph.accidentalDoubleSharpThreeArrowsDown;

  static const accidentalDoubleFlatThreeArrowsUp =
      SmuflGlyph.accidentalDoubleFlatThreeArrowsUp;

  static const accidentalFlatThreeArrowsUp =
      SmuflGlyph.accidentalFlatThreeArrowsUp;

  static const accidentalNaturalThreeArrowsUp =
      SmuflGlyph.accidentalNaturalThreeArrowsUp;

  static const accidentalSharpThreeArrowsUp =
      SmuflGlyph.accidentalSharpThreeArrowsUp;

  static const accidentalDoubleSharpThreeArrowsUp =
      SmuflGlyph.accidentalDoubleSharpThreeArrowsUp;

  static const accidentalLowerOneSeptimalComma =
      SmuflGlyph.accidentalLowerOneSeptimalComma;

  static const accidentalRaiseOneSeptimalComma =
      SmuflGlyph.accidentalRaiseOneSeptimalComma;

  static const accidentalLowerTwoSeptimalCommas =
      SmuflGlyph.accidentalLowerTwoSeptimalCommas;

  static const accidentalRaiseTwoSeptimalCommas =
      SmuflGlyph.accidentalRaiseTwoSeptimalCommas;

  static const accidentalLowerOneUndecimalQuartertone =
      SmuflGlyph.accidentalLowerOneUndecimalQuartertone;

  static const accidentalRaiseOneUndecimalQuartertone =
      SmuflGlyph.accidentalRaiseOneUndecimalQuartertone;

  static const accidentalLowerOneTridecimalQuartertone =
      SmuflGlyph.accidentalLowerOneTridecimalQuartertone;

  static const accidentalRaiseOneTridecimalQuartertone =
      SmuflGlyph.accidentalRaiseOneTridecimalQuartertone;

  static const accidentalCombiningLower17Schisma =
      SmuflGlyph.accidentalCombiningLower17Schisma;

  static const accidentalCombiningRaise17Schisma =
      SmuflGlyph.accidentalCombiningRaise17Schisma;

  static const accidentalCombiningLower19Schisma =
      SmuflGlyph.accidentalCombiningLower19Schisma;

  static const accidentalCombiningRaise19Schisma =
      SmuflGlyph.accidentalCombiningRaise19Schisma;

  static const accidentalCombiningLower23Limit29LimitComma =
      SmuflGlyph.accidentalCombiningLower23Limit29LimitComma;

  static const accidentalCombiningRaise23Limit29LimitComma =
      SmuflGlyph.accidentalCombiningRaise23Limit29LimitComma;

  static const accidentalCombiningLower31Schisma =
      SmuflGlyph.accidentalCombiningLower31Schisma;

  static const accidentalCombiningRaise31Schisma =
      SmuflGlyph.accidentalCombiningRaise31Schisma;

  static const accidentalCombiningOpenCurlyBrace =
      SmuflGlyph.accidentalCombiningOpenCurlyBrace;

  static const accidentalCombiningCloseCurlyBrace =
      SmuflGlyph.accidentalCombiningCloseCurlyBrace;

  static const accidentalDoubleFlatEqualTempered =
      SmuflGlyph.accidentalDoubleFlatEqualTempered;

  static const accidentalFlatEqualTempered =
      SmuflGlyph.accidentalFlatEqualTempered;

  static const accidentalNaturalEqualTempered =
      SmuflGlyph.accidentalNaturalEqualTempered;

  static const accidentalSharpEqualTempered =
      SmuflGlyph.accidentalSharpEqualTempered;

  static const accidentalDoubleSharpEqualTempered =
      SmuflGlyph.accidentalDoubleSharpEqualTempered;

  static const accidentalQuarterFlatEqualTempered =
      SmuflGlyph.accidentalQuarterFlatEqualTempered;

  static const accidentalQuarterSharpEqualTempered =
      SmuflGlyph.accidentalQuarterSharpEqualTempered;

  static const accidentalCombiningLower53LimitComma =
      SmuflGlyph.accidentalCombiningLower53LimitComma;

  static const accidentalCombiningRaise53LimitComma =
      SmuflGlyph.accidentalCombiningRaise53LimitComma;

  static const accidentalEnharmonicTilde = SmuflGlyph.accidentalEnharmonicTilde;

  static const accidentalEnharmonicAlmostEqualTo =
      SmuflGlyph.accidentalEnharmonicAlmostEqualTo;

  static const accidentalEnharmonicEquals =
      SmuflGlyph.accidentalEnharmonicEquals;

  static const accidentalCombiningLower29LimitComma =
      SmuflGlyph.accidentalCombiningLower29LimitComma;

  static const accidentalCombiningRaise29LimitComma =
      SmuflGlyph.accidentalCombiningRaise29LimitComma;

  static const accidentalCombiningLower37Quartertone =
      SmuflGlyph.accidentalCombiningLower37Quartertone;

  static const accidentalCombiningRaise37Quartertone =
      SmuflGlyph.accidentalCombiningRaise37Quartertone;

  static const accidentalCombiningLower41Comma =
      SmuflGlyph.accidentalCombiningLower41Comma;

  static const accidentalCombiningRaise41Comma =
      SmuflGlyph.accidentalCombiningRaise41Comma;

  static const accidentalCombiningLower43Comma =
      SmuflGlyph.accidentalCombiningLower43Comma;

  static const accidentalCombiningRaise43Comma =
      SmuflGlyph.accidentalCombiningRaise43Comma;

  static const accidentalCombiningLower47Quartertone =
      SmuflGlyph.accidentalCombiningLower47Quartertone;

  static const accidentalCombiningRaise47Quartertone =
      SmuflGlyph.accidentalCombiningRaise47Quartertone;
}
