// Generated by tool.

part of "../glyph_class.dart";

class Articulations extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.articAccentAbove,
        SmuflGlyph.articAccentBelow,
        SmuflGlyph.articStaccatoAbove,
        SmuflGlyph.articStaccatoBelow,
        SmuflGlyph.articTenutoAbove,
        SmuflGlyph.articTenutoBelow,
        SmuflGlyph.articStaccatissimoAbove,
        SmuflGlyph.articStaccatissimoBelow,
        SmuflGlyph.articStaccatissimoWedgeAbove,
        SmuflGlyph.articStaccatissimoWedgeBelow,
        SmuflGlyph.articStaccatissimoStrokeAbove,
        SmuflGlyph.articStaccatissimoStrokeBelow,
        SmuflGlyph.articMarcatoAbove,
        SmuflGlyph.articMarcatoBelow,
        SmuflGlyph.articMarcatoStaccatoAbove,
        SmuflGlyph.articMarcatoStaccatoBelow,
        SmuflGlyph.articAccentStaccatoAbove,
        SmuflGlyph.articAccentStaccatoBelow,
        SmuflGlyph.articTenutoStaccatoAbove,
        SmuflGlyph.articTenutoStaccatoBelow,
        SmuflGlyph.articTenutoAccentAbove,
        SmuflGlyph.articTenutoAccentBelow,
        SmuflGlyph.articStressAbove,
        SmuflGlyph.articStressBelow,
        SmuflGlyph.articUnstressAbove,
        SmuflGlyph.articUnstressBelow,
        SmuflGlyph.articLaissezVibrerAbove,
        SmuflGlyph.articLaissezVibrerBelow,
        SmuflGlyph.articSoftAccentAbove,
        SmuflGlyph.articSoftAccentBelow,
        SmuflGlyph.articSoftAccentStaccatoAbove,
        SmuflGlyph.articSoftAccentStaccatoBelow,
        SmuflGlyph.articSoftAccentTenutoAbove,
        SmuflGlyph.articSoftAccentTenutoBelow,
        SmuflGlyph.articSoftAccentTenutoStaccatoAbove,
        SmuflGlyph.articSoftAccentTenutoStaccatoBelow,
      ];

  static const articAccentAbove = SmuflGlyph.articAccentAbove;

  static const articAccentBelow = SmuflGlyph.articAccentBelow;

  static const articStaccatoAbove = SmuflGlyph.articStaccatoAbove;

  static const articStaccatoBelow = SmuflGlyph.articStaccatoBelow;

  static const articTenutoAbove = SmuflGlyph.articTenutoAbove;

  static const articTenutoBelow = SmuflGlyph.articTenutoBelow;

  static const articStaccatissimoAbove = SmuflGlyph.articStaccatissimoAbove;

  static const articStaccatissimoBelow = SmuflGlyph.articStaccatissimoBelow;

  static const articStaccatissimoWedgeAbove =
      SmuflGlyph.articStaccatissimoWedgeAbove;

  static const articStaccatissimoWedgeBelow =
      SmuflGlyph.articStaccatissimoWedgeBelow;

  static const articStaccatissimoStrokeAbove =
      SmuflGlyph.articStaccatissimoStrokeAbove;

  static const articStaccatissimoStrokeBelow =
      SmuflGlyph.articStaccatissimoStrokeBelow;

  static const articMarcatoAbove = SmuflGlyph.articMarcatoAbove;

  static const articMarcatoBelow = SmuflGlyph.articMarcatoBelow;

  static const articMarcatoStaccatoAbove = SmuflGlyph.articMarcatoStaccatoAbove;

  static const articMarcatoStaccatoBelow = SmuflGlyph.articMarcatoStaccatoBelow;

  static const articAccentStaccatoAbove = SmuflGlyph.articAccentStaccatoAbove;

  static const articAccentStaccatoBelow = SmuflGlyph.articAccentStaccatoBelow;

  static const articTenutoStaccatoAbove = SmuflGlyph.articTenutoStaccatoAbove;

  static const articTenutoStaccatoBelow = SmuflGlyph.articTenutoStaccatoBelow;

  static const articTenutoAccentAbove = SmuflGlyph.articTenutoAccentAbove;

  static const articTenutoAccentBelow = SmuflGlyph.articTenutoAccentBelow;

  static const articStressAbove = SmuflGlyph.articStressAbove;

  static const articStressBelow = SmuflGlyph.articStressBelow;

  static const articUnstressAbove = SmuflGlyph.articUnstressAbove;

  static const articUnstressBelow = SmuflGlyph.articUnstressBelow;

  static const articLaissezVibrerAbove = SmuflGlyph.articLaissezVibrerAbove;

  static const articLaissezVibrerBelow = SmuflGlyph.articLaissezVibrerBelow;

  static const articSoftAccentAbove = SmuflGlyph.articSoftAccentAbove;

  static const articSoftAccentBelow = SmuflGlyph.articSoftAccentBelow;

  static const articSoftAccentStaccatoAbove =
      SmuflGlyph.articSoftAccentStaccatoAbove;

  static const articSoftAccentStaccatoBelow =
      SmuflGlyph.articSoftAccentStaccatoBelow;

  static const articSoftAccentTenutoAbove =
      SmuflGlyph.articSoftAccentTenutoAbove;

  static const articSoftAccentTenutoBelow =
      SmuflGlyph.articSoftAccentTenutoBelow;

  static const articSoftAccentTenutoStaccatoAbove =
      SmuflGlyph.articSoftAccentTenutoStaccatoAbove;

  static const articSoftAccentTenutoStaccatoBelow =
      SmuflGlyph.articSoftAccentTenutoStaccatoBelow;
}
