// Generated by tool.

part of "../glyph_class.dart";

class ArticulationsAbove extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.articAccentAbove,
        SmuflGlyph.articStaccatoAbove,
        SmuflGlyph.articTenutoAbove,
        SmuflGlyph.articStaccatissimoAbove,
        SmuflGlyph.articStaccatissimoWedgeAbove,
        SmuflGlyph.articStaccatissimoStrokeAbove,
        SmuflGlyph.articMarcatoAbove,
        SmuflGlyph.articMarcatoStaccatoAbove,
        SmuflGlyph.articAccentStaccatoAbove,
        SmuflGlyph.articTenutoStaccatoAbove,
        SmuflGlyph.articTenutoAccentAbove,
        SmuflGlyph.articStressAbove,
        SmuflGlyph.articUnstressAbove,
        SmuflGlyph.articLaissezVibrerAbove,
        SmuflGlyph.articSoftAccentAbove,
        SmuflGlyph.articSoftAccentStaccatoAbove,
        SmuflGlyph.articSoftAccentTenutoAbove,
        SmuflGlyph.articSoftAccentTenutoStaccatoAbove,
      ];

  static const articAccentAbove = SmuflGlyph.articAccentAbove;

  static const articStaccatoAbove = SmuflGlyph.articStaccatoAbove;

  static const articTenutoAbove = SmuflGlyph.articTenutoAbove;

  static const articStaccatissimoAbove = SmuflGlyph.articStaccatissimoAbove;

  static const articStaccatissimoWedgeAbove =
      SmuflGlyph.articStaccatissimoWedgeAbove;

  static const articStaccatissimoStrokeAbove =
      SmuflGlyph.articStaccatissimoStrokeAbove;

  static const articMarcatoAbove = SmuflGlyph.articMarcatoAbove;

  static const articMarcatoStaccatoAbove = SmuflGlyph.articMarcatoStaccatoAbove;

  static const articAccentStaccatoAbove = SmuflGlyph.articAccentStaccatoAbove;

  static const articTenutoStaccatoAbove = SmuflGlyph.articTenutoStaccatoAbove;

  static const articTenutoAccentAbove = SmuflGlyph.articTenutoAccentAbove;

  static const articStressAbove = SmuflGlyph.articStressAbove;

  static const articUnstressAbove = SmuflGlyph.articUnstressAbove;

  static const articLaissezVibrerAbove = SmuflGlyph.articLaissezVibrerAbove;

  static const articSoftAccentAbove = SmuflGlyph.articSoftAccentAbove;

  static const articSoftAccentStaccatoAbove =
      SmuflGlyph.articSoftAccentStaccatoAbove;

  static const articSoftAccentTenutoAbove =
      SmuflGlyph.articSoftAccentTenutoAbove;

  static const articSoftAccentTenutoStaccatoAbove =
      SmuflGlyph.articSoftAccentTenutoStaccatoAbove;
}
