// Generated by tool.

part of "../glyph_class.dart";

class ArticulationsBelow extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.articAccentBelow,
        SmuflGlyph.articStaccatoBelow,
        SmuflGlyph.articTenutoBelow,
        SmuflGlyph.articStaccatissimoBelow,
        SmuflGlyph.articStaccatissimoWedgeBelow,
        SmuflGlyph.articStaccatissimoStrokeBelow,
        SmuflGlyph.articMarcatoBelow,
        SmuflGlyph.articMarcatoStaccatoBelow,
        SmuflGlyph.articAccentStaccatoBelow,
        SmuflGlyph.articTenutoStaccatoBelow,
        SmuflGlyph.articTenutoAccentBelow,
        SmuflGlyph.articStressBelow,
        SmuflGlyph.articUnstressBelow,
        SmuflGlyph.articLaissezVibrerBelow,
        SmuflGlyph.articSoftAccentBelow,
        SmuflGlyph.articSoftAccentStaccatoBelow,
        SmuflGlyph.articSoftAccentTenutoBelow,
        SmuflGlyph.articSoftAccentTenutoStaccatoBelow,
      ];

  static const articAccentBelow = SmuflGlyph.articAccentBelow;

  static const articStaccatoBelow = SmuflGlyph.articStaccatoBelow;

  static const articTenutoBelow = SmuflGlyph.articTenutoBelow;

  static const articStaccatissimoBelow = SmuflGlyph.articStaccatissimoBelow;

  static const articStaccatissimoWedgeBelow =
      SmuflGlyph.articStaccatissimoWedgeBelow;

  static const articStaccatissimoStrokeBelow =
      SmuflGlyph.articStaccatissimoStrokeBelow;

  static const articMarcatoBelow = SmuflGlyph.articMarcatoBelow;

  static const articMarcatoStaccatoBelow = SmuflGlyph.articMarcatoStaccatoBelow;

  static const articAccentStaccatoBelow = SmuflGlyph.articAccentStaccatoBelow;

  static const articTenutoStaccatoBelow = SmuflGlyph.articTenutoStaccatoBelow;

  static const articTenutoAccentBelow = SmuflGlyph.articTenutoAccentBelow;

  static const articStressBelow = SmuflGlyph.articStressBelow;

  static const articUnstressBelow = SmuflGlyph.articUnstressBelow;

  static const articLaissezVibrerBelow = SmuflGlyph.articLaissezVibrerBelow;

  static const articSoftAccentBelow = SmuflGlyph.articSoftAccentBelow;

  static const articSoftAccentStaccatoBelow =
      SmuflGlyph.articSoftAccentStaccatoBelow;

  static const articSoftAccentTenutoBelow =
      SmuflGlyph.articSoftAccentTenutoBelow;

  static const articSoftAccentTenutoStaccatoBelow =
      SmuflGlyph.articSoftAccentTenutoStaccatoBelow;
}
