// Generated by tool.

part of "../glyph_class.dart";

class ClefsF extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.fClef,
        SmuflGlyph.fClef15mb,
        SmuflGlyph.fClef8vb,
        SmuflGlyph.fClef8va,
        SmuflGlyph.fClef15ma,
        SmuflGlyph.fClefArrowUp,
        SmuflGlyph.fClefArrowDown,
        SmuflGlyph.fClefReversed,
      ];

  static const fClef = SmuflGlyph.fClef;

  static const fClef15mb = SmuflGlyph.fClef15mb;

  static const fClef8vb = SmuflGlyph.fClef8vb;

  static const fClef8va = SmuflGlyph.fClef8va;

  static const fClef15ma = SmuflGlyph.fClef15ma;

  static const fClefArrowUp = SmuflGlyph.fClefArrowUp;

  static const fClefArrowDown = SmuflGlyph.fClefArrowDown;

  static const fClefReversed = SmuflGlyph.fClefReversed;
}
