// Generated by tool.

part of "../glyph_class.dart";

class ClefsC extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.cClef,
        SmuflGlyph.cClef8vb,
        SmuflGlyph.cClefArrowUp,
        SmuflGlyph.cClefArrowDown,
        SmuflGlyph.cClefSquare,
        SmuflGlyph.cClefCombining,
        SmuflGlyph.cClefReversed,
      ];

  static const cClef = SmuflGlyph.cClef;

  static const cClef8vb = SmuflGlyph.cClef8vb;

  static const cClefArrowUp = SmuflGlyph.cClefArrowUp;

  static const cClefArrowDown = SmuflGlyph.cClefArrowDown;

  static const cClefSquare = SmuflGlyph.cClefSquare;

  static const cClefCombining = SmuflGlyph.cClefCombining;

  static const cClefReversed = SmuflGlyph.cClefReversed;
}
