// Generated by tool.

part of "../glyph_class.dart";

class Clefs extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.gClef,
        SmuflGlyph.gClef15mb,
        SmuflGlyph.gClef8vb,
        SmuflGlyph.gClef8va,
        SmuflGlyph.gClef15ma,
        SmuflGlyph.gClef8vbOld,
        SmuflGlyph.gClef8vbCClef,
        SmuflGlyph.gClef8vbParens,
        SmuflGlyph.gClefLigatedNumberBelow,
        SmuflGlyph.gClefLigatedNumberAbove,
        SmuflGlyph.gClefArrowUp,
        SmuflGlyph.gClefArrowDown,
        SmuflGlyph.cClef,
        SmuflGlyph.cClef8vb,
        SmuflGlyph.cClefArrowUp,
        SmuflGlyph.cClefArrowDown,
        SmuflGlyph.cClefSquare,
        SmuflGlyph.cClefCombining,
        SmuflGlyph.fClef,
        SmuflGlyph.fClef15mb,
        SmuflGlyph.fClef8vb,
        SmuflGlyph.fClef8va,
        SmuflGlyph.fClef15ma,
        SmuflGlyph.fClefArrowUp,
        SmuflGlyph.fClefArrowDown,
        SmuflGlyph.unpitchedPercussionClef1,
        SmuflGlyph.unpitchedPercussionClef2,
        SmuflGlyph.semipitchedPercussionClef1,
        SmuflGlyph.semipitchedPercussionClef2,
        SmuflGlyph.g6stringTabClef,
        SmuflGlyph.g4stringTabClef,
        SmuflGlyph.schaefferClef,
        SmuflGlyph.schaefferPreviousClef,
        SmuflGlyph.schaefferGClefToFClef,
        SmuflGlyph.schaefferFClefToGClef,
        SmuflGlyph.gClefReversed,
        SmuflGlyph.gClefTurned,
        SmuflGlyph.cClefReversed,
        SmuflGlyph.fClefReversed,
        SmuflGlyph.fClefTurned,
        SmuflGlyph.bridgeClef,
        SmuflGlyph.accdnDiatonicClef,
        SmuflGlyph.gClefChange,
        SmuflGlyph.cClefChange,
        SmuflGlyph.fClefChange,
        SmuflGlyph.clef8,
        SmuflGlyph.clef15,
        SmuflGlyph.clefChangeCombining,
        SmuflGlyph.indianDrumClef,
      ];

  static const gClef = SmuflGlyph.gClef;

  static const gClef15mb = SmuflGlyph.gClef15mb;

  static const gClef8vb = SmuflGlyph.gClef8vb;

  static const gClef8va = SmuflGlyph.gClef8va;

  static const gClef15ma = SmuflGlyph.gClef15ma;

  static const gClef8vbOld = SmuflGlyph.gClef8vbOld;

  static const gClef8vbCClef = SmuflGlyph.gClef8vbCClef;

  static const gClef8vbParens = SmuflGlyph.gClef8vbParens;

  static const gClefLigatedNumberBelow = SmuflGlyph.gClefLigatedNumberBelow;

  static const gClefLigatedNumberAbove = SmuflGlyph.gClefLigatedNumberAbove;

  static const gClefArrowUp = SmuflGlyph.gClefArrowUp;

  static const gClefArrowDown = SmuflGlyph.gClefArrowDown;

  static const cClef = SmuflGlyph.cClef;

  static const cClef8vb = SmuflGlyph.cClef8vb;

  static const cClefArrowUp = SmuflGlyph.cClefArrowUp;

  static const cClefArrowDown = SmuflGlyph.cClefArrowDown;

  static const cClefSquare = SmuflGlyph.cClefSquare;

  static const cClefCombining = SmuflGlyph.cClefCombining;

  static const fClef = SmuflGlyph.fClef;

  static const fClef15mb = SmuflGlyph.fClef15mb;

  static const fClef8vb = SmuflGlyph.fClef8vb;

  static const fClef8va = SmuflGlyph.fClef8va;

  static const fClef15ma = SmuflGlyph.fClef15ma;

  static const fClefArrowUp = SmuflGlyph.fClefArrowUp;

  static const fClefArrowDown = SmuflGlyph.fClefArrowDown;

  static const unpitchedPercussionClef1 = SmuflGlyph.unpitchedPercussionClef1;

  static const unpitchedPercussionClef2 = SmuflGlyph.unpitchedPercussionClef2;

  static const semipitchedPercussionClef1 =
      SmuflGlyph.semipitchedPercussionClef1;

  static const semipitchedPercussionClef2 =
      SmuflGlyph.semipitchedPercussionClef2;

  static const g6stringTabClef = SmuflGlyph.g6stringTabClef;

  static const g4stringTabClef = SmuflGlyph.g4stringTabClef;

  static const schaefferClef = SmuflGlyph.schaefferClef;

  static const schaefferPreviousClef = SmuflGlyph.schaefferPreviousClef;

  static const schaefferGClefToFClef = SmuflGlyph.schaefferGClefToFClef;

  static const schaefferFClefToGClef = SmuflGlyph.schaefferFClefToGClef;

  static const gClefReversed = SmuflGlyph.gClefReversed;

  static const gClefTurned = SmuflGlyph.gClefTurned;

  static const cClefReversed = SmuflGlyph.cClefReversed;

  static const fClefReversed = SmuflGlyph.fClefReversed;

  static const fClefTurned = SmuflGlyph.fClefTurned;

  static const bridgeClef = SmuflGlyph.bridgeClef;

  static const accdnDiatonicClef = SmuflGlyph.accdnDiatonicClef;

  static const gClefChange = SmuflGlyph.gClefChange;

  static const cClefChange = SmuflGlyph.cClefChange;

  static const fClefChange = SmuflGlyph.fClefChange;

  static const clef8 = SmuflGlyph.clef8;

  static const clef15 = SmuflGlyph.clef15;

  static const clefChangeCombining = SmuflGlyph.clefChangeCombining;

  static const indianDrumClef = SmuflGlyph.indianDrumClef;
}
