// Generated by tool.

part of "../glyph_class.dart";

class ClefsG extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.gClef,
        SmuflGlyph.gClef15mb,
        SmuflGlyph.gClef8vb,
        SmuflGlyph.gClef8va,
        SmuflGlyph.gClef15ma,
        SmuflGlyph.gClef8vbOld,
        SmuflGlyph.gClef8vbCClef,
        SmuflGlyph.gClef8vbParens,
        SmuflGlyph.gClefLigatedNumberBelow,
        SmuflGlyph.gClefLigatedNumberAbove,
        SmuflGlyph.gClefArrowUp,
        SmuflGlyph.gClefArrowDown,
        SmuflGlyph.gClefReversed,
      ];

  static const gClef = SmuflGlyph.gClef;

  static const gClef15mb = SmuflGlyph.gClef15mb;

  static const gClef8vb = SmuflGlyph.gClef8vb;

  static const gClef8va = SmuflGlyph.gClef8va;

  static const gClef15ma = SmuflGlyph.gClef15ma;

  static const gClef8vbOld = SmuflGlyph.gClef8vbOld;

  static const gClef8vbCClef = SmuflGlyph.gClef8vbCClef;

  static const gClef8vbParens = SmuflGlyph.gClef8vbParens;

  static const gClefLigatedNumberBelow = SmuflGlyph.gClefLigatedNumberBelow;

  static const gClefLigatedNumberAbove = SmuflGlyph.gClefLigatedNumberAbove;

  static const gClefArrowUp = SmuflGlyph.gClefArrowUp;

  static const gClefArrowDown = SmuflGlyph.gClefArrowDown;

  static const gClefReversed = SmuflGlyph.gClefReversed;
}
