// Generated by tool.

part of "../glyph_class.dart";

class Dynamics extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.dynamicPiano,
        SmuflGlyph.dynamicMezzo,
        SmuflGlyph.dynamicForte,
        SmuflGlyph.dynamicRinforzando,
        SmuflGlyph.dynamicSforzando,
        SmuflGlyph.dynamicZ,
        SmuflGlyph.dynamicNiente,
        SmuflGlyph.dynamicPPPPPP,
        SmuflGlyph.dynamicPPPPP,
        SmuflGlyph.dynamicPPPP,
        SmuflGlyph.dynamicPPP,
        SmuflGlyph.dynamicPP,
        SmuflGlyph.dynamicMP,
        SmuflGlyph.dynamicMF,
        SmuflGlyph.dynamicPF,
        SmuflGlyph.dynamicFF,
        SmuflGlyph.dynamicFFF,
        SmuflGlyph.dynamicFFFF,
        SmuflGlyph.dynamicFFFFF,
        SmuflGlyph.dynamicFFFFFF,
        SmuflGlyph.dynamicFortePiano,
        SmuflGlyph.dynamicForzando,
        SmuflGlyph.dynamicSforzando1,
        SmuflGlyph.dynamicSforzandoPiano,
        SmuflGlyph.dynamicSforzandoPianissimo,
        SmuflGlyph.dynamicSforzato,
        SmuflGlyph.dynamicSforzatoPiano,
        SmuflGlyph.dynamicSforzatoFF,
        SmuflGlyph.dynamicRinforzando1,
        SmuflGlyph.dynamicRinforzando2,
        SmuflGlyph.dynamicCrescendoHairpin,
        SmuflGlyph.dynamicDiminuendoHairpin,
        SmuflGlyph.dynamicMessaDiVoce,
        SmuflGlyph.dynamicNienteForHairpin,
        SmuflGlyph.dynamicHairpinParenthesisLeft,
        SmuflGlyph.dynamicHairpinParenthesisRight,
        SmuflGlyph.dynamicHairpinBracketLeft,
        SmuflGlyph.dynamicHairpinBracketRight,
        SmuflGlyph.dynamicCombinedSeparatorColon,
        SmuflGlyph.dynamicCombinedSeparatorHyphen,
        SmuflGlyph.dynamicCombinedSeparatorSpace,
        SmuflGlyph.dynamicCombinedSeparatorSlash,
      ];

  static const dynamicPiano = SmuflGlyph.dynamicPiano;

  static const dynamicMezzo = SmuflGlyph.dynamicMezzo;

  static const dynamicForte = SmuflGlyph.dynamicForte;

  static const dynamicRinforzando = SmuflGlyph.dynamicRinforzando;

  static const dynamicSforzando = SmuflGlyph.dynamicSforzando;

  static const dynamicZ = SmuflGlyph.dynamicZ;

  static const dynamicNiente = SmuflGlyph.dynamicNiente;

  static const dynamicPPPPPP = SmuflGlyph.dynamicPPPPPP;

  static const dynamicPPPPP = SmuflGlyph.dynamicPPPPP;

  static const dynamicPPPP = SmuflGlyph.dynamicPPPP;

  static const dynamicPPP = SmuflGlyph.dynamicPPP;

  static const dynamicPP = SmuflGlyph.dynamicPP;

  static const dynamicMP = SmuflGlyph.dynamicMP;

  static const dynamicMF = SmuflGlyph.dynamicMF;

  static const dynamicPF = SmuflGlyph.dynamicPF;

  static const dynamicFF = SmuflGlyph.dynamicFF;

  static const dynamicFFF = SmuflGlyph.dynamicFFF;

  static const dynamicFFFF = SmuflGlyph.dynamicFFFF;

  static const dynamicFFFFF = SmuflGlyph.dynamicFFFFF;

  static const dynamicFFFFFF = SmuflGlyph.dynamicFFFFFF;

  static const dynamicFortePiano = SmuflGlyph.dynamicFortePiano;

  static const dynamicForzando = SmuflGlyph.dynamicForzando;

  static const dynamicSforzando1 = SmuflGlyph.dynamicSforzando1;

  static const dynamicSforzandoPiano = SmuflGlyph.dynamicSforzandoPiano;

  static const dynamicSforzandoPianissimo =
      SmuflGlyph.dynamicSforzandoPianissimo;

  static const dynamicSforzato = SmuflGlyph.dynamicSforzato;

  static const dynamicSforzatoPiano = SmuflGlyph.dynamicSforzatoPiano;

  static const dynamicSforzatoFF = SmuflGlyph.dynamicSforzatoFF;

  static const dynamicRinforzando1 = SmuflGlyph.dynamicRinforzando1;

  static const dynamicRinforzando2 = SmuflGlyph.dynamicRinforzando2;

  static const dynamicCrescendoHairpin = SmuflGlyph.dynamicCrescendoHairpin;

  static const dynamicDiminuendoHairpin = SmuflGlyph.dynamicDiminuendoHairpin;

  static const dynamicMessaDiVoce = SmuflGlyph.dynamicMessaDiVoce;

  static const dynamicNienteForHairpin = SmuflGlyph.dynamicNienteForHairpin;

  static const dynamicHairpinParenthesisLeft =
      SmuflGlyph.dynamicHairpinParenthesisLeft;

  static const dynamicHairpinParenthesisRight =
      SmuflGlyph.dynamicHairpinParenthesisRight;

  static const dynamicHairpinBracketLeft = SmuflGlyph.dynamicHairpinBracketLeft;

  static const dynamicHairpinBracketRight =
      SmuflGlyph.dynamicHairpinBracketRight;

  static const dynamicCombinedSeparatorColon =
      SmuflGlyph.dynamicCombinedSeparatorColon;

  static const dynamicCombinedSeparatorHyphen =
      SmuflGlyph.dynamicCombinedSeparatorHyphen;

  static const dynamicCombinedSeparatorSpace =
      SmuflGlyph.dynamicCombinedSeparatorSpace;

  static const dynamicCombinedSeparatorSlash =
      SmuflGlyph.dynamicCombinedSeparatorSlash;
}
