// Generated by tool.

part of "../glyph_class.dart";

class FiguredBass extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.figbass0,
        SmuflGlyph.figbass1,
        SmuflGlyph.figbass2,
        SmuflGlyph.figbass2Raised,
        SmuflGlyph.figbass3,
        SmuflGlyph.figbass4,
        SmuflGlyph.figbass4Raised,
        SmuflGlyph.figbass5,
        SmuflGlyph.figbass5Raised1,
        SmuflGlyph.figbass5Raised2,
        SmuflGlyph.figbass5Raised3,
        SmuflGlyph.figbass6,
        SmuflGlyph.figbass6Raised,
        SmuflGlyph.figbass7,
        SmuflGlyph.figbass7Raised1,
        SmuflGlyph.figbass7Raised2,
        SmuflGlyph.figbass8,
        SmuflGlyph.figbass9,
        SmuflGlyph.figbass9Raised,
        SmuflGlyph.figbassDoubleFlat,
        SmuflGlyph.figbassFlat,
        SmuflGlyph.figbassNatural,
        SmuflGlyph.figbassSharp,
        SmuflGlyph.figbassDoubleSharp,
        SmuflGlyph.figbassBracketLeft,
        SmuflGlyph.figbassBracketRight,
        SmuflGlyph.figbassParensLeft,
        SmuflGlyph.figbassParensRight,
        SmuflGlyph.figbassPlus,
        SmuflGlyph.figbassCombiningRaising,
        SmuflGlyph.figbassCombiningLowering,
        SmuflGlyph.figbass6Raised2,
        SmuflGlyph.figbass7Diminished,
        SmuflGlyph.figbassTripleFlat,
        SmuflGlyph.figbassTripleSharp,
      ];

  static const figbass0 = SmuflGlyph.figbass0;

  static const figbass1 = SmuflGlyph.figbass1;

  static const figbass2 = SmuflGlyph.figbass2;

  static const figbass2Raised = SmuflGlyph.figbass2Raised;

  static const figbass3 = SmuflGlyph.figbass3;

  static const figbass4 = SmuflGlyph.figbass4;

  static const figbass4Raised = SmuflGlyph.figbass4Raised;

  static const figbass5 = SmuflGlyph.figbass5;

  static const figbass5Raised1 = SmuflGlyph.figbass5Raised1;

  static const figbass5Raised2 = SmuflGlyph.figbass5Raised2;

  static const figbass5Raised3 = SmuflGlyph.figbass5Raised3;

  static const figbass6 = SmuflGlyph.figbass6;

  static const figbass6Raised = SmuflGlyph.figbass6Raised;

  static const figbass7 = SmuflGlyph.figbass7;

  static const figbass7Raised1 = SmuflGlyph.figbass7Raised1;

  static const figbass7Raised2 = SmuflGlyph.figbass7Raised2;

  static const figbass8 = SmuflGlyph.figbass8;

  static const figbass9 = SmuflGlyph.figbass9;

  static const figbass9Raised = SmuflGlyph.figbass9Raised;

  static const figbassDoubleFlat = SmuflGlyph.figbassDoubleFlat;

  static const figbassFlat = SmuflGlyph.figbassFlat;

  static const figbassNatural = SmuflGlyph.figbassNatural;

  static const figbassSharp = SmuflGlyph.figbassSharp;

  static const figbassDoubleSharp = SmuflGlyph.figbassDoubleSharp;

  static const figbassBracketLeft = SmuflGlyph.figbassBracketLeft;

  static const figbassBracketRight = SmuflGlyph.figbassBracketRight;

  static const figbassParensLeft = SmuflGlyph.figbassParensLeft;

  static const figbassParensRight = SmuflGlyph.figbassParensRight;

  static const figbassPlus = SmuflGlyph.figbassPlus;

  static const figbassCombiningRaising = SmuflGlyph.figbassCombiningRaising;

  static const figbassCombiningLowering = SmuflGlyph.figbassCombiningLowering;

  static const figbass6Raised2 = SmuflGlyph.figbass6Raised2;

  static const figbass7Diminished = SmuflGlyph.figbass7Diminished;

  static const figbassTripleFlat = SmuflGlyph.figbassTripleFlat;

  static const figbassTripleSharp = SmuflGlyph.figbassTripleSharp;
}
