// Generated by tool.

part of "../glyph_class.dart";

class ForTextBasedApplications extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.bracket,
        SmuflGlyph.staff1Line,
        SmuflGlyph.staff2Lines,
        SmuflGlyph.staff3Lines,
        SmuflGlyph.staff4Lines,
        SmuflGlyph.staff5Lines,
        SmuflGlyph.staff6Lines,
        SmuflGlyph.staff1LineWide,
        SmuflGlyph.staff2LinesWide,
        SmuflGlyph.staff3LinesWide,
        SmuflGlyph.staff4LinesWide,
        SmuflGlyph.staff5LinesWide,
        SmuflGlyph.staff6LinesWide,
        SmuflGlyph.staff1LineNarrow,
        SmuflGlyph.staff2LinesNarrow,
        SmuflGlyph.staff3LinesNarrow,
        SmuflGlyph.staff4LinesNarrow,
        SmuflGlyph.staff5LinesNarrow,
        SmuflGlyph.staff6LinesNarrow,
        SmuflGlyph.barlineSingle,
        SmuflGlyph.barlineDouble,
        SmuflGlyph.barlineFinal,
        SmuflGlyph.barlineReverseFinal,
        SmuflGlyph.barlineHeavy,
        SmuflGlyph.barlineHeavyHeavy,
        SmuflGlyph.barlineDashed,
        SmuflGlyph.barlineDotted,
        SmuflGlyph.barlineShort,
        SmuflGlyph.barlineTick,
        SmuflGlyph.repeatLeft,
        SmuflGlyph.repeatRight,
        SmuflGlyph.repeatRightLeft,
        SmuflGlyph.dalSegno,
        SmuflGlyph.daCapo,
        SmuflGlyph.leftRepeatSmall,
        SmuflGlyph.rightRepeatSmall,
        SmuflGlyph.timeSigCombNumerator,
        SmuflGlyph.timeSigCombDenominator,
        SmuflGlyph.noteDoubleWhole,
        SmuflGlyph.noteDoubleWholeSquare,
        SmuflGlyph.noteWhole,
        SmuflGlyph.noteHalfUp,
        SmuflGlyph.noteHalfDown,
        SmuflGlyph.noteQuarterUp,
        SmuflGlyph.noteQuarterDown,
        SmuflGlyph.note8thUp,
        SmuflGlyph.note8thDown,
        SmuflGlyph.note16thUp,
        SmuflGlyph.note16thDown,
        SmuflGlyph.note32ndUp,
        SmuflGlyph.note32ndDown,
        SmuflGlyph.note64thUp,
        SmuflGlyph.note64thDown,
        SmuflGlyph.note128thUp,
        SmuflGlyph.note128thDown,
        SmuflGlyph.note256thUp,
        SmuflGlyph.note256thDown,
        SmuflGlyph.note512thUp,
        SmuflGlyph.note512thDown,
        SmuflGlyph.note1024thUp,
        SmuflGlyph.note1024thDown,
        SmuflGlyph.augmentationDot,
        SmuflGlyph.textBlackNoteShortStem,
        SmuflGlyph.textBlackNoteLongStem,
        SmuflGlyph.textBlackNoteFrac8thShortStem,
        SmuflGlyph.textBlackNoteFrac8thLongStem,
        SmuflGlyph.textBlackNoteFrac16thShortStem,
        SmuflGlyph.textBlackNoteFrac16thLongStem,
        SmuflGlyph.textBlackNoteFrac32ndLongStem,
        SmuflGlyph.textCont8thBeamShortStem,
        SmuflGlyph.textCont8thBeamLongStem,
        SmuflGlyph.textCont16thBeamShortStem,
        SmuflGlyph.textCont16thBeamLongStem,
        SmuflGlyph.textCont32ndBeamLongStem,
        SmuflGlyph.textAugmentationDot,
        SmuflGlyph.textTie,
        SmuflGlyph.textTupletBracketStartShortStem,
        SmuflGlyph.textTuplet3ShortStem,
        SmuflGlyph.textTupletBracketEndShortStem,
        SmuflGlyph.textTupletBracketStartLongStem,
        SmuflGlyph.textTuplet3LongStem,
        SmuflGlyph.textTupletBracketEndLongStem,
        SmuflGlyph.stem,
        SmuflGlyph.stemSprechgesang,
        SmuflGlyph.stemSwished,
        SmuflGlyph.stemPendereckiTremolo,
        SmuflGlyph.stemSulPonticello,
        SmuflGlyph.stemBowOnBridge,
        SmuflGlyph.stemBowOnTailpiece,
        SmuflGlyph.stemBuzzRoll,
        SmuflGlyph.stemDamp,
        SmuflGlyph.stemVibratoPulse,
        SmuflGlyph.stemMultiphonicsBlack,
        SmuflGlyph.stemMultiphonicsWhite,
        SmuflGlyph.stemMultiphonicsBlackWhite,
        SmuflGlyph.stemSussurando,
        SmuflGlyph.stemRimShot,
        SmuflGlyph.stemHarpStringNoise,
        SmuflGlyph.restHBarMiddle,
        SmuflGlyph.chantStaff,
        SmuflGlyph.chantStaffWide,
        SmuflGlyph.chantStaffNarrow,
        SmuflGlyph.chantDivisioMinima,
        SmuflGlyph.chantDivisioMaior,
        SmuflGlyph.chantDivisioMaxima,
        SmuflGlyph.chantDivisioFinalis,
        SmuflGlyph.chantVirgula,
        SmuflGlyph.chantCaesura,
        SmuflGlyph.staffPosRaise1,
        SmuflGlyph.staffPosRaise2,
        SmuflGlyph.staffPosRaise3,
        SmuflGlyph.staffPosRaise4,
        SmuflGlyph.staffPosRaise5,
        SmuflGlyph.staffPosRaise6,
        SmuflGlyph.staffPosRaise7,
        SmuflGlyph.staffPosRaise8,
        SmuflGlyph.staffPosLower1,
        SmuflGlyph.staffPosLower2,
        SmuflGlyph.staffPosLower3,
        SmuflGlyph.staffPosLower4,
        SmuflGlyph.staffPosLower5,
        SmuflGlyph.staffPosLower6,
        SmuflGlyph.staffPosLower7,
        SmuflGlyph.staffPosLower8,
        SmuflGlyph.luteStaff6Lines,
        SmuflGlyph.luteStaff6LinesWide,
        SmuflGlyph.luteStaff6LinesNarrow,
        SmuflGlyph.luteBarlineStartRepeat,
        SmuflGlyph.luteBarlineEndRepeat,
        SmuflGlyph.luteBarlineFinal,
        SmuflGlyph.metricModulationArrowLeft,
        SmuflGlyph.metricModulationArrowRight,
      ];

  static const bracket = SmuflGlyph.bracket;

  static const staff1Line = SmuflGlyph.staff1Line;

  static const staff2Lines = SmuflGlyph.staff2Lines;

  static const staff3Lines = SmuflGlyph.staff3Lines;

  static const staff4Lines = SmuflGlyph.staff4Lines;

  static const staff5Lines = SmuflGlyph.staff5Lines;

  static const staff6Lines = SmuflGlyph.staff6Lines;

  static const staff1LineWide = SmuflGlyph.staff1LineWide;

  static const staff2LinesWide = SmuflGlyph.staff2LinesWide;

  static const staff3LinesWide = SmuflGlyph.staff3LinesWide;

  static const staff4LinesWide = SmuflGlyph.staff4LinesWide;

  static const staff5LinesWide = SmuflGlyph.staff5LinesWide;

  static const staff6LinesWide = SmuflGlyph.staff6LinesWide;

  static const staff1LineNarrow = SmuflGlyph.staff1LineNarrow;

  static const staff2LinesNarrow = SmuflGlyph.staff2LinesNarrow;

  static const staff3LinesNarrow = SmuflGlyph.staff3LinesNarrow;

  static const staff4LinesNarrow = SmuflGlyph.staff4LinesNarrow;

  static const staff5LinesNarrow = SmuflGlyph.staff5LinesNarrow;

  static const staff6LinesNarrow = SmuflGlyph.staff6LinesNarrow;

  static const barlineSingle = SmuflGlyph.barlineSingle;

  static const barlineDouble = SmuflGlyph.barlineDouble;

  static const barlineFinal = SmuflGlyph.barlineFinal;

  static const barlineReverseFinal = SmuflGlyph.barlineReverseFinal;

  static const barlineHeavy = SmuflGlyph.barlineHeavy;

  static const barlineHeavyHeavy = SmuflGlyph.barlineHeavyHeavy;

  static const barlineDashed = SmuflGlyph.barlineDashed;

  static const barlineDotted = SmuflGlyph.barlineDotted;

  static const barlineShort = SmuflGlyph.barlineShort;

  static const barlineTick = SmuflGlyph.barlineTick;

  static const repeatLeft = SmuflGlyph.repeatLeft;

  static const repeatRight = SmuflGlyph.repeatRight;

  static const repeatRightLeft = SmuflGlyph.repeatRightLeft;

  static const dalSegno = SmuflGlyph.dalSegno;

  static const daCapo = SmuflGlyph.daCapo;

  static const leftRepeatSmall = SmuflGlyph.leftRepeatSmall;

  static const rightRepeatSmall = SmuflGlyph.rightRepeatSmall;

  static const timeSigCombNumerator = SmuflGlyph.timeSigCombNumerator;

  static const timeSigCombDenominator = SmuflGlyph.timeSigCombDenominator;

  static const noteDoubleWhole = SmuflGlyph.noteDoubleWhole;

  static const noteDoubleWholeSquare = SmuflGlyph.noteDoubleWholeSquare;

  static const noteWhole = SmuflGlyph.noteWhole;

  static const noteHalfUp = SmuflGlyph.noteHalfUp;

  static const noteHalfDown = SmuflGlyph.noteHalfDown;

  static const noteQuarterUp = SmuflGlyph.noteQuarterUp;

  static const noteQuarterDown = SmuflGlyph.noteQuarterDown;

  static const note8thUp = SmuflGlyph.note8thUp;

  static const note8thDown = SmuflGlyph.note8thDown;

  static const note16thUp = SmuflGlyph.note16thUp;

  static const note16thDown = SmuflGlyph.note16thDown;

  static const note32ndUp = SmuflGlyph.note32ndUp;

  static const note32ndDown = SmuflGlyph.note32ndDown;

  static const note64thUp = SmuflGlyph.note64thUp;

  static const note64thDown = SmuflGlyph.note64thDown;

  static const note128thUp = SmuflGlyph.note128thUp;

  static const note128thDown = SmuflGlyph.note128thDown;

  static const note256thUp = SmuflGlyph.note256thUp;

  static const note256thDown = SmuflGlyph.note256thDown;

  static const note512thUp = SmuflGlyph.note512thUp;

  static const note512thDown = SmuflGlyph.note512thDown;

  static const note1024thUp = SmuflGlyph.note1024thUp;

  static const note1024thDown = SmuflGlyph.note1024thDown;

  static const augmentationDot = SmuflGlyph.augmentationDot;

  static const textBlackNoteShortStem = SmuflGlyph.textBlackNoteShortStem;

  static const textBlackNoteLongStem = SmuflGlyph.textBlackNoteLongStem;

  static const textBlackNoteFrac8thShortStem =
      SmuflGlyph.textBlackNoteFrac8thShortStem;

  static const textBlackNoteFrac8thLongStem =
      SmuflGlyph.textBlackNoteFrac8thLongStem;

  static const textBlackNoteFrac16thShortStem =
      SmuflGlyph.textBlackNoteFrac16thShortStem;

  static const textBlackNoteFrac16thLongStem =
      SmuflGlyph.textBlackNoteFrac16thLongStem;

  static const textBlackNoteFrac32ndLongStem =
      SmuflGlyph.textBlackNoteFrac32ndLongStem;

  static const textCont8thBeamShortStem = SmuflGlyph.textCont8thBeamShortStem;

  static const textCont8thBeamLongStem = SmuflGlyph.textCont8thBeamLongStem;

  static const textCont16thBeamShortStem = SmuflGlyph.textCont16thBeamShortStem;

  static const textCont16thBeamLongStem = SmuflGlyph.textCont16thBeamLongStem;

  static const textCont32ndBeamLongStem = SmuflGlyph.textCont32ndBeamLongStem;

  static const textAugmentationDot = SmuflGlyph.textAugmentationDot;

  static const textTie = SmuflGlyph.textTie;

  static const textTupletBracketStartShortStem =
      SmuflGlyph.textTupletBracketStartShortStem;

  static const textTuplet3ShortStem = SmuflGlyph.textTuplet3ShortStem;

  static const textTupletBracketEndShortStem =
      SmuflGlyph.textTupletBracketEndShortStem;

  static const textTupletBracketStartLongStem =
      SmuflGlyph.textTupletBracketStartLongStem;

  static const textTuplet3LongStem = SmuflGlyph.textTuplet3LongStem;

  static const textTupletBracketEndLongStem =
      SmuflGlyph.textTupletBracketEndLongStem;

  static const stem = SmuflGlyph.stem;

  static const stemSprechgesang = SmuflGlyph.stemSprechgesang;

  static const stemSwished = SmuflGlyph.stemSwished;

  static const stemPendereckiTremolo = SmuflGlyph.stemPendereckiTremolo;

  static const stemSulPonticello = SmuflGlyph.stemSulPonticello;

  static const stemBowOnBridge = SmuflGlyph.stemBowOnBridge;

  static const stemBowOnTailpiece = SmuflGlyph.stemBowOnTailpiece;

  static const stemBuzzRoll = SmuflGlyph.stemBuzzRoll;

  static const stemDamp = SmuflGlyph.stemDamp;

  static const stemVibratoPulse = SmuflGlyph.stemVibratoPulse;

  static const stemMultiphonicsBlack = SmuflGlyph.stemMultiphonicsBlack;

  static const stemMultiphonicsWhite = SmuflGlyph.stemMultiphonicsWhite;

  static const stemMultiphonicsBlackWhite =
      SmuflGlyph.stemMultiphonicsBlackWhite;

  static const stemSussurando = SmuflGlyph.stemSussurando;

  static const stemRimShot = SmuflGlyph.stemRimShot;

  static const stemHarpStringNoise = SmuflGlyph.stemHarpStringNoise;

  static const restHBarMiddle = SmuflGlyph.restHBarMiddle;

  static const chantStaff = SmuflGlyph.chantStaff;

  static const chantStaffWide = SmuflGlyph.chantStaffWide;

  static const chantStaffNarrow = SmuflGlyph.chantStaffNarrow;

  static const chantDivisioMinima = SmuflGlyph.chantDivisioMinima;

  static const chantDivisioMaior = SmuflGlyph.chantDivisioMaior;

  static const chantDivisioMaxima = SmuflGlyph.chantDivisioMaxima;

  static const chantDivisioFinalis = SmuflGlyph.chantDivisioFinalis;

  static const chantVirgula = SmuflGlyph.chantVirgula;

  static const chantCaesura = SmuflGlyph.chantCaesura;

  static const staffPosRaise1 = SmuflGlyph.staffPosRaise1;

  static const staffPosRaise2 = SmuflGlyph.staffPosRaise2;

  static const staffPosRaise3 = SmuflGlyph.staffPosRaise3;

  static const staffPosRaise4 = SmuflGlyph.staffPosRaise4;

  static const staffPosRaise5 = SmuflGlyph.staffPosRaise5;

  static const staffPosRaise6 = SmuflGlyph.staffPosRaise6;

  static const staffPosRaise7 = SmuflGlyph.staffPosRaise7;

  static const staffPosRaise8 = SmuflGlyph.staffPosRaise8;

  static const staffPosLower1 = SmuflGlyph.staffPosLower1;

  static const staffPosLower2 = SmuflGlyph.staffPosLower2;

  static const staffPosLower3 = SmuflGlyph.staffPosLower3;

  static const staffPosLower4 = SmuflGlyph.staffPosLower4;

  static const staffPosLower5 = SmuflGlyph.staffPosLower5;

  static const staffPosLower6 = SmuflGlyph.staffPosLower6;

  static const staffPosLower7 = SmuflGlyph.staffPosLower7;

  static const staffPosLower8 = SmuflGlyph.staffPosLower8;

  static const luteStaff6Lines = SmuflGlyph.luteStaff6Lines;

  static const luteStaff6LinesWide = SmuflGlyph.luteStaff6LinesWide;

  static const luteStaff6LinesNarrow = SmuflGlyph.luteStaff6LinesNarrow;

  static const luteBarlineStartRepeat = SmuflGlyph.luteBarlineStartRepeat;

  static const luteBarlineEndRepeat = SmuflGlyph.luteBarlineEndRepeat;

  static const luteBarlineFinal = SmuflGlyph.luteBarlineFinal;

  static const metricModulationArrowLeft = SmuflGlyph.metricModulationArrowLeft;

  static const metricModulationArrowRight =
      SmuflGlyph.metricModulationArrowRight;
}
