// Generated by tool.

part of "../glyph_class.dart";

class MultiGlyphForms extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.ornamentTopLeftConcaveStroke,
        SmuflGlyph.ornamentTopLeftConvexStroke,
        SmuflGlyph.ornamentHighLeftConcaveStroke,
        SmuflGlyph.ornamentHighLeftConvexStroke,
        SmuflGlyph.ornamentLeftVerticalStroke,
        SmuflGlyph.ornamentLeftVerticalStrokeWithCross,
        SmuflGlyph.ornamentLeftShakeT,
        SmuflGlyph.ornamentLeftPlus,
        SmuflGlyph.ornamentLowLeftConcaveStroke,
        SmuflGlyph.ornamentLowLeftConvexStroke,
        SmuflGlyph.ornamentBottomLeftConcaveStroke,
        SmuflGlyph.ornamentBottomLeftConcaveStrokeLarge,
        SmuflGlyph.ornamentBottomLeftConvexStroke,
        SmuflGlyph.ornamentZigZagLineNoRightEnd,
        SmuflGlyph.ornamentZigZagLineWithRightEnd,
        SmuflGlyph.ornamentMiddleVerticalStroke,
        SmuflGlyph.ornamentTopRightConcaveStroke,
        SmuflGlyph.ornamentTopRightConvexStroke,
        SmuflGlyph.ornamentHighRightConcaveStroke,
        SmuflGlyph.ornamentHighRightConvexStroke,
        SmuflGlyph.ornamentRightVerticalStroke,
        SmuflGlyph.ornamentLowRightConcaveStroke,
        SmuflGlyph.ornamentLowRightConvexStroke,
        SmuflGlyph.ornamentBottomRightConcaveStroke,
        SmuflGlyph.ornamentBottomRightConvexStroke,
        SmuflGlyph.wiggleTrillFastest,
        SmuflGlyph.wiggleTrillFasterStill,
        SmuflGlyph.wiggleTrillFaster,
        SmuflGlyph.wiggleTrillFast,
        SmuflGlyph.wiggleTrill,
        SmuflGlyph.wiggleTrillSlow,
        SmuflGlyph.wiggleTrillSlower,
        SmuflGlyph.wiggleTrillSlowerStill,
        SmuflGlyph.wiggleTrillSlowest,
        SmuflGlyph.wiggleArpeggiatoUp,
        SmuflGlyph.wiggleArpeggiatoDown,
        SmuflGlyph.wiggleArpeggiatoUpSwash,
        SmuflGlyph.wiggleArpeggiatoDownSwash,
        SmuflGlyph.wiggleArpeggiatoUpArrow,
        SmuflGlyph.wiggleArpeggiatoDownArrow,
        SmuflGlyph.wiggleGlissando,
        SmuflGlyph.wiggleVibrato,
        SmuflGlyph.wiggleVibratoWide,
        SmuflGlyph.guitarVibratoStroke,
        SmuflGlyph.guitarWideVibratoStroke,
        SmuflGlyph.wiggleWavy,
        SmuflGlyph.wiggleSquareWave,
        SmuflGlyph.wiggleSawtooth,
        SmuflGlyph.wiggleGlissandoGroup1,
        SmuflGlyph.wiggleGlissandoGroup2,
        SmuflGlyph.wiggleGlissandoGroup3,
        SmuflGlyph.wiggleCircularConstant,
        SmuflGlyph.wiggleCircularConstantFlipped,
        SmuflGlyph.wiggleCircularConstantLarge,
        SmuflGlyph.wiggleCircularConstantFlippedLarge,
        SmuflGlyph.wiggleCircularStart,
        SmuflGlyph.wiggleCircularLargest,
        SmuflGlyph.wiggleCircularLargerStill,
        SmuflGlyph.wiggleCircularLarger,
        SmuflGlyph.wiggleCircularLarge,
        SmuflGlyph.wiggleCircular,
        SmuflGlyph.wiggleCircularSmall,
        SmuflGlyph.wiggleCircularEnd,
        SmuflGlyph.wiggleVibratoStart,
        SmuflGlyph.wiggleVibratoSmallestFastest,
        SmuflGlyph.wiggleVibratoSmallestFasterStill,
        SmuflGlyph.wiggleVibratoSmallestFaster,
        SmuflGlyph.wiggleVibratoSmallestFast,
        SmuflGlyph.wiggleVibratoSmallestSlow,
        SmuflGlyph.wiggleVibratoSmallestSlower,
        SmuflGlyph.wiggleVibratoSmallestSlowest,
        SmuflGlyph.wiggleVibratoSmallFastest,
        SmuflGlyph.wiggleVibratoSmallFasterStill,
        SmuflGlyph.wiggleVibratoSmallFaster,
        SmuflGlyph.wiggleVibratoSmallFast,
        SmuflGlyph.wiggleVibratoSmallSlow,
        SmuflGlyph.wiggleVibratoSmallSlower,
        SmuflGlyph.wiggleVibratoSmallSlowest,
        SmuflGlyph.wiggleVibratoMediumFastest,
        SmuflGlyph.wiggleVibratoMediumFasterStill,
        SmuflGlyph.wiggleVibratoMediumFaster,
        SmuflGlyph.wiggleVibratoMediumFast,
        SmuflGlyph.wiggleVibratoMediumSlow,
        SmuflGlyph.wiggleVIbratoMediumSlower,
        SmuflGlyph.wiggleVibratoMediumSlowest,
        SmuflGlyph.wiggleVibratoLargeFastest,
        SmuflGlyph.wiggleVibratoLargeFasterStill,
        SmuflGlyph.wiggleVibratoLargeFaster,
        SmuflGlyph.wiggleVibratoLargeFast,
        SmuflGlyph.wiggleVibratoLargeSlow,
        SmuflGlyph.wiggleVibratoLargeSlower,
        SmuflGlyph.wiggleVibratoLargeSlowest,
        SmuflGlyph.wiggleVibratoLargestFastest,
        SmuflGlyph.wiggleVibratoLargestFasterStill,
        SmuflGlyph.wiggleVibratoLargestFaster,
        SmuflGlyph.wiggleVibratoLargestFast,
        SmuflGlyph.wiggleVibratoLargestSlow,
        SmuflGlyph.wiggleVIbratoLargestSlower,
        SmuflGlyph.wiggleVibratoLargestSlowest,
        SmuflGlyph.wiggleRandom1,
        SmuflGlyph.wiggleRandom2,
        SmuflGlyph.wiggleRandom3,
        SmuflGlyph.wiggleRandom4,
      ];

  static const ornamentTopLeftConcaveStroke =
      SmuflGlyph.ornamentTopLeftConcaveStroke;

  static const ornamentTopLeftConvexStroke =
      SmuflGlyph.ornamentTopLeftConvexStroke;

  static const ornamentHighLeftConcaveStroke =
      SmuflGlyph.ornamentHighLeftConcaveStroke;

  static const ornamentHighLeftConvexStroke =
      SmuflGlyph.ornamentHighLeftConvexStroke;

  static const ornamentLeftVerticalStroke =
      SmuflGlyph.ornamentLeftVerticalStroke;

  static const ornamentLeftVerticalStrokeWithCross =
      SmuflGlyph.ornamentLeftVerticalStrokeWithCross;

  static const ornamentLeftShakeT = SmuflGlyph.ornamentLeftShakeT;

  static const ornamentLeftPlus = SmuflGlyph.ornamentLeftPlus;

  static const ornamentLowLeftConcaveStroke =
      SmuflGlyph.ornamentLowLeftConcaveStroke;

  static const ornamentLowLeftConvexStroke =
      SmuflGlyph.ornamentLowLeftConvexStroke;

  static const ornamentBottomLeftConcaveStroke =
      SmuflGlyph.ornamentBottomLeftConcaveStroke;

  static const ornamentBottomLeftConcaveStrokeLarge =
      SmuflGlyph.ornamentBottomLeftConcaveStrokeLarge;

  static const ornamentBottomLeftConvexStroke =
      SmuflGlyph.ornamentBottomLeftConvexStroke;

  static const ornamentZigZagLineNoRightEnd =
      SmuflGlyph.ornamentZigZagLineNoRightEnd;

  static const ornamentZigZagLineWithRightEnd =
      SmuflGlyph.ornamentZigZagLineWithRightEnd;

  static const ornamentMiddleVerticalStroke =
      SmuflGlyph.ornamentMiddleVerticalStroke;

  static const ornamentTopRightConcaveStroke =
      SmuflGlyph.ornamentTopRightConcaveStroke;

  static const ornamentTopRightConvexStroke =
      SmuflGlyph.ornamentTopRightConvexStroke;

  static const ornamentHighRightConcaveStroke =
      SmuflGlyph.ornamentHighRightConcaveStroke;

  static const ornamentHighRightConvexStroke =
      SmuflGlyph.ornamentHighRightConvexStroke;

  static const ornamentRightVerticalStroke =
      SmuflGlyph.ornamentRightVerticalStroke;

  static const ornamentLowRightConcaveStroke =
      SmuflGlyph.ornamentLowRightConcaveStroke;

  static const ornamentLowRightConvexStroke =
      SmuflGlyph.ornamentLowRightConvexStroke;

  static const ornamentBottomRightConcaveStroke =
      SmuflGlyph.ornamentBottomRightConcaveStroke;

  static const ornamentBottomRightConvexStroke =
      SmuflGlyph.ornamentBottomRightConvexStroke;

  static const wiggleTrillFastest = SmuflGlyph.wiggleTrillFastest;

  static const wiggleTrillFasterStill = SmuflGlyph.wiggleTrillFasterStill;

  static const wiggleTrillFaster = SmuflGlyph.wiggleTrillFaster;

  static const wiggleTrillFast = SmuflGlyph.wiggleTrillFast;

  static const wiggleTrill = SmuflGlyph.wiggleTrill;

  static const wiggleTrillSlow = SmuflGlyph.wiggleTrillSlow;

  static const wiggleTrillSlower = SmuflGlyph.wiggleTrillSlower;

  static const wiggleTrillSlowerStill = SmuflGlyph.wiggleTrillSlowerStill;

  static const wiggleTrillSlowest = SmuflGlyph.wiggleTrillSlowest;

  static const wiggleArpeggiatoUp = SmuflGlyph.wiggleArpeggiatoUp;

  static const wiggleArpeggiatoDown = SmuflGlyph.wiggleArpeggiatoDown;

  static const wiggleArpeggiatoUpSwash = SmuflGlyph.wiggleArpeggiatoUpSwash;

  static const wiggleArpeggiatoDownSwash = SmuflGlyph.wiggleArpeggiatoDownSwash;

  static const wiggleArpeggiatoUpArrow = SmuflGlyph.wiggleArpeggiatoUpArrow;

  static const wiggleArpeggiatoDownArrow = SmuflGlyph.wiggleArpeggiatoDownArrow;

  static const wiggleGlissando = SmuflGlyph.wiggleGlissando;

  static const wiggleVibrato = SmuflGlyph.wiggleVibrato;

  static const wiggleVibratoWide = SmuflGlyph.wiggleVibratoWide;

  static const guitarVibratoStroke = SmuflGlyph.guitarVibratoStroke;

  static const guitarWideVibratoStroke = SmuflGlyph.guitarWideVibratoStroke;

  static const wiggleWavy = SmuflGlyph.wiggleWavy;

  static const wiggleSquareWave = SmuflGlyph.wiggleSquareWave;

  static const wiggleSawtooth = SmuflGlyph.wiggleSawtooth;

  static const wiggleGlissandoGroup1 = SmuflGlyph.wiggleGlissandoGroup1;

  static const wiggleGlissandoGroup2 = SmuflGlyph.wiggleGlissandoGroup2;

  static const wiggleGlissandoGroup3 = SmuflGlyph.wiggleGlissandoGroup3;

  static const wiggleCircularConstant = SmuflGlyph.wiggleCircularConstant;

  static const wiggleCircularConstantFlipped =
      SmuflGlyph.wiggleCircularConstantFlipped;

  static const wiggleCircularConstantLarge =
      SmuflGlyph.wiggleCircularConstantLarge;

  static const wiggleCircularConstantFlippedLarge =
      SmuflGlyph.wiggleCircularConstantFlippedLarge;

  static const wiggleCircularStart = SmuflGlyph.wiggleCircularStart;

  static const wiggleCircularLargest = SmuflGlyph.wiggleCircularLargest;

  static const wiggleCircularLargerStill = SmuflGlyph.wiggleCircularLargerStill;

  static const wiggleCircularLarger = SmuflGlyph.wiggleCircularLarger;

  static const wiggleCircularLarge = SmuflGlyph.wiggleCircularLarge;

  static const wiggleCircular = SmuflGlyph.wiggleCircular;

  static const wiggleCircularSmall = SmuflGlyph.wiggleCircularSmall;

  static const wiggleCircularEnd = SmuflGlyph.wiggleCircularEnd;

  static const wiggleVibratoStart = SmuflGlyph.wiggleVibratoStart;

  static const wiggleVibratoSmallestFastest =
      SmuflGlyph.wiggleVibratoSmallestFastest;

  static const wiggleVibratoSmallestFasterStill =
      SmuflGlyph.wiggleVibratoSmallestFasterStill;

  static const wiggleVibratoSmallestFaster =
      SmuflGlyph.wiggleVibratoSmallestFaster;

  static const wiggleVibratoSmallestFast = SmuflGlyph.wiggleVibratoSmallestFast;

  static const wiggleVibratoSmallestSlow = SmuflGlyph.wiggleVibratoSmallestSlow;

  static const wiggleVibratoSmallestSlower =
      SmuflGlyph.wiggleVibratoSmallestSlower;

  static const wiggleVibratoSmallestSlowest =
      SmuflGlyph.wiggleVibratoSmallestSlowest;

  static const wiggleVibratoSmallFastest = SmuflGlyph.wiggleVibratoSmallFastest;

  static const wiggleVibratoSmallFasterStill =
      SmuflGlyph.wiggleVibratoSmallFasterStill;

  static const wiggleVibratoSmallFaster = SmuflGlyph.wiggleVibratoSmallFaster;

  static const wiggleVibratoSmallFast = SmuflGlyph.wiggleVibratoSmallFast;

  static const wiggleVibratoSmallSlow = SmuflGlyph.wiggleVibratoSmallSlow;

  static const wiggleVibratoSmallSlower = SmuflGlyph.wiggleVibratoSmallSlower;

  static const wiggleVibratoSmallSlowest = SmuflGlyph.wiggleVibratoSmallSlowest;

  static const wiggleVibratoMediumFastest =
      SmuflGlyph.wiggleVibratoMediumFastest;

  static const wiggleVibratoMediumFasterStill =
      SmuflGlyph.wiggleVibratoMediumFasterStill;

  static const wiggleVibratoMediumFaster = SmuflGlyph.wiggleVibratoMediumFaster;

  static const wiggleVibratoMediumFast = SmuflGlyph.wiggleVibratoMediumFast;

  static const wiggleVibratoMediumSlow = SmuflGlyph.wiggleVibratoMediumSlow;

  static const wiggleVIbratoMediumSlower = SmuflGlyph.wiggleVIbratoMediumSlower;

  static const wiggleVibratoMediumSlowest =
      SmuflGlyph.wiggleVibratoMediumSlowest;

  static const wiggleVibratoLargeFastest = SmuflGlyph.wiggleVibratoLargeFastest;

  static const wiggleVibratoLargeFasterStill =
      SmuflGlyph.wiggleVibratoLargeFasterStill;

  static const wiggleVibratoLargeFaster = SmuflGlyph.wiggleVibratoLargeFaster;

  static const wiggleVibratoLargeFast = SmuflGlyph.wiggleVibratoLargeFast;

  static const wiggleVibratoLargeSlow = SmuflGlyph.wiggleVibratoLargeSlow;

  static const wiggleVibratoLargeSlower = SmuflGlyph.wiggleVibratoLargeSlower;

  static const wiggleVibratoLargeSlowest = SmuflGlyph.wiggleVibratoLargeSlowest;

  static const wiggleVibratoLargestFastest =
      SmuflGlyph.wiggleVibratoLargestFastest;

  static const wiggleVibratoLargestFasterStill =
      SmuflGlyph.wiggleVibratoLargestFasterStill;

  static const wiggleVibratoLargestFaster =
      SmuflGlyph.wiggleVibratoLargestFaster;

  static const wiggleVibratoLargestFast = SmuflGlyph.wiggleVibratoLargestFast;

  static const wiggleVibratoLargestSlow = SmuflGlyph.wiggleVibratoLargestSlow;

  static const wiggleVIbratoLargestSlower =
      SmuflGlyph.wiggleVIbratoLargestSlower;

  static const wiggleVibratoLargestSlowest =
      SmuflGlyph.wiggleVibratoLargestSlowest;

  static const wiggleRandom1 = SmuflGlyph.wiggleRandom1;

  static const wiggleRandom2 = SmuflGlyph.wiggleRandom2;

  static const wiggleRandom3 = SmuflGlyph.wiggleRandom3;

  static const wiggleRandom4 = SmuflGlyph.wiggleRandom4;
}
