// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetRoundLarge extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadRoundBlackLarge,
        SmuflGlyph.noteheadRoundWhiteLarge,
        SmuflGlyph.noteheadRoundWhiteWithDotLarge,
        SmuflGlyph.noteheadRoundBlackSlashedLarge,
        SmuflGlyph.noteheadRoundWhiteSlashedLarge,
      ];

  static const noteheadRoundBlackLarge = SmuflGlyph.noteheadRoundBlackLarge;

  static const noteheadRoundWhiteLarge = SmuflGlyph.noteheadRoundWhiteLarge;

  static const noteheadRoundWhiteWithDotLarge =
      SmuflGlyph.noteheadRoundWhiteWithDotLarge;

  static const noteheadRoundBlackSlashedLarge =
      SmuflGlyph.noteheadRoundBlackSlashedLarge;

  static const noteheadRoundWhiteSlashedLarge =
      SmuflGlyph.noteheadRoundWhiteSlashedLarge;
}
