// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetHeavyX extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadHeavyX,
        SmuflGlyph.noteheadHeavyXHat,
      ];

  static const noteheadHeavyX = SmuflGlyph.noteheadHeavyX;

  static const noteheadHeavyXHat = SmuflGlyph.noteheadHeavyXHat;
}
