// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetSlashed2 extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadSlashedBlack2,
        SmuflGlyph.noteheadSlashedHalf2,
        SmuflGlyph.noteheadSlashedWhole2,
        SmuflGlyph.noteheadSlashedDoubleWhole2,
      ];

  static const noteheadSlashedBlack2 = SmuflGlyph.noteheadSlashedBlack2;

  static const noteheadSlashedHalf2 = SmuflGlyph.noteheadSlashedHalf2;

  static const noteheadSlashedWhole2 = SmuflGlyph.noteheadSlashedWhole2;

  static const noteheadSlashedDoubleWhole2 =
      SmuflGlyph.noteheadSlashedDoubleWhole2;
}
