// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetNamesPitch extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteAFlatWhole,
        SmuflGlyph.noteAWhole,
        SmuflGlyph.noteASharpWhole,
        SmuflGlyph.noteBFlatWhole,
        SmuflGlyph.noteBWhole,
        SmuflGlyph.noteBSharpWhole,
        SmuflGlyph.noteCFlatWhole,
        SmuflGlyph.noteCWhole,
        SmuflGlyph.noteCSharpWhole,
        SmuflGlyph.noteDFlatWhole,
        SmuflGlyph.noteDWhole,
        SmuflGlyph.noteDSharpWhole,
        SmuflGlyph.noteEFlatWhole,
        SmuflGlyph.noteEWhole,
        SmuflGlyph.noteESharpWhole,
        SmuflGlyph.noteFFlatWhole,
        SmuflGlyph.noteFWhole,
        SmuflGlyph.noteFSharpWhole,
        SmuflGlyph.noteGFlatWhole,
        SmuflGlyph.noteGWhole,
        SmuflGlyph.noteGSharpWhole,
        SmuflGlyph.noteHWhole,
        SmuflGlyph.noteHSharpWhole,
        SmuflGlyph.noteAFlatHalf,
        SmuflGlyph.noteAHalf,
        SmuflGlyph.noteASharpHalf,
        SmuflGlyph.noteBFlatHalf,
        SmuflGlyph.noteBHalf,
        SmuflGlyph.noteBSharpHalf,
        SmuflGlyph.noteCFlatHalf,
        SmuflGlyph.noteCHalf,
        SmuflGlyph.noteCSharpHalf,
        SmuflGlyph.noteDFlatHalf,
        SmuflGlyph.noteDHalf,
        SmuflGlyph.noteDSharpHalf,
        SmuflGlyph.noteEFlatHalf,
        SmuflGlyph.noteEHalf,
        SmuflGlyph.noteESharpHalf,
        SmuflGlyph.noteFFlatHalf,
        SmuflGlyph.noteFHalf,
        SmuflGlyph.noteFSharpHalf,
        SmuflGlyph.noteGFlatHalf,
        SmuflGlyph.noteGHalf,
        SmuflGlyph.noteGSharpHalf,
        SmuflGlyph.noteHHalf,
        SmuflGlyph.noteHSharpHalf,
        SmuflGlyph.noteAFlatBlack,
        SmuflGlyph.noteABlack,
        SmuflGlyph.noteASharpBlack,
        SmuflGlyph.noteBFlatBlack,
        SmuflGlyph.noteBBlack,
        SmuflGlyph.noteBSharpBlack,
        SmuflGlyph.noteCFlatBlack,
        SmuflGlyph.noteCBlack,
        SmuflGlyph.noteCSharpBlack,
        SmuflGlyph.noteDFlatBlack,
        SmuflGlyph.noteDBlack,
        SmuflGlyph.noteDSharpBlack,
        SmuflGlyph.noteEFlatBlack,
        SmuflGlyph.noteEBlack,
        SmuflGlyph.noteESharpBlack,
        SmuflGlyph.noteFFlatBlack,
        SmuflGlyph.noteFBlack,
        SmuflGlyph.noteFSharpBlack,
        SmuflGlyph.noteGFlatBlack,
        SmuflGlyph.noteGBlack,
        SmuflGlyph.noteGSharpBlack,
        SmuflGlyph.noteHBlack,
        SmuflGlyph.noteHSharpBlack,
      ];

  static const noteAFlatWhole = SmuflGlyph.noteAFlatWhole;

  static const noteAWhole = SmuflGlyph.noteAWhole;

  static const noteASharpWhole = SmuflGlyph.noteASharpWhole;

  static const noteBFlatWhole = SmuflGlyph.noteBFlatWhole;

  static const noteBWhole = SmuflGlyph.noteBWhole;

  static const noteBSharpWhole = SmuflGlyph.noteBSharpWhole;

  static const noteCFlatWhole = SmuflGlyph.noteCFlatWhole;

  static const noteCWhole = SmuflGlyph.noteCWhole;

  static const noteCSharpWhole = SmuflGlyph.noteCSharpWhole;

  static const noteDFlatWhole = SmuflGlyph.noteDFlatWhole;

  static const noteDWhole = SmuflGlyph.noteDWhole;

  static const noteDSharpWhole = SmuflGlyph.noteDSharpWhole;

  static const noteEFlatWhole = SmuflGlyph.noteEFlatWhole;

  static const noteEWhole = SmuflGlyph.noteEWhole;

  static const noteESharpWhole = SmuflGlyph.noteESharpWhole;

  static const noteFFlatWhole = SmuflGlyph.noteFFlatWhole;

  static const noteFWhole = SmuflGlyph.noteFWhole;

  static const noteFSharpWhole = SmuflGlyph.noteFSharpWhole;

  static const noteGFlatWhole = SmuflGlyph.noteGFlatWhole;

  static const noteGWhole = SmuflGlyph.noteGWhole;

  static const noteGSharpWhole = SmuflGlyph.noteGSharpWhole;

  static const noteHWhole = SmuflGlyph.noteHWhole;

  static const noteHSharpWhole = SmuflGlyph.noteHSharpWhole;

  static const noteAFlatHalf = SmuflGlyph.noteAFlatHalf;

  static const noteAHalf = SmuflGlyph.noteAHalf;

  static const noteASharpHalf = SmuflGlyph.noteASharpHalf;

  static const noteBFlatHalf = SmuflGlyph.noteBFlatHalf;

  static const noteBHalf = SmuflGlyph.noteBHalf;

  static const noteBSharpHalf = SmuflGlyph.noteBSharpHalf;

  static const noteCFlatHalf = SmuflGlyph.noteCFlatHalf;

  static const noteCHalf = SmuflGlyph.noteCHalf;

  static const noteCSharpHalf = SmuflGlyph.noteCSharpHalf;

  static const noteDFlatHalf = SmuflGlyph.noteDFlatHalf;

  static const noteDHalf = SmuflGlyph.noteDHalf;

  static const noteDSharpHalf = SmuflGlyph.noteDSharpHalf;

  static const noteEFlatHalf = SmuflGlyph.noteEFlatHalf;

  static const noteEHalf = SmuflGlyph.noteEHalf;

  static const noteESharpHalf = SmuflGlyph.noteESharpHalf;

  static const noteFFlatHalf = SmuflGlyph.noteFFlatHalf;

  static const noteFHalf = SmuflGlyph.noteFHalf;

  static const noteFSharpHalf = SmuflGlyph.noteFSharpHalf;

  static const noteGFlatHalf = SmuflGlyph.noteGFlatHalf;

  static const noteGHalf = SmuflGlyph.noteGHalf;

  static const noteGSharpHalf = SmuflGlyph.noteGSharpHalf;

  static const noteHHalf = SmuflGlyph.noteHHalf;

  static const noteHSharpHalf = SmuflGlyph.noteHSharpHalf;

  static const noteAFlatBlack = SmuflGlyph.noteAFlatBlack;

  static const noteABlack = SmuflGlyph.noteABlack;

  static const noteASharpBlack = SmuflGlyph.noteASharpBlack;

  static const noteBFlatBlack = SmuflGlyph.noteBFlatBlack;

  static const noteBBlack = SmuflGlyph.noteBBlack;

  static const noteBSharpBlack = SmuflGlyph.noteBSharpBlack;

  static const noteCFlatBlack = SmuflGlyph.noteCFlatBlack;

  static const noteCBlack = SmuflGlyph.noteCBlack;

  static const noteCSharpBlack = SmuflGlyph.noteCSharpBlack;

  static const noteDFlatBlack = SmuflGlyph.noteDFlatBlack;

  static const noteDBlack = SmuflGlyph.noteDBlack;

  static const noteDSharpBlack = SmuflGlyph.noteDSharpBlack;

  static const noteEFlatBlack = SmuflGlyph.noteEFlatBlack;

  static const noteEBlack = SmuflGlyph.noteEBlack;

  static const noteESharpBlack = SmuflGlyph.noteESharpBlack;

  static const noteFFlatBlack = SmuflGlyph.noteFFlatBlack;

  static const noteFBlack = SmuflGlyph.noteFBlack;

  static const noteFSharpBlack = SmuflGlyph.noteFSharpBlack;

  static const noteGFlatBlack = SmuflGlyph.noteGFlatBlack;

  static const noteGBlack = SmuflGlyph.noteGBlack;

  static const noteGSharpBlack = SmuflGlyph.noteGSharpBlack;

  static const noteHBlack = SmuflGlyph.noteHBlack;

  static const noteHSharpBlack = SmuflGlyph.noteHSharpBlack;
}
