// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetDiamondOld extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadDiamondDoubleWholeOld,
        SmuflGlyph.noteheadDiamondWholeOld,
        SmuflGlyph.noteheadDiamondHalfOld,
        SmuflGlyph.noteheadDiamondBlackOld,
        SmuflGlyph.noteheadDiamondHalfFilled,
      ];

  static const noteheadDiamondDoubleWholeOld =
      SmuflGlyph.noteheadDiamondDoubleWholeOld;

  static const noteheadDiamondWholeOld = SmuflGlyph.noteheadDiamondWholeOld;

  static const noteheadDiamondHalfOld = SmuflGlyph.noteheadDiamondHalfOld;

  static const noteheadDiamondBlackOld = SmuflGlyph.noteheadDiamondBlackOld;

  static const noteheadDiamondHalfFilled = SmuflGlyph.noteheadDiamondHalfFilled;
}
