// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetLargeArrowUp extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadLargeArrowUpDoubleWhole,
        SmuflGlyph.noteheadLargeArrowUpWhole,
        SmuflGlyph.noteheadLargeArrowUpHalf,
        SmuflGlyph.noteheadLargeArrowUpBlack,
      ];

  static const noteheadLargeArrowUpDoubleWhole =
      SmuflGlyph.noteheadLargeArrowUpDoubleWhole;

  static const noteheadLargeArrowUpWhole = SmuflGlyph.noteheadLargeArrowUpWhole;

  static const noteheadLargeArrowUpHalf = SmuflGlyph.noteheadLargeArrowUpHalf;

  static const noteheadLargeArrowUpBlack = SmuflGlyph.noteheadLargeArrowUpBlack;
}
