// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetSacredHarp extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteShapeRoundWhite,
        SmuflGlyph.noteShapeRoundBlack,
        SmuflGlyph.noteShapeSquareWhite,
        SmuflGlyph.noteShapeSquareBlack,
        SmuflGlyph.noteShapeTriangleRightWhite,
        SmuflGlyph.noteShapeTriangleRightBlack,
        SmuflGlyph.noteShapeTriangleLeftWhite,
        SmuflGlyph.noteShapeTriangleLeftBlack,
        SmuflGlyph.noteShapeDiamondWhite,
        SmuflGlyph.noteShapeDiamondBlack,
        SmuflGlyph.noteShapeTriangleUpWhite,
        SmuflGlyph.noteShapeTriangleUpBlack,
        SmuflGlyph.noteShapeMoonWhite,
        SmuflGlyph.noteShapeMoonBlack,
        SmuflGlyph.noteShapeTriangleRoundWhite,
        SmuflGlyph.noteShapeTriangleRoundBlack,
        SmuflGlyph.noteShapeRoundDoubleWhole,
        SmuflGlyph.noteShapeSquareDoubleWhole,
        SmuflGlyph.noteShapeTriangleRightDoubleWhole,
        SmuflGlyph.noteShapeTriangleLeftDoubleWhole,
        SmuflGlyph.noteShapeDiamondDoubleWhole,
        SmuflGlyph.noteShapeTriangleUpDoubleWhole,
        SmuflGlyph.noteShapeMoonDoubleWhole,
        SmuflGlyph.noteShapeTriangleRoundDoubleWhole,
        SmuflGlyph.noteShapeKeystoneDoubleWhole,
        SmuflGlyph.noteShapeQuarterMoonDoubleWhole,
        SmuflGlyph.noteShapeIsoscelesTriangleDoubleWhole,
        SmuflGlyph.noteShapeMoonLeftDoubleWhole,
        SmuflGlyph.noteShapeArrowheadLeftDoubleWhole,
        SmuflGlyph.noteShapeTriangleRoundLeftDoubleWhole,
      ];

  static const noteShapeRoundWhite = SmuflGlyph.noteShapeRoundWhite;

  static const noteShapeRoundBlack = SmuflGlyph.noteShapeRoundBlack;

  static const noteShapeSquareWhite = SmuflGlyph.noteShapeSquareWhite;

  static const noteShapeSquareBlack = SmuflGlyph.noteShapeSquareBlack;

  static const noteShapeTriangleRightWhite =
      SmuflGlyph.noteShapeTriangleRightWhite;

  static const noteShapeTriangleRightBlack =
      SmuflGlyph.noteShapeTriangleRightBlack;

  static const noteShapeTriangleLeftWhite =
      SmuflGlyph.noteShapeTriangleLeftWhite;

  static const noteShapeTriangleLeftBlack =
      SmuflGlyph.noteShapeTriangleLeftBlack;

  static const noteShapeDiamondWhite = SmuflGlyph.noteShapeDiamondWhite;

  static const noteShapeDiamondBlack = SmuflGlyph.noteShapeDiamondBlack;

  static const noteShapeTriangleUpWhite = SmuflGlyph.noteShapeTriangleUpWhite;

  static const noteShapeTriangleUpBlack = SmuflGlyph.noteShapeTriangleUpBlack;

  static const noteShapeMoonWhite = SmuflGlyph.noteShapeMoonWhite;

  static const noteShapeMoonBlack = SmuflGlyph.noteShapeMoonBlack;

  static const noteShapeTriangleRoundWhite =
      SmuflGlyph.noteShapeTriangleRoundWhite;

  static const noteShapeTriangleRoundBlack =
      SmuflGlyph.noteShapeTriangleRoundBlack;

  static const noteShapeRoundDoubleWhole = SmuflGlyph.noteShapeRoundDoubleWhole;

  static const noteShapeSquareDoubleWhole =
      SmuflGlyph.noteShapeSquareDoubleWhole;

  static const noteShapeTriangleRightDoubleWhole =
      SmuflGlyph.noteShapeTriangleRightDoubleWhole;

  static const noteShapeTriangleLeftDoubleWhole =
      SmuflGlyph.noteShapeTriangleLeftDoubleWhole;

  static const noteShapeDiamondDoubleWhole =
      SmuflGlyph.noteShapeDiamondDoubleWhole;

  static const noteShapeTriangleUpDoubleWhole =
      SmuflGlyph.noteShapeTriangleUpDoubleWhole;

  static const noteShapeMoonDoubleWhole = SmuflGlyph.noteShapeMoonDoubleWhole;

  static const noteShapeTriangleRoundDoubleWhole =
      SmuflGlyph.noteShapeTriangleRoundDoubleWhole;

  static const noteShapeKeystoneDoubleWhole =
      SmuflGlyph.noteShapeKeystoneDoubleWhole;

  static const noteShapeQuarterMoonDoubleWhole =
      SmuflGlyph.noteShapeQuarterMoonDoubleWhole;

  static const noteShapeIsoscelesTriangleDoubleWhole =
      SmuflGlyph.noteShapeIsoscelesTriangleDoubleWhole;

  static const noteShapeMoonLeftDoubleWhole =
      SmuflGlyph.noteShapeMoonLeftDoubleWhole;

  static const noteShapeArrowheadLeftDoubleWhole =
      SmuflGlyph.noteShapeArrowheadLeftDoubleWhole;

  static const noteShapeTriangleRoundLeftDoubleWhole =
      SmuflGlyph.noteShapeTriangleRoundLeftDoubleWhole;
}
