// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetTriangleLeft extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadTriangleLeftWhite,
        SmuflGlyph.noteheadTriangleLeftBlack,
      ];

  static const noteheadTriangleLeftWhite = SmuflGlyph.noteheadTriangleLeftWhite;

  static const noteheadTriangleLeftBlack = SmuflGlyph.noteheadTriangleLeftBlack;
}
