// Generated by tool.

part of "../glyph_class.dart";

class Noteheads extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadDoubleWhole,
        SmuflGlyph.noteheadDoubleWholeSquare,
        SmuflGlyph.noteheadWhole,
        SmuflGlyph.noteheadHalf,
        SmuflGlyph.noteheadBlack,
        SmuflGlyph.noteheadNull,
        SmuflGlyph.noteheadXDoubleWhole,
        SmuflGlyph.noteheadXWhole,
        SmuflGlyph.noteheadXHalf,
        SmuflGlyph.noteheadXBlack,
        SmuflGlyph.noteheadXOrnate,
        SmuflGlyph.noteheadXOrnateEllipse,
        SmuflGlyph.noteheadPlusDoubleWhole,
        SmuflGlyph.noteheadPlusWhole,
        SmuflGlyph.noteheadPlusHalf,
        SmuflGlyph.noteheadPlusBlack,
        SmuflGlyph.noteheadCircleXDoubleWhole,
        SmuflGlyph.noteheadCircleXWhole,
        SmuflGlyph.noteheadCircleXHalf,
        SmuflGlyph.noteheadCircleX,
        SmuflGlyph.noteheadDoubleWholeWithX,
        SmuflGlyph.noteheadWholeWithX,
        SmuflGlyph.noteheadHalfWithX,
        SmuflGlyph.noteheadVoidWithX,
        SmuflGlyph.noteheadSquareWhite,
        SmuflGlyph.noteheadSquareBlack,
        SmuflGlyph.noteheadTriangleUpDoubleWhole,
        SmuflGlyph.noteheadTriangleUpWhole,
        SmuflGlyph.noteheadTriangleUpHalf,
        SmuflGlyph.noteheadTriangleUpWhite,
        SmuflGlyph.noteheadTriangleUpBlack,
        SmuflGlyph.noteheadTriangleLeftWhite,
        SmuflGlyph.noteheadTriangleLeftBlack,
        SmuflGlyph.noteheadTriangleRightWhite,
        SmuflGlyph.noteheadTriangleRightBlack,
        SmuflGlyph.noteheadTriangleDownDoubleWhole,
        SmuflGlyph.noteheadTriangleDownWhole,
        SmuflGlyph.noteheadTriangleDownHalf,
        SmuflGlyph.noteheadTriangleDownWhite,
        SmuflGlyph.noteheadTriangleDownBlack,
        SmuflGlyph.noteheadTriangleUpRightWhite,
        SmuflGlyph.noteheadTriangleUpRightBlack,
        SmuflGlyph.noteheadMoonWhite,
        SmuflGlyph.noteheadMoonBlack,
        SmuflGlyph.noteheadTriangleRoundDownWhite,
        SmuflGlyph.noteheadTriangleRoundDownBlack,
        SmuflGlyph.noteheadParenthesis,
        SmuflGlyph.noteheadSlashedBlack1,
        SmuflGlyph.noteheadSlashedBlack2,
        SmuflGlyph.noteheadSlashedHalf1,
        SmuflGlyph.noteheadSlashedHalf2,
        SmuflGlyph.noteheadSlashedWhole1,
        SmuflGlyph.noteheadSlashedWhole2,
        SmuflGlyph.noteheadSlashedDoubleWhole1,
        SmuflGlyph.noteheadSlashedDoubleWhole2,
        SmuflGlyph.noteheadDiamondDoubleWhole,
        SmuflGlyph.noteheadDiamondWhole,
        SmuflGlyph.noteheadDiamondHalf,
        SmuflGlyph.noteheadDiamondBlack,
        SmuflGlyph.noteheadDiamondWhite,
        SmuflGlyph.noteheadDiamondWhiteWide,
        SmuflGlyph.noteheadDiamondDoubleWholeOld,
        SmuflGlyph.noteheadDiamondWholeOld,
        SmuflGlyph.noteheadDiamondHalfOld,
        SmuflGlyph.noteheadDiamondBlackOld,
        SmuflGlyph.noteheadDiamondHalfFilled,
        SmuflGlyph.noteheadCircledBlack,
        SmuflGlyph.noteheadCircledHalf,
        SmuflGlyph.noteheadCircledWhole,
        SmuflGlyph.noteheadCircledDoubleWhole,
        SmuflGlyph.noteheadCircledBlackLarge,
        SmuflGlyph.noteheadCircledHalfLarge,
        SmuflGlyph.noteheadCircledWholeLarge,
        SmuflGlyph.noteheadCircledDoubleWholeLarge,
        SmuflGlyph.noteheadCircledXLarge,
        SmuflGlyph.noteheadLargeArrowUpDoubleWhole,
        SmuflGlyph.noteheadLargeArrowUpWhole,
        SmuflGlyph.noteheadLargeArrowUpHalf,
        SmuflGlyph.noteheadLargeArrowUpBlack,
        SmuflGlyph.noteheadLargeArrowDownDoubleWhole,
        SmuflGlyph.noteheadLargeArrowDownWhole,
        SmuflGlyph.noteheadLargeArrowDownHalf,
        SmuflGlyph.noteheadLargeArrowDownBlack,
        SmuflGlyph.noteheadParenthesisLeft,
        SmuflGlyph.noteheadParenthesisRight,
        SmuflGlyph.noteheadCircleSlash,
        SmuflGlyph.noteheadHeavyX,
        SmuflGlyph.noteheadHeavyXHat,
        SmuflGlyph.noteheadWholeFilled,
        SmuflGlyph.noteheadHalfFilled,
        SmuflGlyph.noteheadDiamondOpen,
        SmuflGlyph.noteheadSlashVerticalEnds,
        SmuflGlyph.noteheadSlashHorizontalEnds,
        SmuflGlyph.noteheadSlashWhiteWhole,
        SmuflGlyph.noteheadSlashWhiteHalf,
        SmuflGlyph.noteheadSlashDiamondWhite,
        SmuflGlyph.noteheadSlashVerticalEndsSmall,
        SmuflGlyph.noteheadSlashX,
        SmuflGlyph.noteheadSlashVerticalEndsMuted,
        SmuflGlyph.noteheadSlashHorizontalEndsMuted,
        SmuflGlyph.noteheadSlashWhiteMuted,
        SmuflGlyph.noteheadSlashWhiteDoubleWhole,
        SmuflGlyph.noteheadRoundBlackLarge,
        SmuflGlyph.noteheadRoundWhiteLarge,
        SmuflGlyph.noteheadRoundWhiteWithDotLarge,
        SmuflGlyph.noteheadRoundBlack,
        SmuflGlyph.noteheadRoundWhite,
        SmuflGlyph.noteheadRoundWhiteWithDot,
        SmuflGlyph.noteheadRoundBlackSlashedLarge,
        SmuflGlyph.noteheadRoundWhiteSlashedLarge,
        SmuflGlyph.noteheadRoundBlackSlashed,
        SmuflGlyph.noteheadRoundWhiteSlashed,
        SmuflGlyph.noteheadSquareBlackLarge,
        SmuflGlyph.noteheadSquareBlackWhite,
        SmuflGlyph.noteheadRoundBlackDoubleSlashed,
        SmuflGlyph.noteheadRoundWhiteDoubleSlashed,
        SmuflGlyph.noteheadClusterSquareWhite,
        SmuflGlyph.noteheadClusterSquareBlack,
        SmuflGlyph.noteheadClusterRoundWhite,
        SmuflGlyph.noteheadClusterRoundBlack,
        SmuflGlyph.noteheadClusterDoubleWhole2nd,
        SmuflGlyph.noteheadClusterWhole2nd,
        SmuflGlyph.noteheadClusterHalf2nd,
        SmuflGlyph.noteheadClusterQuarter2nd,
        SmuflGlyph.noteheadClusterDoubleWhole3rd,
        SmuflGlyph.noteheadClusterWhole3rd,
        SmuflGlyph.noteheadClusterHalf3rd,
        SmuflGlyph.noteheadClusterQuarter3rd,
        SmuflGlyph.noteheadClusterDoubleWholeTop,
        SmuflGlyph.noteheadClusterDoubleWholeMiddle,
        SmuflGlyph.noteheadClusterDoubleWholeBottom,
        SmuflGlyph.noteheadClusterWholeTop,
        SmuflGlyph.noteheadClusterWholeMiddle,
        SmuflGlyph.noteheadClusterWholeBottom,
        SmuflGlyph.noteheadClusterHalfTop,
        SmuflGlyph.noteheadClusterHalfMiddle,
        SmuflGlyph.noteheadClusterHalfBottom,
        SmuflGlyph.noteheadClusterQuarterTop,
        SmuflGlyph.noteheadClusterQuarterMiddle,
        SmuflGlyph.noteheadClusterQuarterBottom,
        SmuflGlyph.noteheadDiamondClusterWhite2nd,
        SmuflGlyph.noteheadDiamondClusterBlack2nd,
        SmuflGlyph.noteheadDiamondClusterWhite3rd,
        SmuflGlyph.noteheadDiamondClusterBlack3rd,
        SmuflGlyph.noteheadDiamondClusterWhiteTop,
        SmuflGlyph.noteheadDiamondClusterWhiteMiddle,
        SmuflGlyph.noteheadDiamondClusterWhiteBottom,
        SmuflGlyph.noteheadDiamondClusterBlackTop,
        SmuflGlyph.noteheadDiamondClusterBlackMiddle,
        SmuflGlyph.noteheadDiamondClusterBlackBottom,
        SmuflGlyph.noteheadRectangularClusterBlackTop,
        SmuflGlyph.noteheadRectangularClusterBlackMiddle,
        SmuflGlyph.noteheadRectangularClusterBlackBottom,
        SmuflGlyph.noteheadRectangularClusterWhiteTop,
        SmuflGlyph.noteheadRectangularClusterWhiteMiddle,
        SmuflGlyph.noteheadRectangularClusterWhiteBottom,
        SmuflGlyph.noteDoWhole,
        SmuflGlyph.noteReWhole,
        SmuflGlyph.noteMiWhole,
        SmuflGlyph.noteFaWhole,
        SmuflGlyph.noteSoWhole,
        SmuflGlyph.noteLaWhole,
        SmuflGlyph.noteTiWhole,
        SmuflGlyph.noteSiWhole,
        SmuflGlyph.noteDoHalf,
        SmuflGlyph.noteReHalf,
        SmuflGlyph.noteMiHalf,
        SmuflGlyph.noteFaHalf,
        SmuflGlyph.noteSoHalf,
        SmuflGlyph.noteLaHalf,
        SmuflGlyph.noteTiHalf,
        SmuflGlyph.noteSiHalf,
        SmuflGlyph.noteDoBlack,
        SmuflGlyph.noteReBlack,
        SmuflGlyph.noteMiBlack,
        SmuflGlyph.noteFaBlack,
        SmuflGlyph.noteSoBlack,
        SmuflGlyph.noteLaBlack,
        SmuflGlyph.noteTiBlack,
        SmuflGlyph.noteSiBlack,
        SmuflGlyph.noteAFlatWhole,
        SmuflGlyph.noteAWhole,
        SmuflGlyph.noteASharpWhole,
        SmuflGlyph.noteBFlatWhole,
        SmuflGlyph.noteBWhole,
        SmuflGlyph.noteBSharpWhole,
        SmuflGlyph.noteCFlatWhole,
        SmuflGlyph.noteCWhole,
        SmuflGlyph.noteCSharpWhole,
        SmuflGlyph.noteDFlatWhole,
        SmuflGlyph.noteDWhole,
        SmuflGlyph.noteDSharpWhole,
        SmuflGlyph.noteEFlatWhole,
        SmuflGlyph.noteEWhole,
        SmuflGlyph.noteESharpWhole,
        SmuflGlyph.noteFFlatWhole,
        SmuflGlyph.noteFWhole,
        SmuflGlyph.noteFSharpWhole,
        SmuflGlyph.noteGFlatWhole,
        SmuflGlyph.noteGWhole,
        SmuflGlyph.noteGSharpWhole,
        SmuflGlyph.noteHWhole,
        SmuflGlyph.noteHSharpWhole,
        SmuflGlyph.noteAFlatHalf,
        SmuflGlyph.noteAHalf,
        SmuflGlyph.noteASharpHalf,
        SmuflGlyph.noteBFlatHalf,
        SmuflGlyph.noteBHalf,
        SmuflGlyph.noteBSharpHalf,
        SmuflGlyph.noteCFlatHalf,
        SmuflGlyph.noteCHalf,
        SmuflGlyph.noteCSharpHalf,
        SmuflGlyph.noteDFlatHalf,
        SmuflGlyph.noteDHalf,
        SmuflGlyph.noteDSharpHalf,
        SmuflGlyph.noteEFlatHalf,
        SmuflGlyph.noteEHalf,
        SmuflGlyph.noteESharpHalf,
        SmuflGlyph.noteFFlatHalf,
        SmuflGlyph.noteFHalf,
        SmuflGlyph.noteFSharpHalf,
        SmuflGlyph.noteGFlatHalf,
        SmuflGlyph.noteGHalf,
        SmuflGlyph.noteGSharpHalf,
        SmuflGlyph.noteHHalf,
        SmuflGlyph.noteHSharpHalf,
        SmuflGlyph.noteAFlatBlack,
        SmuflGlyph.noteABlack,
        SmuflGlyph.noteASharpBlack,
        SmuflGlyph.noteBFlatBlack,
        SmuflGlyph.noteBBlack,
        SmuflGlyph.noteBSharpBlack,
        SmuflGlyph.noteCFlatBlack,
        SmuflGlyph.noteCBlack,
        SmuflGlyph.noteCSharpBlack,
        SmuflGlyph.noteDFlatBlack,
        SmuflGlyph.noteDBlack,
        SmuflGlyph.noteDSharpBlack,
        SmuflGlyph.noteEFlatBlack,
        SmuflGlyph.noteEBlack,
        SmuflGlyph.noteESharpBlack,
        SmuflGlyph.noteFFlatBlack,
        SmuflGlyph.noteFBlack,
        SmuflGlyph.noteFSharpBlack,
        SmuflGlyph.noteGFlatBlack,
        SmuflGlyph.noteGBlack,
        SmuflGlyph.noteGSharpBlack,
        SmuflGlyph.noteHBlack,
        SmuflGlyph.noteHSharpBlack,
        SmuflGlyph.noteEmptyWhole,
        SmuflGlyph.noteEmptyHalf,
        SmuflGlyph.noteEmptyBlack,
        SmuflGlyph.noteShapeRoundDoubleWhole,
        SmuflGlyph.noteShapeSquareDoubleWhole,
        SmuflGlyph.noteShapeTriangleRightDoubleWhole,
        SmuflGlyph.noteShapeTriangleLeftDoubleWhole,
        SmuflGlyph.noteShapeDiamondDoubleWhole,
        SmuflGlyph.noteShapeTriangleUpDoubleWhole,
        SmuflGlyph.noteShapeMoonDoubleWhole,
        SmuflGlyph.noteShapeTriangleRoundDoubleWhole,
        SmuflGlyph.noteShapeKeystoneDoubleWhole,
        SmuflGlyph.noteShapeQuarterMoonDoubleWhole,
        SmuflGlyph.noteShapeIsoscelesTriangleDoubleWhole,
        SmuflGlyph.noteShapeMoonLeftDoubleWhole,
        SmuflGlyph.noteShapeArrowheadLeftDoubleWhole,
        SmuflGlyph.noteShapeTriangleRoundLeftDoubleWhole,
        SmuflGlyph.swissRudimentsNoteheadBlackFlam,
        SmuflGlyph.swissRudimentsNoteheadHalfFlam,
        SmuflGlyph.swissRudimentsNoteheadHalfDouble,
      ];

  static const noteheadDoubleWhole = SmuflGlyph.noteheadDoubleWhole;

  static const noteheadDoubleWholeSquare = SmuflGlyph.noteheadDoubleWholeSquare;

  static const noteheadWhole = SmuflGlyph.noteheadWhole;

  static const noteheadHalf = SmuflGlyph.noteheadHalf;

  static const noteheadBlack = SmuflGlyph.noteheadBlack;

  static const noteheadNull = SmuflGlyph.noteheadNull;

  static const noteheadXDoubleWhole = SmuflGlyph.noteheadXDoubleWhole;

  static const noteheadXWhole = SmuflGlyph.noteheadXWhole;

  static const noteheadXHalf = SmuflGlyph.noteheadXHalf;

  static const noteheadXBlack = SmuflGlyph.noteheadXBlack;

  static const noteheadXOrnate = SmuflGlyph.noteheadXOrnate;

  static const noteheadXOrnateEllipse = SmuflGlyph.noteheadXOrnateEllipse;

  static const noteheadPlusDoubleWhole = SmuflGlyph.noteheadPlusDoubleWhole;

  static const noteheadPlusWhole = SmuflGlyph.noteheadPlusWhole;

  static const noteheadPlusHalf = SmuflGlyph.noteheadPlusHalf;

  static const noteheadPlusBlack = SmuflGlyph.noteheadPlusBlack;

  static const noteheadCircleXDoubleWhole =
      SmuflGlyph.noteheadCircleXDoubleWhole;

  static const noteheadCircleXWhole = SmuflGlyph.noteheadCircleXWhole;

  static const noteheadCircleXHalf = SmuflGlyph.noteheadCircleXHalf;

  static const noteheadCircleX = SmuflGlyph.noteheadCircleX;

  static const noteheadDoubleWholeWithX = SmuflGlyph.noteheadDoubleWholeWithX;

  static const noteheadWholeWithX = SmuflGlyph.noteheadWholeWithX;

  static const noteheadHalfWithX = SmuflGlyph.noteheadHalfWithX;

  static const noteheadVoidWithX = SmuflGlyph.noteheadVoidWithX;

  static const noteheadSquareWhite = SmuflGlyph.noteheadSquareWhite;

  static const noteheadSquareBlack = SmuflGlyph.noteheadSquareBlack;

  static const noteheadTriangleUpDoubleWhole =
      SmuflGlyph.noteheadTriangleUpDoubleWhole;

  static const noteheadTriangleUpWhole = SmuflGlyph.noteheadTriangleUpWhole;

  static const noteheadTriangleUpHalf = SmuflGlyph.noteheadTriangleUpHalf;

  static const noteheadTriangleUpWhite = SmuflGlyph.noteheadTriangleUpWhite;

  static const noteheadTriangleUpBlack = SmuflGlyph.noteheadTriangleUpBlack;

  static const noteheadTriangleLeftWhite = SmuflGlyph.noteheadTriangleLeftWhite;

  static const noteheadTriangleLeftBlack = SmuflGlyph.noteheadTriangleLeftBlack;

  static const noteheadTriangleRightWhite =
      SmuflGlyph.noteheadTriangleRightWhite;

  static const noteheadTriangleRightBlack =
      SmuflGlyph.noteheadTriangleRightBlack;

  static const noteheadTriangleDownDoubleWhole =
      SmuflGlyph.noteheadTriangleDownDoubleWhole;

  static const noteheadTriangleDownWhole = SmuflGlyph.noteheadTriangleDownWhole;

  static const noteheadTriangleDownHalf = SmuflGlyph.noteheadTriangleDownHalf;

  static const noteheadTriangleDownWhite = SmuflGlyph.noteheadTriangleDownWhite;

  static const noteheadTriangleDownBlack = SmuflGlyph.noteheadTriangleDownBlack;

  static const noteheadTriangleUpRightWhite =
      SmuflGlyph.noteheadTriangleUpRightWhite;

  static const noteheadTriangleUpRightBlack =
      SmuflGlyph.noteheadTriangleUpRightBlack;

  static const noteheadMoonWhite = SmuflGlyph.noteheadMoonWhite;

  static const noteheadMoonBlack = SmuflGlyph.noteheadMoonBlack;

  static const noteheadTriangleRoundDownWhite =
      SmuflGlyph.noteheadTriangleRoundDownWhite;

  static const noteheadTriangleRoundDownBlack =
      SmuflGlyph.noteheadTriangleRoundDownBlack;

  static const noteheadParenthesis = SmuflGlyph.noteheadParenthesis;

  static const noteheadSlashedBlack1 = SmuflGlyph.noteheadSlashedBlack1;

  static const noteheadSlashedBlack2 = SmuflGlyph.noteheadSlashedBlack2;

  static const noteheadSlashedHalf1 = SmuflGlyph.noteheadSlashedHalf1;

  static const noteheadSlashedHalf2 = SmuflGlyph.noteheadSlashedHalf2;

  static const noteheadSlashedWhole1 = SmuflGlyph.noteheadSlashedWhole1;

  static const noteheadSlashedWhole2 = SmuflGlyph.noteheadSlashedWhole2;

  static const noteheadSlashedDoubleWhole1 =
      SmuflGlyph.noteheadSlashedDoubleWhole1;

  static const noteheadSlashedDoubleWhole2 =
      SmuflGlyph.noteheadSlashedDoubleWhole2;

  static const noteheadDiamondDoubleWhole =
      SmuflGlyph.noteheadDiamondDoubleWhole;

  static const noteheadDiamondWhole = SmuflGlyph.noteheadDiamondWhole;

  static const noteheadDiamondHalf = SmuflGlyph.noteheadDiamondHalf;

  static const noteheadDiamondBlack = SmuflGlyph.noteheadDiamondBlack;

  static const noteheadDiamondWhite = SmuflGlyph.noteheadDiamondWhite;

  static const noteheadDiamondWhiteWide = SmuflGlyph.noteheadDiamondWhiteWide;

  static const noteheadDiamondDoubleWholeOld =
      SmuflGlyph.noteheadDiamondDoubleWholeOld;

  static const noteheadDiamondWholeOld = SmuflGlyph.noteheadDiamondWholeOld;

  static const noteheadDiamondHalfOld = SmuflGlyph.noteheadDiamondHalfOld;

  static const noteheadDiamondBlackOld = SmuflGlyph.noteheadDiamondBlackOld;

  static const noteheadDiamondHalfFilled = SmuflGlyph.noteheadDiamondHalfFilled;

  static const noteheadCircledBlack = SmuflGlyph.noteheadCircledBlack;

  static const noteheadCircledHalf = SmuflGlyph.noteheadCircledHalf;

  static const noteheadCircledWhole = SmuflGlyph.noteheadCircledWhole;

  static const noteheadCircledDoubleWhole =
      SmuflGlyph.noteheadCircledDoubleWhole;

  static const noteheadCircledBlackLarge = SmuflGlyph.noteheadCircledBlackLarge;

  static const noteheadCircledHalfLarge = SmuflGlyph.noteheadCircledHalfLarge;

  static const noteheadCircledWholeLarge = SmuflGlyph.noteheadCircledWholeLarge;

  static const noteheadCircledDoubleWholeLarge =
      SmuflGlyph.noteheadCircledDoubleWholeLarge;

  static const noteheadCircledXLarge = SmuflGlyph.noteheadCircledXLarge;

  static const noteheadLargeArrowUpDoubleWhole =
      SmuflGlyph.noteheadLargeArrowUpDoubleWhole;

  static const noteheadLargeArrowUpWhole = SmuflGlyph.noteheadLargeArrowUpWhole;

  static const noteheadLargeArrowUpHalf = SmuflGlyph.noteheadLargeArrowUpHalf;

  static const noteheadLargeArrowUpBlack = SmuflGlyph.noteheadLargeArrowUpBlack;

  static const noteheadLargeArrowDownDoubleWhole =
      SmuflGlyph.noteheadLargeArrowDownDoubleWhole;

  static const noteheadLargeArrowDownWhole =
      SmuflGlyph.noteheadLargeArrowDownWhole;

  static const noteheadLargeArrowDownHalf =
      SmuflGlyph.noteheadLargeArrowDownHalf;

  static const noteheadLargeArrowDownBlack =
      SmuflGlyph.noteheadLargeArrowDownBlack;

  static const noteheadParenthesisLeft = SmuflGlyph.noteheadParenthesisLeft;

  static const noteheadParenthesisRight = SmuflGlyph.noteheadParenthesisRight;

  static const noteheadCircleSlash = SmuflGlyph.noteheadCircleSlash;

  static const noteheadHeavyX = SmuflGlyph.noteheadHeavyX;

  static const noteheadHeavyXHat = SmuflGlyph.noteheadHeavyXHat;

  static const noteheadWholeFilled = SmuflGlyph.noteheadWholeFilled;

  static const noteheadHalfFilled = SmuflGlyph.noteheadHalfFilled;

  static const noteheadDiamondOpen = SmuflGlyph.noteheadDiamondOpen;

  static const noteheadSlashVerticalEnds = SmuflGlyph.noteheadSlashVerticalEnds;

  static const noteheadSlashHorizontalEnds =
      SmuflGlyph.noteheadSlashHorizontalEnds;

  static const noteheadSlashWhiteWhole = SmuflGlyph.noteheadSlashWhiteWhole;

  static const noteheadSlashWhiteHalf = SmuflGlyph.noteheadSlashWhiteHalf;

  static const noteheadSlashDiamondWhite = SmuflGlyph.noteheadSlashDiamondWhite;

  static const noteheadSlashVerticalEndsSmall =
      SmuflGlyph.noteheadSlashVerticalEndsSmall;

  static const noteheadSlashX = SmuflGlyph.noteheadSlashX;

  static const noteheadSlashVerticalEndsMuted =
      SmuflGlyph.noteheadSlashVerticalEndsMuted;

  static const noteheadSlashHorizontalEndsMuted =
      SmuflGlyph.noteheadSlashHorizontalEndsMuted;

  static const noteheadSlashWhiteMuted = SmuflGlyph.noteheadSlashWhiteMuted;

  static const noteheadSlashWhiteDoubleWhole =
      SmuflGlyph.noteheadSlashWhiteDoubleWhole;

  static const noteheadRoundBlackLarge = SmuflGlyph.noteheadRoundBlackLarge;

  static const noteheadRoundWhiteLarge = SmuflGlyph.noteheadRoundWhiteLarge;

  static const noteheadRoundWhiteWithDotLarge =
      SmuflGlyph.noteheadRoundWhiteWithDotLarge;

  static const noteheadRoundBlack = SmuflGlyph.noteheadRoundBlack;

  static const noteheadRoundWhite = SmuflGlyph.noteheadRoundWhite;

  static const noteheadRoundWhiteWithDot = SmuflGlyph.noteheadRoundWhiteWithDot;

  static const noteheadRoundBlackSlashedLarge =
      SmuflGlyph.noteheadRoundBlackSlashedLarge;

  static const noteheadRoundWhiteSlashedLarge =
      SmuflGlyph.noteheadRoundWhiteSlashedLarge;

  static const noteheadRoundBlackSlashed = SmuflGlyph.noteheadRoundBlackSlashed;

  static const noteheadRoundWhiteSlashed = SmuflGlyph.noteheadRoundWhiteSlashed;

  static const noteheadSquareBlackLarge = SmuflGlyph.noteheadSquareBlackLarge;

  static const noteheadSquareBlackWhite = SmuflGlyph.noteheadSquareBlackWhite;

  static const noteheadRoundBlackDoubleSlashed =
      SmuflGlyph.noteheadRoundBlackDoubleSlashed;

  static const noteheadRoundWhiteDoubleSlashed =
      SmuflGlyph.noteheadRoundWhiteDoubleSlashed;

  static const noteheadClusterSquareWhite =
      SmuflGlyph.noteheadClusterSquareWhite;

  static const noteheadClusterSquareBlack =
      SmuflGlyph.noteheadClusterSquareBlack;

  static const noteheadClusterRoundWhite = SmuflGlyph.noteheadClusterRoundWhite;

  static const noteheadClusterRoundBlack = SmuflGlyph.noteheadClusterRoundBlack;

  static const noteheadClusterDoubleWhole2nd =
      SmuflGlyph.noteheadClusterDoubleWhole2nd;

  static const noteheadClusterWhole2nd = SmuflGlyph.noteheadClusterWhole2nd;

  static const noteheadClusterHalf2nd = SmuflGlyph.noteheadClusterHalf2nd;

  static const noteheadClusterQuarter2nd = SmuflGlyph.noteheadClusterQuarter2nd;

  static const noteheadClusterDoubleWhole3rd =
      SmuflGlyph.noteheadClusterDoubleWhole3rd;

  static const noteheadClusterWhole3rd = SmuflGlyph.noteheadClusterWhole3rd;

  static const noteheadClusterHalf3rd = SmuflGlyph.noteheadClusterHalf3rd;

  static const noteheadClusterQuarter3rd = SmuflGlyph.noteheadClusterQuarter3rd;

  static const noteheadClusterDoubleWholeTop =
      SmuflGlyph.noteheadClusterDoubleWholeTop;

  static const noteheadClusterDoubleWholeMiddle =
      SmuflGlyph.noteheadClusterDoubleWholeMiddle;

  static const noteheadClusterDoubleWholeBottom =
      SmuflGlyph.noteheadClusterDoubleWholeBottom;

  static const noteheadClusterWholeTop = SmuflGlyph.noteheadClusterWholeTop;

  static const noteheadClusterWholeMiddle =
      SmuflGlyph.noteheadClusterWholeMiddle;

  static const noteheadClusterWholeBottom =
      SmuflGlyph.noteheadClusterWholeBottom;

  static const noteheadClusterHalfTop = SmuflGlyph.noteheadClusterHalfTop;

  static const noteheadClusterHalfMiddle = SmuflGlyph.noteheadClusterHalfMiddle;

  static const noteheadClusterHalfBottom = SmuflGlyph.noteheadClusterHalfBottom;

  static const noteheadClusterQuarterTop = SmuflGlyph.noteheadClusterQuarterTop;

  static const noteheadClusterQuarterMiddle =
      SmuflGlyph.noteheadClusterQuarterMiddle;

  static const noteheadClusterQuarterBottom =
      SmuflGlyph.noteheadClusterQuarterBottom;

  static const noteheadDiamondClusterWhite2nd =
      SmuflGlyph.noteheadDiamondClusterWhite2nd;

  static const noteheadDiamondClusterBlack2nd =
      SmuflGlyph.noteheadDiamondClusterBlack2nd;

  static const noteheadDiamondClusterWhite3rd =
      SmuflGlyph.noteheadDiamondClusterWhite3rd;

  static const noteheadDiamondClusterBlack3rd =
      SmuflGlyph.noteheadDiamondClusterBlack3rd;

  static const noteheadDiamondClusterWhiteTop =
      SmuflGlyph.noteheadDiamondClusterWhiteTop;

  static const noteheadDiamondClusterWhiteMiddle =
      SmuflGlyph.noteheadDiamondClusterWhiteMiddle;

  static const noteheadDiamondClusterWhiteBottom =
      SmuflGlyph.noteheadDiamondClusterWhiteBottom;

  static const noteheadDiamondClusterBlackTop =
      SmuflGlyph.noteheadDiamondClusterBlackTop;

  static const noteheadDiamondClusterBlackMiddle =
      SmuflGlyph.noteheadDiamondClusterBlackMiddle;

  static const noteheadDiamondClusterBlackBottom =
      SmuflGlyph.noteheadDiamondClusterBlackBottom;

  static const noteheadRectangularClusterBlackTop =
      SmuflGlyph.noteheadRectangularClusterBlackTop;

  static const noteheadRectangularClusterBlackMiddle =
      SmuflGlyph.noteheadRectangularClusterBlackMiddle;

  static const noteheadRectangularClusterBlackBottom =
      SmuflGlyph.noteheadRectangularClusterBlackBottom;

  static const noteheadRectangularClusterWhiteTop =
      SmuflGlyph.noteheadRectangularClusterWhiteTop;

  static const noteheadRectangularClusterWhiteMiddle =
      SmuflGlyph.noteheadRectangularClusterWhiteMiddle;

  static const noteheadRectangularClusterWhiteBottom =
      SmuflGlyph.noteheadRectangularClusterWhiteBottom;

  static const noteDoWhole = SmuflGlyph.noteDoWhole;

  static const noteReWhole = SmuflGlyph.noteReWhole;

  static const noteMiWhole = SmuflGlyph.noteMiWhole;

  static const noteFaWhole = SmuflGlyph.noteFaWhole;

  static const noteSoWhole = SmuflGlyph.noteSoWhole;

  static const noteLaWhole = SmuflGlyph.noteLaWhole;

  static const noteTiWhole = SmuflGlyph.noteTiWhole;

  static const noteSiWhole = SmuflGlyph.noteSiWhole;

  static const noteDoHalf = SmuflGlyph.noteDoHalf;

  static const noteReHalf = SmuflGlyph.noteReHalf;

  static const noteMiHalf = SmuflGlyph.noteMiHalf;

  static const noteFaHalf = SmuflGlyph.noteFaHalf;

  static const noteSoHalf = SmuflGlyph.noteSoHalf;

  static const noteLaHalf = SmuflGlyph.noteLaHalf;

  static const noteTiHalf = SmuflGlyph.noteTiHalf;

  static const noteSiHalf = SmuflGlyph.noteSiHalf;

  static const noteDoBlack = SmuflGlyph.noteDoBlack;

  static const noteReBlack = SmuflGlyph.noteReBlack;

  static const noteMiBlack = SmuflGlyph.noteMiBlack;

  static const noteFaBlack = SmuflGlyph.noteFaBlack;

  static const noteSoBlack = SmuflGlyph.noteSoBlack;

  static const noteLaBlack = SmuflGlyph.noteLaBlack;

  static const noteTiBlack = SmuflGlyph.noteTiBlack;

  static const noteSiBlack = SmuflGlyph.noteSiBlack;

  static const noteAFlatWhole = SmuflGlyph.noteAFlatWhole;

  static const noteAWhole = SmuflGlyph.noteAWhole;

  static const noteASharpWhole = SmuflGlyph.noteASharpWhole;

  static const noteBFlatWhole = SmuflGlyph.noteBFlatWhole;

  static const noteBWhole = SmuflGlyph.noteBWhole;

  static const noteBSharpWhole = SmuflGlyph.noteBSharpWhole;

  static const noteCFlatWhole = SmuflGlyph.noteCFlatWhole;

  static const noteCWhole = SmuflGlyph.noteCWhole;

  static const noteCSharpWhole = SmuflGlyph.noteCSharpWhole;

  static const noteDFlatWhole = SmuflGlyph.noteDFlatWhole;

  static const noteDWhole = SmuflGlyph.noteDWhole;

  static const noteDSharpWhole = SmuflGlyph.noteDSharpWhole;

  static const noteEFlatWhole = SmuflGlyph.noteEFlatWhole;

  static const noteEWhole = SmuflGlyph.noteEWhole;

  static const noteESharpWhole = SmuflGlyph.noteESharpWhole;

  static const noteFFlatWhole = SmuflGlyph.noteFFlatWhole;

  static const noteFWhole = SmuflGlyph.noteFWhole;

  static const noteFSharpWhole = SmuflGlyph.noteFSharpWhole;

  static const noteGFlatWhole = SmuflGlyph.noteGFlatWhole;

  static const noteGWhole = SmuflGlyph.noteGWhole;

  static const noteGSharpWhole = SmuflGlyph.noteGSharpWhole;

  static const noteHWhole = SmuflGlyph.noteHWhole;

  static const noteHSharpWhole = SmuflGlyph.noteHSharpWhole;

  static const noteAFlatHalf = SmuflGlyph.noteAFlatHalf;

  static const noteAHalf = SmuflGlyph.noteAHalf;

  static const noteASharpHalf = SmuflGlyph.noteASharpHalf;

  static const noteBFlatHalf = SmuflGlyph.noteBFlatHalf;

  static const noteBHalf = SmuflGlyph.noteBHalf;

  static const noteBSharpHalf = SmuflGlyph.noteBSharpHalf;

  static const noteCFlatHalf = SmuflGlyph.noteCFlatHalf;

  static const noteCHalf = SmuflGlyph.noteCHalf;

  static const noteCSharpHalf = SmuflGlyph.noteCSharpHalf;

  static const noteDFlatHalf = SmuflGlyph.noteDFlatHalf;

  static const noteDHalf = SmuflGlyph.noteDHalf;

  static const noteDSharpHalf = SmuflGlyph.noteDSharpHalf;

  static const noteEFlatHalf = SmuflGlyph.noteEFlatHalf;

  static const noteEHalf = SmuflGlyph.noteEHalf;

  static const noteESharpHalf = SmuflGlyph.noteESharpHalf;

  static const noteFFlatHalf = SmuflGlyph.noteFFlatHalf;

  static const noteFHalf = SmuflGlyph.noteFHalf;

  static const noteFSharpHalf = SmuflGlyph.noteFSharpHalf;

  static const noteGFlatHalf = SmuflGlyph.noteGFlatHalf;

  static const noteGHalf = SmuflGlyph.noteGHalf;

  static const noteGSharpHalf = SmuflGlyph.noteGSharpHalf;

  static const noteHHalf = SmuflGlyph.noteHHalf;

  static const noteHSharpHalf = SmuflGlyph.noteHSharpHalf;

  static const noteAFlatBlack = SmuflGlyph.noteAFlatBlack;

  static const noteABlack = SmuflGlyph.noteABlack;

  static const noteASharpBlack = SmuflGlyph.noteASharpBlack;

  static const noteBFlatBlack = SmuflGlyph.noteBFlatBlack;

  static const noteBBlack = SmuflGlyph.noteBBlack;

  static const noteBSharpBlack = SmuflGlyph.noteBSharpBlack;

  static const noteCFlatBlack = SmuflGlyph.noteCFlatBlack;

  static const noteCBlack = SmuflGlyph.noteCBlack;

  static const noteCSharpBlack = SmuflGlyph.noteCSharpBlack;

  static const noteDFlatBlack = SmuflGlyph.noteDFlatBlack;

  static const noteDBlack = SmuflGlyph.noteDBlack;

  static const noteDSharpBlack = SmuflGlyph.noteDSharpBlack;

  static const noteEFlatBlack = SmuflGlyph.noteEFlatBlack;

  static const noteEBlack = SmuflGlyph.noteEBlack;

  static const noteESharpBlack = SmuflGlyph.noteESharpBlack;

  static const noteFFlatBlack = SmuflGlyph.noteFFlatBlack;

  static const noteFBlack = SmuflGlyph.noteFBlack;

  static const noteFSharpBlack = SmuflGlyph.noteFSharpBlack;

  static const noteGFlatBlack = SmuflGlyph.noteGFlatBlack;

  static const noteGBlack = SmuflGlyph.noteGBlack;

  static const noteGSharpBlack = SmuflGlyph.noteGSharpBlack;

  static const noteHBlack = SmuflGlyph.noteHBlack;

  static const noteHSharpBlack = SmuflGlyph.noteHSharpBlack;

  static const noteEmptyWhole = SmuflGlyph.noteEmptyWhole;

  static const noteEmptyHalf = SmuflGlyph.noteEmptyHalf;

  static const noteEmptyBlack = SmuflGlyph.noteEmptyBlack;

  static const noteShapeRoundDoubleWhole = SmuflGlyph.noteShapeRoundDoubleWhole;

  static const noteShapeSquareDoubleWhole =
      SmuflGlyph.noteShapeSquareDoubleWhole;

  static const noteShapeTriangleRightDoubleWhole =
      SmuflGlyph.noteShapeTriangleRightDoubleWhole;

  static const noteShapeTriangleLeftDoubleWhole =
      SmuflGlyph.noteShapeTriangleLeftDoubleWhole;

  static const noteShapeDiamondDoubleWhole =
      SmuflGlyph.noteShapeDiamondDoubleWhole;

  static const noteShapeTriangleUpDoubleWhole =
      SmuflGlyph.noteShapeTriangleUpDoubleWhole;

  static const noteShapeMoonDoubleWhole = SmuflGlyph.noteShapeMoonDoubleWhole;

  static const noteShapeTriangleRoundDoubleWhole =
      SmuflGlyph.noteShapeTriangleRoundDoubleWhole;

  static const noteShapeKeystoneDoubleWhole =
      SmuflGlyph.noteShapeKeystoneDoubleWhole;

  static const noteShapeQuarterMoonDoubleWhole =
      SmuflGlyph.noteShapeQuarterMoonDoubleWhole;

  static const noteShapeIsoscelesTriangleDoubleWhole =
      SmuflGlyph.noteShapeIsoscelesTriangleDoubleWhole;

  static const noteShapeMoonLeftDoubleWhole =
      SmuflGlyph.noteShapeMoonLeftDoubleWhole;

  static const noteShapeArrowheadLeftDoubleWhole =
      SmuflGlyph.noteShapeArrowheadLeftDoubleWhole;

  static const noteShapeTriangleRoundLeftDoubleWhole =
      SmuflGlyph.noteShapeTriangleRoundLeftDoubleWhole;

  static const swissRudimentsNoteheadBlackFlam =
      SmuflGlyph.swissRudimentsNoteheadBlackFlam;

  static const swissRudimentsNoteheadHalfFlam =
      SmuflGlyph.swissRudimentsNoteheadHalfFlam;

  static const swissRudimentsNoteheadHalfDouble =
      SmuflGlyph.swissRudimentsNoteheadHalfDouble;
}
