// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetWithX extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadDoubleWholeWithX,
        SmuflGlyph.noteheadWholeWithX,
        SmuflGlyph.noteheadHalfWithX,
        SmuflGlyph.noteheadVoidWithX,
      ];

  static const noteheadDoubleWholeWithX = SmuflGlyph.noteheadDoubleWholeWithX;

  static const noteheadWholeWithX = SmuflGlyph.noteheadWholeWithX;

  static const noteheadHalfWithX = SmuflGlyph.noteheadHalfWithX;

  static const noteheadVoidWithX = SmuflGlyph.noteheadVoidWithX;
}
