// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetTriangleRight extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadTriangleRightWhite,
        SmuflGlyph.noteheadTriangleRightBlack,
      ];

  static const noteheadTriangleRightWhite =
      SmuflGlyph.noteheadTriangleRightWhite;

  static const noteheadTriangleRightBlack =
      SmuflGlyph.noteheadTriangleRightBlack;
}
