// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetSlashHorizontalEnds extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadSlashHorizontalEnds,
        SmuflGlyph.noteheadSlashWhiteHalf,
        SmuflGlyph.noteheadSlashDiamondWhite,
        SmuflGlyph.noteheadSlashX,
        SmuflGlyph.noteheadSlashHorizontalEndsMuted,
        SmuflGlyph.noteheadSlashWhiteMuted,
        SmuflGlyph.noteheadSlashWhiteDoubleWhole,
      ];

  static const noteheadSlashHorizontalEnds =
      SmuflGlyph.noteheadSlashHorizontalEnds;

  static const noteheadSlashWhiteHalf = SmuflGlyph.noteheadSlashWhiteHalf;

  static const noteheadSlashDiamondWhite = SmuflGlyph.noteheadSlashDiamondWhite;

  static const noteheadSlashX = SmuflGlyph.noteheadSlashX;

  static const noteheadSlashHorizontalEndsMuted =
      SmuflGlyph.noteheadSlashHorizontalEndsMuted;

  static const noteheadSlashWhiteMuted = SmuflGlyph.noteheadSlashWhiteMuted;

  static const noteheadSlashWhiteDoubleWhole =
      SmuflGlyph.noteheadSlashWhiteDoubleWhole;
}
