// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetDiamond extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadDiamondDoubleWhole,
        SmuflGlyph.noteheadDiamondWhole,
        SmuflGlyph.noteheadDiamondHalf,
        SmuflGlyph.noteheadDiamondBlack,
        SmuflGlyph.noteheadDiamondClusterWhite2nd,
        SmuflGlyph.noteheadDiamondClusterBlack2nd,
        SmuflGlyph.noteheadDiamondClusterWhite3rd,
        SmuflGlyph.noteheadDiamondClusterBlack3rd,
        SmuflGlyph.noteheadDiamondClusterWhiteTop,
        SmuflGlyph.noteheadDiamondClusterWhiteMiddle,
        SmuflGlyph.noteheadDiamondClusterWhiteBottom,
        SmuflGlyph.noteheadDiamondClusterBlackTop,
        SmuflGlyph.noteheadDiamondClusterBlackMiddle,
        SmuflGlyph.noteheadDiamondClusterBlackBottom,
      ];

  static const noteheadDiamondDoubleWhole =
      SmuflGlyph.noteheadDiamondDoubleWhole;

  static const noteheadDiamondWhole = SmuflGlyph.noteheadDiamondWhole;

  static const noteheadDiamondHalf = SmuflGlyph.noteheadDiamondHalf;

  static const noteheadDiamondBlack = SmuflGlyph.noteheadDiamondBlack;

  static const noteheadDiamondClusterWhite2nd =
      SmuflGlyph.noteheadDiamondClusterWhite2nd;

  static const noteheadDiamondClusterBlack2nd =
      SmuflGlyph.noteheadDiamondClusterBlack2nd;

  static const noteheadDiamondClusterWhite3rd =
      SmuflGlyph.noteheadDiamondClusterWhite3rd;

  static const noteheadDiamondClusterBlack3rd =
      SmuflGlyph.noteheadDiamondClusterBlack3rd;

  static const noteheadDiamondClusterWhiteTop =
      SmuflGlyph.noteheadDiamondClusterWhiteTop;

  static const noteheadDiamondClusterWhiteMiddle =
      SmuflGlyph.noteheadDiamondClusterWhiteMiddle;

  static const noteheadDiamondClusterWhiteBottom =
      SmuflGlyph.noteheadDiamondClusterWhiteBottom;

  static const noteheadDiamondClusterBlackTop =
      SmuflGlyph.noteheadDiamondClusterBlackTop;

  static const noteheadDiamondClusterBlackMiddle =
      SmuflGlyph.noteheadDiamondClusterBlackMiddle;

  static const noteheadDiamondClusterBlackBottom =
      SmuflGlyph.noteheadDiamondClusterBlackBottom;
}
