// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetCircled extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadCircledBlack,
        SmuflGlyph.noteheadCircledHalf,
        SmuflGlyph.noteheadCircledWhole,
        SmuflGlyph.noteheadCircledDoubleWhole,
        SmuflGlyph.noteheadCircledBlackLarge,
        SmuflGlyph.noteheadCircledHalfLarge,
        SmuflGlyph.noteheadCircledWholeLarge,
        SmuflGlyph.noteheadCircledDoubleWholeLarge,
        SmuflGlyph.noteheadCircledXLarge,
      ];

  static const noteheadCircledBlack = SmuflGlyph.noteheadCircledBlack;

  static const noteheadCircledHalf = SmuflGlyph.noteheadCircledHalf;

  static const noteheadCircledWhole = SmuflGlyph.noteheadCircledWhole;

  static const noteheadCircledDoubleWhole =
      SmuflGlyph.noteheadCircledDoubleWhole;

  static const noteheadCircledBlackLarge = SmuflGlyph.noteheadCircledBlackLarge;

  static const noteheadCircledHalfLarge = SmuflGlyph.noteheadCircledHalfLarge;

  static const noteheadCircledWholeLarge = SmuflGlyph.noteheadCircledWholeLarge;

  static const noteheadCircledDoubleWholeLarge =
      SmuflGlyph.noteheadCircledDoubleWholeLarge;

  static const noteheadCircledXLarge = SmuflGlyph.noteheadCircledXLarge;
}
