// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetX extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadXDoubleWhole,
        SmuflGlyph.noteheadXWhole,
        SmuflGlyph.noteheadXHalf,
        SmuflGlyph.noteheadXBlack,
        SmuflGlyph.noteheadXOrnate,
        SmuflGlyph.noteheadXOrnateEllipse,
      ];

  static const noteheadXDoubleWhole = SmuflGlyph.noteheadXDoubleWhole;

  static const noteheadXWhole = SmuflGlyph.noteheadXWhole;

  static const noteheadXHalf = SmuflGlyph.noteheadXHalf;

  static const noteheadXBlack = SmuflGlyph.noteheadXBlack;

  static const noteheadXOrnate = SmuflGlyph.noteheadXOrnate;

  static const noteheadXOrnateEllipse = SmuflGlyph.noteheadXOrnateEllipse;
}
