// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetNamesSolfege extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteDoWhole,
        SmuflGlyph.noteReWhole,
        SmuflGlyph.noteMiWhole,
        SmuflGlyph.noteFaWhole,
        SmuflGlyph.noteSoWhole,
        SmuflGlyph.noteLaWhole,
        SmuflGlyph.noteTiWhole,
        SmuflGlyph.noteSiWhole,
        SmuflGlyph.noteDoHalf,
        SmuflGlyph.noteReHalf,
        SmuflGlyph.noteMiHalf,
        SmuflGlyph.noteFaHalf,
        SmuflGlyph.noteSoHalf,
        SmuflGlyph.noteLaHalf,
        SmuflGlyph.noteTiHalf,
        SmuflGlyph.noteSiHalf,
        SmuflGlyph.noteDoBlack,
        SmuflGlyph.noteReBlack,
        SmuflGlyph.noteMiBlack,
        SmuflGlyph.noteFaBlack,
        SmuflGlyph.noteSoBlack,
        SmuflGlyph.noteLaBlack,
        SmuflGlyph.noteTiBlack,
        SmuflGlyph.noteSiBlack,
      ];

  static const noteDoWhole = SmuflGlyph.noteDoWhole;

  static const noteReWhole = SmuflGlyph.noteReWhole;

  static const noteMiWhole = SmuflGlyph.noteMiWhole;

  static const noteFaWhole = SmuflGlyph.noteFaWhole;

  static const noteSoWhole = SmuflGlyph.noteSoWhole;

  static const noteLaWhole = SmuflGlyph.noteLaWhole;

  static const noteTiWhole = SmuflGlyph.noteTiWhole;

  static const noteSiWhole = SmuflGlyph.noteSiWhole;

  static const noteDoHalf = SmuflGlyph.noteDoHalf;

  static const noteReHalf = SmuflGlyph.noteReHalf;

  static const noteMiHalf = SmuflGlyph.noteMiHalf;

  static const noteFaHalf = SmuflGlyph.noteFaHalf;

  static const noteSoHalf = SmuflGlyph.noteSoHalf;

  static const noteLaHalf = SmuflGlyph.noteLaHalf;

  static const noteTiHalf = SmuflGlyph.noteTiHalf;

  static const noteSiHalf = SmuflGlyph.noteSiHalf;

  static const noteDoBlack = SmuflGlyph.noteDoBlack;

  static const noteReBlack = SmuflGlyph.noteReBlack;

  static const noteMiBlack = SmuflGlyph.noteMiBlack;

  static const noteFaBlack = SmuflGlyph.noteFaBlack;

  static const noteSoBlack = SmuflGlyph.noteSoBlack;

  static const noteLaBlack = SmuflGlyph.noteLaBlack;

  static const noteTiBlack = SmuflGlyph.noteTiBlack;

  static const noteSiBlack = SmuflGlyph.noteSiBlack;
}
