// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetCircleX extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadCircleXDoubleWhole,
        SmuflGlyph.noteheadCircleXWhole,
        SmuflGlyph.noteheadCircleXHalf,
        SmuflGlyph.noteheadCircleX,
        SmuflGlyph.noteheadDoubleWholeWithX,
      ];

  static const noteheadCircleXDoubleWhole =
      SmuflGlyph.noteheadCircleXDoubleWhole;

  static const noteheadCircleXWhole = SmuflGlyph.noteheadCircleXWhole;

  static const noteheadCircleXHalf = SmuflGlyph.noteheadCircleXHalf;

  static const noteheadCircleX = SmuflGlyph.noteheadCircleX;

  static const noteheadDoubleWholeWithX = SmuflGlyph.noteheadDoubleWholeWithX;
}
