// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetTriangleDown extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadTriangleDownDoubleWhole,
        SmuflGlyph.noteheadTriangleDownWhole,
        SmuflGlyph.noteheadTriangleDownHalf,
        SmuflGlyph.noteheadTriangleDownWhite,
        SmuflGlyph.noteheadTriangleDownBlack,
      ];

  static const noteheadTriangleDownDoubleWhole =
      SmuflGlyph.noteheadTriangleDownDoubleWhole;

  static const noteheadTriangleDownWhole = SmuflGlyph.noteheadTriangleDownWhole;

  static const noteheadTriangleDownHalf = SmuflGlyph.noteheadTriangleDownHalf;

  static const noteheadTriangleDownWhite = SmuflGlyph.noteheadTriangleDownWhite;

  static const noteheadTriangleDownBlack = SmuflGlyph.noteheadTriangleDownBlack;
}
