// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetPlus extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadPlusDoubleWhole,
        SmuflGlyph.noteheadPlusWhole,
        SmuflGlyph.noteheadPlusHalf,
        SmuflGlyph.noteheadPlusBlack,
        SmuflGlyph.noteheadCircleXDoubleWhole,
      ];

  static const noteheadPlusDoubleWhole = SmuflGlyph.noteheadPlusDoubleWhole;

  static const noteheadPlusWhole = SmuflGlyph.noteheadPlusWhole;

  static const noteheadPlusHalf = SmuflGlyph.noteheadPlusHalf;

  static const noteheadPlusBlack = SmuflGlyph.noteheadPlusBlack;

  static const noteheadCircleXDoubleWhole =
      SmuflGlyph.noteheadCircleXDoubleWhole;
}
