// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetLargeArrowDown extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadLargeArrowDownDoubleWhole,
        SmuflGlyph.noteheadLargeArrowDownWhole,
        SmuflGlyph.noteheadLargeArrowDownHalf,
        SmuflGlyph.noteheadLargeArrowDownBlack,
      ];

  static const noteheadLargeArrowDownDoubleWhole =
      SmuflGlyph.noteheadLargeArrowDownDoubleWhole;

  static const noteheadLargeArrowDownWhole =
      SmuflGlyph.noteheadLargeArrowDownWhole;

  static const noteheadLargeArrowDownHalf =
      SmuflGlyph.noteheadLargeArrowDownHalf;

  static const noteheadLargeArrowDownBlack =
      SmuflGlyph.noteheadLargeArrowDownBlack;
}
