// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetSlashVerticalEnds extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadSlashVerticalEnds,
        SmuflGlyph.noteheadSlashWhiteHalf,
        SmuflGlyph.noteheadSlashDiamondWhite,
        SmuflGlyph.noteheadSlashVerticalEndsSmall,
        SmuflGlyph.noteheadSlashVerticalEndsMuted,
        SmuflGlyph.noteheadSlashWhiteMuted,
      ];

  static const noteheadSlashVerticalEnds = SmuflGlyph.noteheadSlashVerticalEnds;

  static const noteheadSlashWhiteHalf = SmuflGlyph.noteheadSlashWhiteHalf;

  static const noteheadSlashDiamondWhite = SmuflGlyph.noteheadSlashDiamondWhite;

  static const noteheadSlashVerticalEndsSmall =
      SmuflGlyph.noteheadSlashVerticalEndsSmall;

  static const noteheadSlashVerticalEndsMuted =
      SmuflGlyph.noteheadSlashVerticalEndsMuted;

  static const noteheadSlashWhiteMuted = SmuflGlyph.noteheadSlashWhiteMuted;
}
