// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetTriangleUp extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadTriangleUpDoubleWhole,
        SmuflGlyph.noteheadTriangleUpWhole,
        SmuflGlyph.noteheadTriangleUpHalf,
        SmuflGlyph.noteheadTriangleUpWhite,
        SmuflGlyph.noteheadTriangleUpBlack,
      ];

  static const noteheadTriangleUpDoubleWhole =
      SmuflGlyph.noteheadTriangleUpDoubleWhole;

  static const noteheadTriangleUpWhole = SmuflGlyph.noteheadTriangleUpWhole;

  static const noteheadTriangleUpHalf = SmuflGlyph.noteheadTriangleUpHalf;

  static const noteheadTriangleUpWhite = SmuflGlyph.noteheadTriangleUpWhite;

  static const noteheadTriangleUpBlack = SmuflGlyph.noteheadTriangleUpBlack;
}
