// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetSlashed1 extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadSlashedBlack1,
        SmuflGlyph.noteheadSlashedHalf1,
        SmuflGlyph.noteheadSlashedWhole1,
        SmuflGlyph.noteheadSlashedDoubleWhole1,
      ];

  static const noteheadSlashedBlack1 = SmuflGlyph.noteheadSlashedBlack1;

  static const noteheadSlashedHalf1 = SmuflGlyph.noteheadSlashedHalf1;

  static const noteheadSlashedWhole1 = SmuflGlyph.noteheadSlashedWhole1;

  static const noteheadSlashedDoubleWhole1 =
      SmuflGlyph.noteheadSlashedDoubleWhole1;
}
