// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetSquare extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadSquareBlackLarge,
        SmuflGlyph.noteheadSquareBlackWhite,
        SmuflGlyph.noteheadRectangularClusterBlackTop,
        SmuflGlyph.noteheadRectangularClusterBlackMiddle,
        SmuflGlyph.noteheadRectangularClusterBlackBottom,
        SmuflGlyph.noteheadRectangularClusterWhiteTop,
        SmuflGlyph.noteheadRectangularClusterWhiteMiddle,
        SmuflGlyph.noteheadRectangularClusterWhiteBottom,
      ];

  static const noteheadSquareBlackLarge = SmuflGlyph.noteheadSquareBlackLarge;

  static const noteheadSquareBlackWhite = SmuflGlyph.noteheadSquareBlackWhite;

  static const noteheadRectangularClusterBlackTop =
      SmuflGlyph.noteheadRectangularClusterBlackTop;

  static const noteheadRectangularClusterBlackMiddle =
      SmuflGlyph.noteheadRectangularClusterBlackMiddle;

  static const noteheadRectangularClusterBlackBottom =
      SmuflGlyph.noteheadRectangularClusterBlackBottom;

  static const noteheadRectangularClusterWhiteTop =
      SmuflGlyph.noteheadRectangularClusterWhiteTop;

  static const noteheadRectangularClusterWhiteMiddle =
      SmuflGlyph.noteheadRectangularClusterWhiteMiddle;

  static const noteheadRectangularClusterWhiteBottom =
      SmuflGlyph.noteheadRectangularClusterWhiteBottom;
}
