// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetDefault extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadDoubleWhole,
        SmuflGlyph.noteheadDoubleWholeSquare,
        SmuflGlyph.noteheadWhole,
        SmuflGlyph.noteheadHalf,
        SmuflGlyph.noteheadBlack,
        SmuflGlyph.noteheadClusterDoubleWhole2nd,
        SmuflGlyph.noteheadClusterWhole2nd,
        SmuflGlyph.noteheadClusterHalf2nd,
        SmuflGlyph.noteheadClusterQuarter2nd,
        SmuflGlyph.noteheadClusterDoubleWhole3rd,
        SmuflGlyph.noteheadClusterWhole3rd,
        SmuflGlyph.noteheadClusterHalf3rd,
        SmuflGlyph.noteheadClusterQuarter3rd,
        SmuflGlyph.noteheadClusterDoubleWholeTop,
        SmuflGlyph.noteheadClusterDoubleWholeMiddle,
        SmuflGlyph.noteheadClusterDoubleWholeBottom,
        SmuflGlyph.noteheadClusterWholeTop,
        SmuflGlyph.noteheadClusterWholeMiddle,
        SmuflGlyph.noteheadClusterWholeBottom,
        SmuflGlyph.noteheadClusterHalfTop,
        SmuflGlyph.noteheadClusterHalfMiddle,
        SmuflGlyph.noteheadClusterHalfBottom,
        SmuflGlyph.noteheadClusterQuarterTop,
        SmuflGlyph.noteheadClusterQuarterMiddle,
        SmuflGlyph.noteheadClusterQuarterBottom,
      ];

  static const noteheadDoubleWhole = SmuflGlyph.noteheadDoubleWhole;

  static const noteheadDoubleWholeSquare = SmuflGlyph.noteheadDoubleWholeSquare;

  static const noteheadWhole = SmuflGlyph.noteheadWhole;

  static const noteheadHalf = SmuflGlyph.noteheadHalf;

  static const noteheadBlack = SmuflGlyph.noteheadBlack;

  static const noteheadClusterDoubleWhole2nd =
      SmuflGlyph.noteheadClusterDoubleWhole2nd;

  static const noteheadClusterWhole2nd = SmuflGlyph.noteheadClusterWhole2nd;

  static const noteheadClusterHalf2nd = SmuflGlyph.noteheadClusterHalf2nd;

  static const noteheadClusterQuarter2nd = SmuflGlyph.noteheadClusterQuarter2nd;

  static const noteheadClusterDoubleWhole3rd =
      SmuflGlyph.noteheadClusterDoubleWhole3rd;

  static const noteheadClusterWhole3rd = SmuflGlyph.noteheadClusterWhole3rd;

  static const noteheadClusterHalf3rd = SmuflGlyph.noteheadClusterHalf3rd;

  static const noteheadClusterQuarter3rd = SmuflGlyph.noteheadClusterQuarter3rd;

  static const noteheadClusterDoubleWholeTop =
      SmuflGlyph.noteheadClusterDoubleWholeTop;

  static const noteheadClusterDoubleWholeMiddle =
      SmuflGlyph.noteheadClusterDoubleWholeMiddle;

  static const noteheadClusterDoubleWholeBottom =
      SmuflGlyph.noteheadClusterDoubleWholeBottom;

  static const noteheadClusterWholeTop = SmuflGlyph.noteheadClusterWholeTop;

  static const noteheadClusterWholeMiddle =
      SmuflGlyph.noteheadClusterWholeMiddle;

  static const noteheadClusterWholeBottom =
      SmuflGlyph.noteheadClusterWholeBottom;

  static const noteheadClusterHalfTop = SmuflGlyph.noteheadClusterHalfTop;

  static const noteheadClusterHalfMiddle = SmuflGlyph.noteheadClusterHalfMiddle;

  static const noteheadClusterHalfBottom = SmuflGlyph.noteheadClusterHalfBottom;

  static const noteheadClusterQuarterTop = SmuflGlyph.noteheadClusterQuarterTop;

  static const noteheadClusterQuarterMiddle =
      SmuflGlyph.noteheadClusterQuarterMiddle;

  static const noteheadClusterQuarterBottom =
      SmuflGlyph.noteheadClusterQuarterBottom;
}
