// Generated by tool.

part of "../glyph_class.dart";

class NoteheadSetRoundSmall extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadRoundBlack,
        SmuflGlyph.noteheadRoundWhite,
        SmuflGlyph.noteheadRoundWhiteWithDot,
        SmuflGlyph.noteheadRoundBlackSlashed,
        SmuflGlyph.noteheadRoundWhiteSlashed,
      ];

  static const noteheadRoundBlack = SmuflGlyph.noteheadRoundBlack;

  static const noteheadRoundWhite = SmuflGlyph.noteheadRoundWhite;

  static const noteheadRoundWhiteWithDot = SmuflGlyph.noteheadRoundWhiteWithDot;

  static const noteheadRoundBlackSlashed = SmuflGlyph.noteheadRoundBlackSlashed;

  static const noteheadRoundWhiteSlashed = SmuflGlyph.noteheadRoundWhiteSlashed;
}
