// Generated by tool.

part of "../glyph_class.dart";

class Octaves extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.ottava,
        SmuflGlyph.ottavaAlta,
        SmuflGlyph.ottavaBassa,
        SmuflGlyph.ottavaBassaBa,
        SmuflGlyph.quindicesima,
        SmuflGlyph.quindicesimaAlta,
        SmuflGlyph.quindicesimaBassa,
        SmuflGlyph.ventiduesima,
        SmuflGlyph.ventiduesimaAlta,
        SmuflGlyph.ventiduesimaBassa,
        SmuflGlyph.octaveParensLeft,
        SmuflGlyph.octaveParensRight,
        SmuflGlyph.ottavaBassaVb,
        SmuflGlyph.quindicesimaBassaMb,
        SmuflGlyph.ventiduesimaBassaMb,
        SmuflGlyph.octaveBassa,
        SmuflGlyph.octaveLoco,
        SmuflGlyph.octaveBaselineA,
        SmuflGlyph.octaveSuperscriptA,
        SmuflGlyph.octaveBaselineB,
        SmuflGlyph.octaveSuperscriptB,
        SmuflGlyph.octaveBaselineM,
        SmuflGlyph.octaveSuperscriptM,
        SmuflGlyph.octaveBaselineV,
        SmuflGlyph.octaveSuperscriptV,
      ];

  static const ottava = SmuflGlyph.ottava;

  static const ottavaAlta = SmuflGlyph.ottavaAlta;

  static const ottavaBassa = SmuflGlyph.ottavaBassa;

  static const ottavaBassaBa = SmuflGlyph.ottavaBassaBa;

  static const quindicesima = SmuflGlyph.quindicesima;

  static const quindicesimaAlta = SmuflGlyph.quindicesimaAlta;

  static const quindicesimaBassa = SmuflGlyph.quindicesimaBassa;

  static const ventiduesima = SmuflGlyph.ventiduesima;

  static const ventiduesimaAlta = SmuflGlyph.ventiduesimaAlta;

  static const ventiduesimaBassa = SmuflGlyph.ventiduesimaBassa;

  static const octaveParensLeft = SmuflGlyph.octaveParensLeft;

  static const octaveParensRight = SmuflGlyph.octaveParensRight;

  static const ottavaBassaVb = SmuflGlyph.ottavaBassaVb;

  static const quindicesimaBassaMb = SmuflGlyph.quindicesimaBassaMb;

  static const ventiduesimaBassaMb = SmuflGlyph.ventiduesimaBassaMb;

  static const octaveBassa = SmuflGlyph.octaveBassa;

  static const octaveLoco = SmuflGlyph.octaveLoco;

  static const octaveBaselineA = SmuflGlyph.octaveBaselineA;

  static const octaveSuperscriptA = SmuflGlyph.octaveSuperscriptA;

  static const octaveBaselineB = SmuflGlyph.octaveBaselineB;

  static const octaveSuperscriptB = SmuflGlyph.octaveSuperscriptB;

  static const octaveBaselineM = SmuflGlyph.octaveBaselineM;

  static const octaveSuperscriptM = SmuflGlyph.octaveSuperscriptM;

  static const octaveBaselineV = SmuflGlyph.octaveBaselineV;

  static const octaveSuperscriptV = SmuflGlyph.octaveSuperscriptV;
}
