// Generated by tool.

part of "../glyph_class.dart";

class ParenthesesNotehead extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.noteheadParenthesisLeft,
        SmuflGlyph.noteheadParenthesisRight,
      ];

  static const noteheadParenthesisLeft = SmuflGlyph.noteheadParenthesisLeft;

  static const noteheadParenthesisRight = SmuflGlyph.noteheadParenthesisRight;
}
