// Generated by tool.

part of "../glyph_class.dart";

class PausesBelow extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.fermataBelow,
        SmuflGlyph.fermataVeryShortBelow,
        SmuflGlyph.fermataShortBelow,
        SmuflGlyph.fermataLongBelow,
        SmuflGlyph.fermataVeryLongBelow,
        SmuflGlyph.fermataLongHenzeBelow,
        SmuflGlyph.fermataShortHenzeBelow,
      ];

  static const fermataBelow = SmuflGlyph.fermataBelow;

  static const fermataVeryShortBelow = SmuflGlyph.fermataVeryShortBelow;

  static const fermataShortBelow = SmuflGlyph.fermataShortBelow;

  static const fermataLongBelow = SmuflGlyph.fermataLongBelow;

  static const fermataVeryLongBelow = SmuflGlyph.fermataVeryLongBelow;

  static const fermataLongHenzeBelow = SmuflGlyph.fermataLongHenzeBelow;

  static const fermataShortHenzeBelow = SmuflGlyph.fermataShortHenzeBelow;
}
