// Generated by tool.

part of "../glyph_class.dart";

class Pauses extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.fermataAbove,
        SmuflGlyph.fermataBelow,
        SmuflGlyph.fermataVeryShortAbove,
        SmuflGlyph.fermataVeryShortBelow,
        SmuflGlyph.fermataShortAbove,
        SmuflGlyph.fermataShortBelow,
        SmuflGlyph.fermataLongAbove,
        SmuflGlyph.fermataLongBelow,
        SmuflGlyph.fermataVeryLongAbove,
        SmuflGlyph.fermataVeryLongBelow,
        SmuflGlyph.fermataLongHenzeAbove,
        SmuflGlyph.fermataLongHenzeBelow,
        SmuflGlyph.fermataShortHenzeAbove,
        SmuflGlyph.fermataShortHenzeBelow,
        SmuflGlyph.breathMarkComma,
        SmuflGlyph.caesura,
        SmuflGlyph.caesuraThick,
        SmuflGlyph.caesuraShort,
        SmuflGlyph.breathMarkSalzedo,
        SmuflGlyph.curlewSign,
        SmuflGlyph.caesuraSingleStroke,
      ];

  static const fermataAbove = SmuflGlyph.fermataAbove;

  static const fermataBelow = SmuflGlyph.fermataBelow;

  static const fermataVeryShortAbove = SmuflGlyph.fermataVeryShortAbove;

  static const fermataVeryShortBelow = SmuflGlyph.fermataVeryShortBelow;

  static const fermataShortAbove = SmuflGlyph.fermataShortAbove;

  static const fermataShortBelow = SmuflGlyph.fermataShortBelow;

  static const fermataLongAbove = SmuflGlyph.fermataLongAbove;

  static const fermataLongBelow = SmuflGlyph.fermataLongBelow;

  static const fermataVeryLongAbove = SmuflGlyph.fermataVeryLongAbove;

  static const fermataVeryLongBelow = SmuflGlyph.fermataVeryLongBelow;

  static const fermataLongHenzeAbove = SmuflGlyph.fermataLongHenzeAbove;

  static const fermataLongHenzeBelow = SmuflGlyph.fermataLongHenzeBelow;

  static const fermataShortHenzeAbove = SmuflGlyph.fermataShortHenzeAbove;

  static const fermataShortHenzeBelow = SmuflGlyph.fermataShortHenzeBelow;

  static const breathMarkComma = SmuflGlyph.breathMarkComma;

  static const caesura = SmuflGlyph.caesura;

  static const caesuraThick = SmuflGlyph.caesuraThick;

  static const caesuraShort = SmuflGlyph.caesuraShort;

  static const breathMarkSalzedo = SmuflGlyph.breathMarkSalzedo;

  static const curlewSign = SmuflGlyph.curlewSign;

  static const caesuraSingleStroke = SmuflGlyph.caesuraSingleStroke;
}
