// Generated by tool.

part of "../glyph_class.dart";

class PausesAbove extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.fermataAbove,
        SmuflGlyph.fermataVeryShortAbove,
        SmuflGlyph.fermataShortAbove,
        SmuflGlyph.fermataLongAbove,
        SmuflGlyph.fermataVeryLongAbove,
        SmuflGlyph.fermataLongHenzeAbove,
        SmuflGlyph.fermataShortHenzeAbove,
      ];

  static const fermataAbove = SmuflGlyph.fermataAbove;

  static const fermataVeryShortAbove = SmuflGlyph.fermataVeryShortAbove;

  static const fermataShortAbove = SmuflGlyph.fermataShortAbove;

  static const fermataLongAbove = SmuflGlyph.fermataLongAbove;

  static const fermataVeryLongAbove = SmuflGlyph.fermataVeryLongAbove;

  static const fermataLongHenzeAbove = SmuflGlyph.fermataLongHenzeAbove;

  static const fermataShortHenzeAbove = SmuflGlyph.fermataShortHenzeAbove;
}
