// Generated by tool.

part of "../glyph_class.dart";

class Rests extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.restMaxima,
        SmuflGlyph.restLonga,
        SmuflGlyph.restDoubleWhole,
        SmuflGlyph.restWhole,
        SmuflGlyph.restHalf,
        SmuflGlyph.restQuarter,
        SmuflGlyph.rest8th,
        SmuflGlyph.rest16th,
        SmuflGlyph.rest32nd,
        SmuflGlyph.rest64th,
        SmuflGlyph.rest128th,
        SmuflGlyph.rest256th,
        SmuflGlyph.rest512th,
        SmuflGlyph.rest1024th,
        SmuflGlyph.restHBar,
        SmuflGlyph.restHBarLeft,
        SmuflGlyph.restHBarRight,
        SmuflGlyph.restQuarterOld,
        SmuflGlyph.restDoubleWholeLegerLine,
        SmuflGlyph.restWholeLegerLine,
        SmuflGlyph.restHalfLegerLine,
        SmuflGlyph.restQuarterZ,
      ];

  static const restMaxima = SmuflGlyph.restMaxima;

  static const restLonga = SmuflGlyph.restLonga;

  static const restDoubleWhole = SmuflGlyph.restDoubleWhole;

  static const restWhole = SmuflGlyph.restWhole;

  static const restHalf = SmuflGlyph.restHalf;

  static const restQuarter = SmuflGlyph.restQuarter;

  static const rest8th = SmuflGlyph.rest8th;

  static const rest16th = SmuflGlyph.rest16th;

  static const rest32nd = SmuflGlyph.rest32nd;

  static const rest64th = SmuflGlyph.rest64th;

  static const rest128th = SmuflGlyph.rest128th;

  static const rest256th = SmuflGlyph.rest256th;

  static const rest512th = SmuflGlyph.rest512th;

  static const rest1024th = SmuflGlyph.rest1024th;

  static const restHBar = SmuflGlyph.restHBar;

  static const restHBarLeft = SmuflGlyph.restHBarLeft;

  static const restHBarRight = SmuflGlyph.restHBarRight;

  static const restQuarterOld = SmuflGlyph.restQuarterOld;

  static const restDoubleWholeLegerLine = SmuflGlyph.restDoubleWholeLegerLine;

  static const restWholeLegerLine = SmuflGlyph.restWholeLegerLine;

  static const restHalfLegerLine = SmuflGlyph.restHalfLegerLine;

  static const restQuarterZ = SmuflGlyph.restQuarterZ;
}
