// Generated by tool.

part of "../glyph_class.dart";

class StemDecorations extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.tremolo1,
        SmuflGlyph.tremolo2,
        SmuflGlyph.tremolo3,
        SmuflGlyph.tremolo4,
        SmuflGlyph.tremolo5,
        SmuflGlyph.buzzRoll,
        SmuflGlyph.pendereckiTremolo,
        SmuflGlyph.unmeasuredTremolo,
        SmuflGlyph.unmeasuredTremoloSimple,
        SmuflGlyph.windMultiphonicsBlackStem,
        SmuflGlyph.windMultiphonicsWhiteStem,
        SmuflGlyph.windMultiphonicsBlackWhiteStem,
        SmuflGlyph.stringsBowBehindBridge,
        SmuflGlyph.stringsBowOnBridge,
        SmuflGlyph.stringsBowOnTailpiece,
        SmuflGlyph.stringsVibratoPulse,
        SmuflGlyph.pluckedDampOnStem,
        SmuflGlyph.vocalSprechgesang,
        SmuflGlyph.vocalsSussurando,
        SmuflGlyph.harpStringNoiseStem,
        SmuflGlyph.pictRimShotOnStem,
        SmuflGlyph.pictSwishStem,
        SmuflGlyph.pictTurnRightStem,
        SmuflGlyph.pictTurnLeftStem,
        SmuflGlyph.pictTurnRightLeftStem,
        SmuflGlyph.pictCrushStem,
        SmuflGlyph.pictDeadNoteStem,
        SmuflGlyph.accdnRicochetStem2,
        SmuflGlyph.accdnRicochetStem3,
        SmuflGlyph.accdnRicochetStem4,
        SmuflGlyph.accdnRicochetStem5,
        SmuflGlyph.accdnRicochetStem6,
      ];

  static const tremolo1 = SmuflGlyph.tremolo1;

  static const tremolo2 = SmuflGlyph.tremolo2;

  static const tremolo3 = SmuflGlyph.tremolo3;

  static const tremolo4 = SmuflGlyph.tremolo4;

  static const tremolo5 = SmuflGlyph.tremolo5;

  static const buzzRoll = SmuflGlyph.buzzRoll;

  static const pendereckiTremolo = SmuflGlyph.pendereckiTremolo;

  static const unmeasuredTremolo = SmuflGlyph.unmeasuredTremolo;

  static const unmeasuredTremoloSimple = SmuflGlyph.unmeasuredTremoloSimple;

  static const windMultiphonicsBlackStem = SmuflGlyph.windMultiphonicsBlackStem;

  static const windMultiphonicsWhiteStem = SmuflGlyph.windMultiphonicsWhiteStem;

  static const windMultiphonicsBlackWhiteStem =
      SmuflGlyph.windMultiphonicsBlackWhiteStem;

  static const stringsBowBehindBridge = SmuflGlyph.stringsBowBehindBridge;

  static const stringsBowOnBridge = SmuflGlyph.stringsBowOnBridge;

  static const stringsBowOnTailpiece = SmuflGlyph.stringsBowOnTailpiece;

  static const stringsVibratoPulse = SmuflGlyph.stringsVibratoPulse;

  static const pluckedDampOnStem = SmuflGlyph.pluckedDampOnStem;

  static const vocalSprechgesang = SmuflGlyph.vocalSprechgesang;

  static const vocalsSussurando = SmuflGlyph.vocalsSussurando;

  static const harpStringNoiseStem = SmuflGlyph.harpStringNoiseStem;

  static const pictRimShotOnStem = SmuflGlyph.pictRimShotOnStem;

  static const pictSwishStem = SmuflGlyph.pictSwishStem;

  static const pictTurnRightStem = SmuflGlyph.pictTurnRightStem;

  static const pictTurnLeftStem = SmuflGlyph.pictTurnLeftStem;

  static const pictTurnRightLeftStem = SmuflGlyph.pictTurnRightLeftStem;

  static const pictCrushStem = SmuflGlyph.pictCrushStem;

  static const pictDeadNoteStem = SmuflGlyph.pictDeadNoteStem;

  static const accdnRicochetStem2 = SmuflGlyph.accdnRicochetStem2;

  static const accdnRicochetStem3 = SmuflGlyph.accdnRicochetStem3;

  static const accdnRicochetStem4 = SmuflGlyph.accdnRicochetStem4;

  static const accdnRicochetStem5 = SmuflGlyph.accdnRicochetStem5;

  static const accdnRicochetStem6 = SmuflGlyph.accdnRicochetStem6;
}
