// Generated by tool.

part of "../glyph_class.dart";

class TfChordSymbolAccidentals extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.csymAccidentalFlat,
        SmuflGlyph.csymAccidentalNatural,
        SmuflGlyph.csymAccidentalSharp,
        SmuflGlyph.csymAccidentalDoubleSharp,
        SmuflGlyph.csymAccidentalDoubleFlat,
        SmuflGlyph.csymAccidentalTripleSharp,
        SmuflGlyph.csymAccidentalTripleFlat,
      ];

  static const csymAccidentalFlat = SmuflGlyph.csymAccidentalFlat;

  static const csymAccidentalNatural = SmuflGlyph.csymAccidentalNatural;

  static const csymAccidentalSharp = SmuflGlyph.csymAccidentalSharp;

  static const csymAccidentalDoubleSharp = SmuflGlyph.csymAccidentalDoubleSharp;

  static const csymAccidentalDoubleFlat = SmuflGlyph.csymAccidentalDoubleFlat;

  static const csymAccidentalTripleSharp = SmuflGlyph.csymAccidentalTripleSharp;

  static const csymAccidentalTripleFlat = SmuflGlyph.csymAccidentalTripleFlat;
}
