// Generated by tool.

part of "../glyph_class.dart";

class TfChordSymbols extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.csymDiminished,
        SmuflGlyph.csymHalfDiminished,
        SmuflGlyph.csymAugmented,
        SmuflGlyph.csymMajorSeventh,
      ];

  static const csymDiminished = SmuflGlyph.csymDiminished;

  static const csymHalfDiminished = SmuflGlyph.csymHalfDiminished;

  static const csymAugmented = SmuflGlyph.csymAugmented;

  static const csymMajorSeventh = SmuflGlyph.csymMajorSeventh;
}
