// Generated by tool.

part of "../glyph_class.dart";

class TfDaseianNotation extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.daseianGraves1,
        SmuflGlyph.daseianGraves2,
        SmuflGlyph.daseianGraves3,
        SmuflGlyph.daseianGraves4,
        SmuflGlyph.daseianFinales1,
        SmuflGlyph.daseianFinales2,
        SmuflGlyph.daseianFinales3,
        SmuflGlyph.daseianFinales4,
        SmuflGlyph.daseianSuperiores1,
        SmuflGlyph.daseianSuperiores2,
        SmuflGlyph.daseianSuperiores3,
        SmuflGlyph.daseianSuperiores4,
        SmuflGlyph.daseianExcellentes1,
        SmuflGlyph.daseianExcellentes2,
        SmuflGlyph.daseianExcellentes3,
        SmuflGlyph.daseianExcellentes4,
        SmuflGlyph.daseianResidua1,
        SmuflGlyph.daseianResidua2,
      ];

  static const daseianGraves1 = SmuflGlyph.daseianGraves1;

  static const daseianGraves2 = SmuflGlyph.daseianGraves2;

  static const daseianGraves3 = SmuflGlyph.daseianGraves3;

  static const daseianGraves4 = SmuflGlyph.daseianGraves4;

  static const daseianFinales1 = SmuflGlyph.daseianFinales1;

  static const daseianFinales2 = SmuflGlyph.daseianFinales2;

  static const daseianFinales3 = SmuflGlyph.daseianFinales3;

  static const daseianFinales4 = SmuflGlyph.daseianFinales4;

  static const daseianSuperiores1 = SmuflGlyph.daseianSuperiores1;

  static const daseianSuperiores2 = SmuflGlyph.daseianSuperiores2;

  static const daseianSuperiores3 = SmuflGlyph.daseianSuperiores3;

  static const daseianSuperiores4 = SmuflGlyph.daseianSuperiores4;

  static const daseianExcellentes1 = SmuflGlyph.daseianExcellentes1;

  static const daseianExcellentes2 = SmuflGlyph.daseianExcellentes2;

  static const daseianExcellentes3 = SmuflGlyph.daseianExcellentes3;

  static const daseianExcellentes4 = SmuflGlyph.daseianExcellentes4;

  static const daseianResidua1 = SmuflGlyph.daseianResidua1;

  static const daseianResidua2 = SmuflGlyph.daseianResidua2;
}
