// Generated by tool.

part of "../glyph_class.dart";

class TfHarpPedals extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.harpPedalRaised,
        SmuflGlyph.harpPedalCentered,
        SmuflGlyph.harpPedalLowered,
        SmuflGlyph.harpPedalDivider,
      ];

  static const harpPedalRaised = SmuflGlyph.harpPedalRaised;

  static const harpPedalCentered = SmuflGlyph.harpPedalCentered;

  static const harpPedalLowered = SmuflGlyph.harpPedalLowered;

  static const harpPedalDivider = SmuflGlyph.harpPedalDivider;
}
