// Generated by tool.

part of "../glyph_class.dart";

class Tf_hairpins extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.dynamicCrescendoHairpin,
        SmuflGlyph.dynamicDiminuendoHairpin,
        SmuflGlyph.dynamicMessaDiVoce,
      ];

  static const dynamicCrescendoHairpin = SmuflGlyph.dynamicCrescendoHairpin;

  static const dynamicDiminuendoHairpin = SmuflGlyph.dynamicDiminuendoHairpin;

  static const dynamicMessaDiVoce = SmuflGlyph.dynamicMessaDiVoce;
}
