// Generated by tool.

part of "../glyph_class.dart";

class Tf_metronomeMarks extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.metNoteDoubleWhole,
        SmuflGlyph.metNoteDoubleWholeSquare,
        SmuflGlyph.metNoteWhole,
        SmuflGlyph.metNoteHalfUp,
        SmuflGlyph.metNoteHalfDown,
        SmuflGlyph.metNoteQuarterUp,
        SmuflGlyph.metNoteQuarterDown,
        SmuflGlyph.metNote8thUp,
        SmuflGlyph.metNote8thDown,
        SmuflGlyph.metNote16thUp,
        SmuflGlyph.metNote16thDown,
        SmuflGlyph.metNote32ndUp,
        SmuflGlyph.metNote32ndDown,
        SmuflGlyph.metNote64thUp,
        SmuflGlyph.metNote64thDown,
        SmuflGlyph.metNote128thUp,
        SmuflGlyph.metNote128thDown,
        SmuflGlyph.metNote256thUp,
        SmuflGlyph.metNote256thDown,
        SmuflGlyph.metNote512thUp,
        SmuflGlyph.metNote512thDown,
        SmuflGlyph.metNote1024thUp,
        SmuflGlyph.metNote1024thDown,
        SmuflGlyph.metAugmentationDot,
      ];

  static const metNoteDoubleWhole = SmuflGlyph.metNoteDoubleWhole;

  static const metNoteDoubleWholeSquare = SmuflGlyph.metNoteDoubleWholeSquare;

  static const metNoteWhole = SmuflGlyph.metNoteWhole;

  static const metNoteHalfUp = SmuflGlyph.metNoteHalfUp;

  static const metNoteHalfDown = SmuflGlyph.metNoteHalfDown;

  static const metNoteQuarterUp = SmuflGlyph.metNoteQuarterUp;

  static const metNoteQuarterDown = SmuflGlyph.metNoteQuarterDown;

  static const metNote8thUp = SmuflGlyph.metNote8thUp;

  static const metNote8thDown = SmuflGlyph.metNote8thDown;

  static const metNote16thUp = SmuflGlyph.metNote16thUp;

  static const metNote16thDown = SmuflGlyph.metNote16thDown;

  static const metNote32ndUp = SmuflGlyph.metNote32ndUp;

  static const metNote32ndDown = SmuflGlyph.metNote32ndDown;

  static const metNote64thUp = SmuflGlyph.metNote64thUp;

  static const metNote64thDown = SmuflGlyph.metNote64thDown;

  static const metNote128thUp = SmuflGlyph.metNote128thUp;

  static const metNote128thDown = SmuflGlyph.metNote128thDown;

  static const metNote256thUp = SmuflGlyph.metNote256thUp;

  static const metNote256thDown = SmuflGlyph.metNote256thDown;

  static const metNote512thUp = SmuflGlyph.metNote512thUp;

  static const metNote512thDown = SmuflGlyph.metNote512thDown;

  static const metNote1024thUp = SmuflGlyph.metNote1024thUp;

  static const metNote1024thDown = SmuflGlyph.metNote1024thDown;

  static const metAugmentationDot = SmuflGlyph.metAugmentationDot;
}
