// Generated by tool.

part of "../glyph_class.dart";

class Tf_ornaments extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.graceNoteAcciaccaturaStemUp,
        SmuflGlyph.graceNoteAcciaccaturaStemDown,
        SmuflGlyph.graceNoteAppoggiaturaStemUp,
        SmuflGlyph.graceNoteAppoggiaturaStemDown,
        SmuflGlyph.graceNoteSlashStemUp,
        SmuflGlyph.graceNoteSlashStemDown,
        SmuflGlyph.ornamentTrill,
        SmuflGlyph.ornamentTurn,
        SmuflGlyph.ornamentTurnInverted,
        SmuflGlyph.ornamentTurnSlash,
        SmuflGlyph.ornamentTurnUp,
        SmuflGlyph.ornamentTurnUpS,
        SmuflGlyph.ornamentShortTrill,
        SmuflGlyph.ornamentMordent,
        SmuflGlyph.ornamentTremblement,
        SmuflGlyph.ornamentHaydn,
        SmuflGlyph.ornamentPortDeVoixV,
        SmuflGlyph.ornamentRightFacingHalfCircle,
        SmuflGlyph.ornamentLeftFacingHalfCircle,
        SmuflGlyph.ornamentRightFacingHook,
        SmuflGlyph.ornamentLeftFacingHook,
        SmuflGlyph.ornamentHookBeforeNote,
        SmuflGlyph.ornamentHookAfterNote,
        SmuflGlyph.ornamentUpCurve,
        SmuflGlyph.ornamentDownCurve,
        SmuflGlyph.ornamentShortObliqueLineBeforeNote,
        SmuflGlyph.ornamentShortObliqueLineAfterNote,
        SmuflGlyph.ornamentObliqueLineBeforeNote,
        SmuflGlyph.ornamentObliqueLineAfterNote,
        SmuflGlyph.ornamentDoubleObliqueLinesBeforeNote,
        SmuflGlyph.ornamentDoubleObliqueLinesAfterNote,
        SmuflGlyph.ornamentObliqueLineHorizBeforeNote,
        SmuflGlyph.ornamentObliqueLineHorizAfterNote,
        SmuflGlyph.ornamentComma,
        SmuflGlyph.ornamentShake3,
        SmuflGlyph.ornamentVerticalLine,
        SmuflGlyph.ornamentShakeMuffat1,
        SmuflGlyph.glissandoUp,
        SmuflGlyph.glissandoDown,
        SmuflGlyph.ornamentSchleifer,
        SmuflGlyph.ornamentTopLeftConcaveStroke,
        SmuflGlyph.ornamentTopLeftConvexStroke,
        SmuflGlyph.ornamentHighLeftConcaveStroke,
        SmuflGlyph.ornamentHighLeftConvexStroke,
        SmuflGlyph.ornamentLeftVerticalStroke,
        SmuflGlyph.ornamentLeftVerticalStrokeWithCross,
        SmuflGlyph.ornamentLeftShakeT,
        SmuflGlyph.ornamentLeftPlus,
        SmuflGlyph.ornamentLowLeftConcaveStroke,
        SmuflGlyph.ornamentLowLeftConvexStroke,
        SmuflGlyph.ornamentBottomLeftConcaveStroke,
        SmuflGlyph.ornamentBottomLeftConcaveStrokeLarge,
        SmuflGlyph.ornamentBottomLeftConvexStroke,
        SmuflGlyph.ornamentZigZagLineNoRightEnd,
        SmuflGlyph.ornamentZigZagLineWithRightEnd,
        SmuflGlyph.ornamentMiddleVerticalStroke,
        SmuflGlyph.ornamentTopRightConcaveStroke,
        SmuflGlyph.ornamentTopRightConvexStroke,
        SmuflGlyph.ornamentHighRightConcaveStroke,
        SmuflGlyph.ornamentHighRightConvexStroke,
        SmuflGlyph.ornamentRightVerticalStroke,
        SmuflGlyph.ornamentLowRightConcaveStroke,
        SmuflGlyph.ornamentLowRightConvexStroke,
        SmuflGlyph.ornamentBottomRightConcaveStroke,
        SmuflGlyph.ornamentBottomRightConvexStroke,
        SmuflGlyph.ornamentPrecompSlide,
        SmuflGlyph.ornamentPrecompDescendingSlide,
        SmuflGlyph.ornamentPrecompAppoggTrill,
        SmuflGlyph.ornamentPrecompAppoggTrillSuffix,
        SmuflGlyph.ornamentPrecompTurnTrillDAnglebert,
        SmuflGlyph.ornamentPrecompSlideTrillDAnglebert,
        SmuflGlyph.ornamentPrecompSlideTrillMarpurg,
        SmuflGlyph.ornamentPrecompTurnTrillBach,
        SmuflGlyph.ornamentPrecompSlideTrillBach,
        SmuflGlyph.ornamentPrecompSlideTrillMuffat,
        SmuflGlyph.ornamentPrecompSlideTrillSuffixMuffat,
        SmuflGlyph.ornamentPrecompTrillSuffixDandrieu,
        SmuflGlyph.ornamentPrecompPortDeVoixMordent,
        SmuflGlyph.ornamentPrecompTrillWithMordent,
        SmuflGlyph.ornamentPrecompCadence,
        SmuflGlyph.ornamentPrecompCadenceWithTurn,
        SmuflGlyph.ornamentPrecompDoubleCadenceLowerPrefix,
        SmuflGlyph.ornamentPrecompCadenceUpperPrefix,
        SmuflGlyph.ornamentPrecompCadenceUpperPrefixTurn,
        SmuflGlyph.ornamentPrecompDoubleCadenceUpperPrefix,
        SmuflGlyph.ornamentPrecompDoubleCadenceUpperPrefixTurn,
        SmuflGlyph.ornamentPrecompMordentRelease,
        SmuflGlyph.ornamentPrecompMordentUpperPrefix,
        SmuflGlyph.ornamentPrecompInvertedMordentUpperPrefix,
        SmuflGlyph.ornamentPrecompTrillLowerSuffix,
      ];

  static const graceNoteAcciaccaturaStemUp =
      SmuflGlyph.graceNoteAcciaccaturaStemUp;

  static const graceNoteAcciaccaturaStemDown =
      SmuflGlyph.graceNoteAcciaccaturaStemDown;

  static const graceNoteAppoggiaturaStemUp =
      SmuflGlyph.graceNoteAppoggiaturaStemUp;

  static const graceNoteAppoggiaturaStemDown =
      SmuflGlyph.graceNoteAppoggiaturaStemDown;

  static const graceNoteSlashStemUp = SmuflGlyph.graceNoteSlashStemUp;

  static const graceNoteSlashStemDown = SmuflGlyph.graceNoteSlashStemDown;

  static const ornamentTrill = SmuflGlyph.ornamentTrill;

  static const ornamentTurn = SmuflGlyph.ornamentTurn;

  static const ornamentTurnInverted = SmuflGlyph.ornamentTurnInverted;

  static const ornamentTurnSlash = SmuflGlyph.ornamentTurnSlash;

  static const ornamentTurnUp = SmuflGlyph.ornamentTurnUp;

  static const ornamentTurnUpS = SmuflGlyph.ornamentTurnUpS;

  static const ornamentShortTrill = SmuflGlyph.ornamentShortTrill;

  static const ornamentMordent = SmuflGlyph.ornamentMordent;

  static const ornamentTremblement = SmuflGlyph.ornamentTremblement;

  static const ornamentHaydn = SmuflGlyph.ornamentHaydn;

  static const ornamentPortDeVoixV = SmuflGlyph.ornamentPortDeVoixV;

  static const ornamentRightFacingHalfCircle =
      SmuflGlyph.ornamentRightFacingHalfCircle;

  static const ornamentLeftFacingHalfCircle =
      SmuflGlyph.ornamentLeftFacingHalfCircle;

  static const ornamentRightFacingHook = SmuflGlyph.ornamentRightFacingHook;

  static const ornamentLeftFacingHook = SmuflGlyph.ornamentLeftFacingHook;

  static const ornamentHookBeforeNote = SmuflGlyph.ornamentHookBeforeNote;

  static const ornamentHookAfterNote = SmuflGlyph.ornamentHookAfterNote;

  static const ornamentUpCurve = SmuflGlyph.ornamentUpCurve;

  static const ornamentDownCurve = SmuflGlyph.ornamentDownCurve;

  static const ornamentShortObliqueLineBeforeNote =
      SmuflGlyph.ornamentShortObliqueLineBeforeNote;

  static const ornamentShortObliqueLineAfterNote =
      SmuflGlyph.ornamentShortObliqueLineAfterNote;

  static const ornamentObliqueLineBeforeNote =
      SmuflGlyph.ornamentObliqueLineBeforeNote;

  static const ornamentObliqueLineAfterNote =
      SmuflGlyph.ornamentObliqueLineAfterNote;

  static const ornamentDoubleObliqueLinesBeforeNote =
      SmuflGlyph.ornamentDoubleObliqueLinesBeforeNote;

  static const ornamentDoubleObliqueLinesAfterNote =
      SmuflGlyph.ornamentDoubleObliqueLinesAfterNote;

  static const ornamentObliqueLineHorizBeforeNote =
      SmuflGlyph.ornamentObliqueLineHorizBeforeNote;

  static const ornamentObliqueLineHorizAfterNote =
      SmuflGlyph.ornamentObliqueLineHorizAfterNote;

  static const ornamentComma = SmuflGlyph.ornamentComma;

  static const ornamentShake3 = SmuflGlyph.ornamentShake3;

  static const ornamentVerticalLine = SmuflGlyph.ornamentVerticalLine;

  static const ornamentShakeMuffat1 = SmuflGlyph.ornamentShakeMuffat1;

  static const glissandoUp = SmuflGlyph.glissandoUp;

  static const glissandoDown = SmuflGlyph.glissandoDown;

  static const ornamentSchleifer = SmuflGlyph.ornamentSchleifer;

  static const ornamentTopLeftConcaveStroke =
      SmuflGlyph.ornamentTopLeftConcaveStroke;

  static const ornamentTopLeftConvexStroke =
      SmuflGlyph.ornamentTopLeftConvexStroke;

  static const ornamentHighLeftConcaveStroke =
      SmuflGlyph.ornamentHighLeftConcaveStroke;

  static const ornamentHighLeftConvexStroke =
      SmuflGlyph.ornamentHighLeftConvexStroke;

  static const ornamentLeftVerticalStroke =
      SmuflGlyph.ornamentLeftVerticalStroke;

  static const ornamentLeftVerticalStrokeWithCross =
      SmuflGlyph.ornamentLeftVerticalStrokeWithCross;

  static const ornamentLeftShakeT = SmuflGlyph.ornamentLeftShakeT;

  static const ornamentLeftPlus = SmuflGlyph.ornamentLeftPlus;

  static const ornamentLowLeftConcaveStroke =
      SmuflGlyph.ornamentLowLeftConcaveStroke;

  static const ornamentLowLeftConvexStroke =
      SmuflGlyph.ornamentLowLeftConvexStroke;

  static const ornamentBottomLeftConcaveStroke =
      SmuflGlyph.ornamentBottomLeftConcaveStroke;

  static const ornamentBottomLeftConcaveStrokeLarge =
      SmuflGlyph.ornamentBottomLeftConcaveStrokeLarge;

  static const ornamentBottomLeftConvexStroke =
      SmuflGlyph.ornamentBottomLeftConvexStroke;

  static const ornamentZigZagLineNoRightEnd =
      SmuflGlyph.ornamentZigZagLineNoRightEnd;

  static const ornamentZigZagLineWithRightEnd =
      SmuflGlyph.ornamentZigZagLineWithRightEnd;

  static const ornamentMiddleVerticalStroke =
      SmuflGlyph.ornamentMiddleVerticalStroke;

  static const ornamentTopRightConcaveStroke =
      SmuflGlyph.ornamentTopRightConcaveStroke;

  static const ornamentTopRightConvexStroke =
      SmuflGlyph.ornamentTopRightConvexStroke;

  static const ornamentHighRightConcaveStroke =
      SmuflGlyph.ornamentHighRightConcaveStroke;

  static const ornamentHighRightConvexStroke =
      SmuflGlyph.ornamentHighRightConvexStroke;

  static const ornamentRightVerticalStroke =
      SmuflGlyph.ornamentRightVerticalStroke;

  static const ornamentLowRightConcaveStroke =
      SmuflGlyph.ornamentLowRightConcaveStroke;

  static const ornamentLowRightConvexStroke =
      SmuflGlyph.ornamentLowRightConvexStroke;

  static const ornamentBottomRightConcaveStroke =
      SmuflGlyph.ornamentBottomRightConcaveStroke;

  static const ornamentBottomRightConvexStroke =
      SmuflGlyph.ornamentBottomRightConvexStroke;

  static const ornamentPrecompSlide = SmuflGlyph.ornamentPrecompSlide;

  static const ornamentPrecompDescendingSlide =
      SmuflGlyph.ornamentPrecompDescendingSlide;

  static const ornamentPrecompAppoggTrill =
      SmuflGlyph.ornamentPrecompAppoggTrill;

  static const ornamentPrecompAppoggTrillSuffix =
      SmuflGlyph.ornamentPrecompAppoggTrillSuffix;

  static const ornamentPrecompTurnTrillDAnglebert =
      SmuflGlyph.ornamentPrecompTurnTrillDAnglebert;

  static const ornamentPrecompSlideTrillDAnglebert =
      SmuflGlyph.ornamentPrecompSlideTrillDAnglebert;

  static const ornamentPrecompSlideTrillMarpurg =
      SmuflGlyph.ornamentPrecompSlideTrillMarpurg;

  static const ornamentPrecompTurnTrillBach =
      SmuflGlyph.ornamentPrecompTurnTrillBach;

  static const ornamentPrecompSlideTrillBach =
      SmuflGlyph.ornamentPrecompSlideTrillBach;

  static const ornamentPrecompSlideTrillMuffat =
      SmuflGlyph.ornamentPrecompSlideTrillMuffat;

  static const ornamentPrecompSlideTrillSuffixMuffat =
      SmuflGlyph.ornamentPrecompSlideTrillSuffixMuffat;

  static const ornamentPrecompTrillSuffixDandrieu =
      SmuflGlyph.ornamentPrecompTrillSuffixDandrieu;

  static const ornamentPrecompPortDeVoixMordent =
      SmuflGlyph.ornamentPrecompPortDeVoixMordent;

  static const ornamentPrecompTrillWithMordent =
      SmuflGlyph.ornamentPrecompTrillWithMordent;

  static const ornamentPrecompCadence = SmuflGlyph.ornamentPrecompCadence;

  static const ornamentPrecompCadenceWithTurn =
      SmuflGlyph.ornamentPrecompCadenceWithTurn;

  static const ornamentPrecompDoubleCadenceLowerPrefix =
      SmuflGlyph.ornamentPrecompDoubleCadenceLowerPrefix;

  static const ornamentPrecompCadenceUpperPrefix =
      SmuflGlyph.ornamentPrecompCadenceUpperPrefix;

  static const ornamentPrecompCadenceUpperPrefixTurn =
      SmuflGlyph.ornamentPrecompCadenceUpperPrefixTurn;

  static const ornamentPrecompDoubleCadenceUpperPrefix =
      SmuflGlyph.ornamentPrecompDoubleCadenceUpperPrefix;

  static const ornamentPrecompDoubleCadenceUpperPrefixTurn =
      SmuflGlyph.ornamentPrecompDoubleCadenceUpperPrefixTurn;

  static const ornamentPrecompMordentRelease =
      SmuflGlyph.ornamentPrecompMordentRelease;

  static const ornamentPrecompMordentUpperPrefix =
      SmuflGlyph.ornamentPrecompMordentUpperPrefix;

  static const ornamentPrecompInvertedMordentUpperPrefix =
      SmuflGlyph.ornamentPrecompInvertedMordentUpperPrefix;

  static const ornamentPrecompTrillLowerSuffix =
      SmuflGlyph.ornamentPrecompTrillLowerSuffix;
}
