// Generated by tool.

part of "../glyph_class.dart";

class TfPedals extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.keyboardPedalPed,
        SmuflGlyph.keyboardPedalP,
        SmuflGlyph.keyboardPedalE,
        SmuflGlyph.keyboardPedalD,
        SmuflGlyph.keyboardPedalDot,
        SmuflGlyph.keyboardPedalUp,
        SmuflGlyph.keyboardPedalHalf,
        SmuflGlyph.keyboardPedalUpNotch,
        SmuflGlyph.keyboardPedalHyphen,
        SmuflGlyph.keyboardPedalSost,
        SmuflGlyph.keyboardPedalS,
      ];

  static const keyboardPedalPed = SmuflGlyph.keyboardPedalPed;

  static const keyboardPedalP = SmuflGlyph.keyboardPedalP;

  static const keyboardPedalE = SmuflGlyph.keyboardPedalE;

  static const keyboardPedalD = SmuflGlyph.keyboardPedalD;

  static const keyboardPedalDot = SmuflGlyph.keyboardPedalDot;

  static const keyboardPedalUp = SmuflGlyph.keyboardPedalUp;

  static const keyboardPedalHalf = SmuflGlyph.keyboardPedalHalf;

  static const keyboardPedalUpNotch = SmuflGlyph.keyboardPedalUpNotch;

  static const keyboardPedalHyphen = SmuflGlyph.keyboardPedalHyphen;

  static const keyboardPedalSost = SmuflGlyph.keyboardPedalSost;

  static const keyboardPedalS = SmuflGlyph.keyboardPedalS;
}
