// Generated by tool.

part of "../glyph_class.dart";

class TfProlations extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.mensuralProportionMinor,
        SmuflGlyph.mensuralProportionMajor,
        SmuflGlyph.mensuralModusPerfectumVert,
        SmuflGlyph.mensuralModusImperfectumVert,
        SmuflGlyph.mensuralTempusPerfectumHoriz,
        SmuflGlyph.mensuralTempusImperfectumHoriz,
      ];

  static const mensuralProportionMinor = SmuflGlyph.mensuralProportionMinor;

  static const mensuralProportionMajor = SmuflGlyph.mensuralProportionMajor;

  static const mensuralModusPerfectumVert =
      SmuflGlyph.mensuralModusPerfectumVert;

  static const mensuralModusImperfectumVert =
      SmuflGlyph.mensuralModusImperfectumVert;

  static const mensuralTempusPerfectumHoriz =
      SmuflGlyph.mensuralTempusPerfectumHoriz;

  static const mensuralTempusImperfectumHoriz =
      SmuflGlyph.mensuralTempusImperfectumHoriz;
}
