// Generated by tool.

part of "../glyph_class.dart";

class TfPictograms extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.pictGlsp,
        SmuflGlyph.pictXyl,
        SmuflGlyph.pictXylTenor,
        SmuflGlyph.pictXylBass,
        SmuflGlyph.pictXylTrough,
        SmuflGlyph.pictXylTenorTrough,
        SmuflGlyph.pictMar,
        SmuflGlyph.pictVib,
        SmuflGlyph.pictVibMotorOff,
        SmuflGlyph.pictEmptyTrap,
        SmuflGlyph.pictGlspSmithBrindle,
        SmuflGlyph.pictXylSmithBrindle,
        SmuflGlyph.pictMarSmithBrindle,
        SmuflGlyph.pictVibSmithBrindle,
        SmuflGlyph.pictCrotales,
        SmuflGlyph.pictSteelDrums,
        SmuflGlyph.pictCelesta,
        SmuflGlyph.pictLithophone,
        SmuflGlyph.pictTubaphone,
        SmuflGlyph.pictTubularBells,
        SmuflGlyph.pictWindChimesGlass,
        SmuflGlyph.pictChimes,
        SmuflGlyph.pictBambooChimes,
        SmuflGlyph.pictShellChimes,
        SmuflGlyph.pictGlassTubeChimes,
        SmuflGlyph.pictGlassPlateChimes,
        SmuflGlyph.pictMetalTubeChimes,
        SmuflGlyph.pictMetalPlateChimes,
        SmuflGlyph.pictTimpani,
        SmuflGlyph.pictSnareDrum,
        SmuflGlyph.pictSnareDrumSnaresOff,
        SmuflGlyph.pictSnareDrumMilitary,
        SmuflGlyph.pictBassDrum,
        SmuflGlyph.pictBassDrumOnSide,
        SmuflGlyph.pictTenorDrum,
        SmuflGlyph.pictTomTom,
        SmuflGlyph.pictTomTomChinese,
        SmuflGlyph.pictTomTomJapanese,
        SmuflGlyph.pictTomTomIndoAmerican,
        SmuflGlyph.pictTambourine,
        SmuflGlyph.pictTimbales,
        SmuflGlyph.pictBongos,
        SmuflGlyph.pictConga,
        SmuflGlyph.pictLogDrum,
        SmuflGlyph.pictSlitDrum,
        SmuflGlyph.pictBrakeDrum,
        SmuflGlyph.pictGobletDrum,
        SmuflGlyph.pictTabla,
        SmuflGlyph.pictCuica,
        SmuflGlyph.pictWoodBlock,
        SmuflGlyph.pictTempleBlocks,
        SmuflGlyph.pictClaves,
        SmuflGlyph.pictGuiro,
        SmuflGlyph.pictRatchet,
        SmuflGlyph.pictFootballRatchet,
        SmuflGlyph.pictWhip,
        SmuflGlyph.pictBoardClapper,
        SmuflGlyph.pictCastanets,
        SmuflGlyph.pictCastanetsWithHandle,
        SmuflGlyph.pictQuijada,
        SmuflGlyph.pictBambooScraper,
        SmuflGlyph.pictRecoReco,
        SmuflGlyph.pictTriangle,
        SmuflGlyph.pictAnvil,
        SmuflGlyph.pictSleighBell,
        SmuflGlyph.pictCowBell,
        SmuflGlyph.pictAlmglocken,
        SmuflGlyph.pictBellPlate,
        SmuflGlyph.pictBell,
        SmuflGlyph.pictHandbell,
        SmuflGlyph.pictCencerro,
        SmuflGlyph.pictAgogo,
        SmuflGlyph.pictShellBells,
        SmuflGlyph.pictJingleBells,
        SmuflGlyph.pictBellTree,
        SmuflGlyph.pictCrashCymbals,
        SmuflGlyph.pictSuspendedCymbal,
        SmuflGlyph.pictHiHat,
        SmuflGlyph.pictHiHatOnStand,
        SmuflGlyph.pictSizzleCymbal,
        SmuflGlyph.pictVietnameseHat,
        SmuflGlyph.pictChineseCymbal,
        SmuflGlyph.pictFingerCymbals,
        SmuflGlyph.pictCymbalTongs,
        SmuflGlyph.pictEdgeOfCymbal,
        SmuflGlyph.pictBellOfCymbal,
        SmuflGlyph.pictTamTam,
        SmuflGlyph.pictTamTamWithBeater,
        SmuflGlyph.pictGong,
        SmuflGlyph.pictGongWithButton,
        SmuflGlyph.pictSlideBrushOnGong,
        SmuflGlyph.pictFlexatone,
        SmuflGlyph.pictMaraca,
        SmuflGlyph.pictMaracas,
        SmuflGlyph.pictCabasa,
        SmuflGlyph.pictThundersheet,
        SmuflGlyph.pictVibraslap,
        SmuflGlyph.pictSistrum,
        SmuflGlyph.pictRainstick,
        SmuflGlyph.pictChainRattle,
        SmuflGlyph.pictSlideWhistle,
        SmuflGlyph.pictBirdWhistle,
        SmuflGlyph.pictPoliceWhistle,
        SmuflGlyph.pictSiren,
        SmuflGlyph.pictWindMachine,
        SmuflGlyph.pictCarHorn,
        SmuflGlyph.pictKlaxonHorn,
        SmuflGlyph.pictDuckCall,
        SmuflGlyph.pictWindWhistle,
        SmuflGlyph.pictMegaphone,
        SmuflGlyph.pictLotusFlute,
        SmuflGlyph.pictPistolShot,
        SmuflGlyph.pictCannon,
        SmuflGlyph.pictSandpaperBlocks,
        SmuflGlyph.pictLionsRoar,
        SmuflGlyph.pictGlassHarp,
        SmuflGlyph.pictGlassHarmonica,
        SmuflGlyph.pictMusicalSaw,
        SmuflGlyph.pictJawHarp,
        SmuflGlyph.pictBeaterSoftXylophoneUp,
        SmuflGlyph.pictBeaterSoftXylophoneDown,
        SmuflGlyph.pictBeaterSoftXylophoneRight,
        SmuflGlyph.pictBeaterSoftXylophoneLeft,
        SmuflGlyph.pictBeaterMediumXylophoneUp,
        SmuflGlyph.pictBeaterMediumXylophoneDown,
        SmuflGlyph.pictBeaterMediumXylophoneRight,
        SmuflGlyph.pictBeaterMediumXylophoneLeft,
        SmuflGlyph.pictBeaterHardXylophoneUp,
        SmuflGlyph.pictBeaterHardXylophoneDown,
        SmuflGlyph.pictBeaterHardXylophoneRight,
        SmuflGlyph.pictBeaterHardXylophoneLeft,
        SmuflGlyph.pictBeaterWoodXylophoneUp,
        SmuflGlyph.pictBeaterWoodXylophoneDown,
        SmuflGlyph.pictBeaterWoodXylophoneRight,
        SmuflGlyph.pictBeaterWoodXylophoneLeft,
        SmuflGlyph.pictBeaterSoftGlockenspielUp,
        SmuflGlyph.pictBeaterSoftGlockenspielDown,
        SmuflGlyph.pictBeaterSoftGlockenspielRight,
        SmuflGlyph.pictBeaterSoftGlockenspielLeft,
        SmuflGlyph.pictBeaterHardGlockenspielUp,
        SmuflGlyph.pictBeaterHardGlockenspielDown,
        SmuflGlyph.pictBeaterHardGlockenspielRight,
        SmuflGlyph.pictBeaterHardGlockenspielLeft,
        SmuflGlyph.pictBeaterSoftTimpaniUp,
        SmuflGlyph.pictBeaterSoftTimpaniDown,
        SmuflGlyph.pictBeaterSoftTimpaniRight,
        SmuflGlyph.pictBeaterSoftTimpaniLeft,
        SmuflGlyph.pictBeaterMediumTimpaniUp,
        SmuflGlyph.pictBeaterMediumTimpaniDown,
        SmuflGlyph.pictBeaterMediumTimpaniRight,
        SmuflGlyph.pictBeaterMediumTimpaniLeft,
        SmuflGlyph.pictBeaterHardTimpaniUp,
        SmuflGlyph.pictBeaterHardTimpaniDown,
        SmuflGlyph.pictBeaterHardTimpaniRight,
        SmuflGlyph.pictBeaterHardTimpaniLeft,
        SmuflGlyph.pictBeaterWoodTimpaniUp,
        SmuflGlyph.pictBeaterWoodTimpaniDown,
        SmuflGlyph.pictBeaterWoodTimpaniRight,
        SmuflGlyph.pictBeaterWoodTimpaniLeft,
        SmuflGlyph.pictBeaterSoftBassDrumUp,
        SmuflGlyph.pictBeaterSoftBassDrumDown,
        SmuflGlyph.pictBeaterMediumBassDrumUp,
        SmuflGlyph.pictBeaterMediumBassDrumDown,
        SmuflGlyph.pictBeaterHardBassDrumUp,
        SmuflGlyph.pictBeaterHardBassDrumDown,
        SmuflGlyph.pictBeaterMetalBassDrumUp,
        SmuflGlyph.pictBeaterMetalBassDrumDown,
        SmuflGlyph.pictBeaterDoubleBassDrumUp,
        SmuflGlyph.pictBeaterDoubleBassDrumDown,
        SmuflGlyph.pictBeaterSoftYarnUp,
        SmuflGlyph.pictBeaterSoftYarnDown,
        SmuflGlyph.pictBeaterSoftYarnRight,
        SmuflGlyph.pictBeaterSoftYarnLeft,
        SmuflGlyph.pictBeaterMediumYarnUp,
        SmuflGlyph.pictBeaterMediumYarnDown,
        SmuflGlyph.pictBeaterMediumYarnRight,
        SmuflGlyph.pictBeaterMediumYarnLeft,
        SmuflGlyph.pictBeaterHardYarnUp,
        SmuflGlyph.pictBeaterHardYarnDown,
        SmuflGlyph.pictBeaterHardYarnRight,
        SmuflGlyph.pictBeaterHardYarnLeft,
        SmuflGlyph.pictBeaterSuperballUp,
        SmuflGlyph.pictBeaterSuperballDown,
        SmuflGlyph.pictBeaterSuperballRight,
        SmuflGlyph.pictBeaterSuperballLeft,
        SmuflGlyph.pictSuperball,
        SmuflGlyph.pictWoundHardUp,
        SmuflGlyph.pictWoundHardDown,
        SmuflGlyph.pictWoundHardRight,
        SmuflGlyph.pictWoundHardLeft,
        SmuflGlyph.pictWoundSoftUp,
        SmuflGlyph.pictWoundSoftDown,
        SmuflGlyph.pictWoundSoftRight,
        SmuflGlyph.pictWoundSoftLeft,
        SmuflGlyph.pictGumSoftUp,
        SmuflGlyph.pictGumSoftDown,
        SmuflGlyph.pictGumSoftRight,
        SmuflGlyph.pictGumSoftLeft,
        SmuflGlyph.pictGumMediumUp,
        SmuflGlyph.pictGumMediumDown,
        SmuflGlyph.pictGumMediumRight,
        SmuflGlyph.pictGumMediumLeft,
        SmuflGlyph.pictGumHardUp,
        SmuflGlyph.pictGumHardDown,
        SmuflGlyph.pictGumHardRight,
        SmuflGlyph.pictGumHardLeft,
        SmuflGlyph.pictBeaterMetalUp,
        SmuflGlyph.pictBeaterMetalDown,
        SmuflGlyph.pictBeaterMetalRight,
        SmuflGlyph.pictBeaterMetalLeft,
        SmuflGlyph.pictBeaterHammerWoodUp,
        SmuflGlyph.pictBeaterHammerWoodDown,
        SmuflGlyph.pictBeaterHammerPlasticUp,
        SmuflGlyph.pictBeaterHammerPlasticDown,
        SmuflGlyph.pictBeaterHammerMetalUp,
        SmuflGlyph.pictBeaterHammerMetalDown,
        SmuflGlyph.pictBeaterSnareSticksUp,
        SmuflGlyph.pictBeaterSnareSticksDown,
        SmuflGlyph.pictBeaterJazzSticksUp,
        SmuflGlyph.pictStickShot,
        SmuflGlyph.pictScrapeCenterToEdge,
        SmuflGlyph.pictScrapeEdgeToCenter,
        SmuflGlyph.pictScrapeAroundRim,
        SmuflGlyph.pictOnRim,
        SmuflGlyph.pictOpenRimShot,
        SmuflGlyph.pictHalfOpen1,
        SmuflGlyph.pictHalfOpen2,
        SmuflGlyph.pictOpen,
        SmuflGlyph.pictDamp1,
        SmuflGlyph.pictDamp2,
        SmuflGlyph.pictDamp3,
        SmuflGlyph.pictDamp4,
        SmuflGlyph.pictRimShotOnStem,
        SmuflGlyph.pictCenter1,
        SmuflGlyph.pictCenter2,
        SmuflGlyph.pictCenter3,
        SmuflGlyph.pictRim1,
        SmuflGlyph.pictRim2,
        SmuflGlyph.pictRim3,
        SmuflGlyph.pictNormalPosition,
        SmuflGlyph.pictChokeCymbal,
        SmuflGlyph.pictRightHandSquare,
        SmuflGlyph.pictLeftHandCircle,
        SmuflGlyph.pictSwishStem,
        SmuflGlyph.pictTurnRightStem,
        SmuflGlyph.pictTurnLeftStem,
        SmuflGlyph.pictTurnRightLeftStem,
        SmuflGlyph.pictCrushStem,
        SmuflGlyph.pictDeadNoteStem,
        SmuflGlyph.accdnRH3RanksPiccolo,
        SmuflGlyph.accdnRH3RanksClarinet,
        SmuflGlyph.accdnRH3RanksUpperTremolo8,
        SmuflGlyph.accdnRH3RanksLowerTremolo8,
        SmuflGlyph.accdnRH3RanksBassoon,
        SmuflGlyph.accdnRH3RanksOboe,
        SmuflGlyph.accdnRH3RanksViolin,
        SmuflGlyph.accdnRH3RanksImitationMusette,
        SmuflGlyph.accdnRH3RanksAuthenticMusette,
        SmuflGlyph.accdnRH3RanksOrgan,
        SmuflGlyph.accdnRH3RanksHarmonium,
        SmuflGlyph.accdnRH3RanksBandoneon,
        SmuflGlyph.accdnRH3RanksAccordion,
        SmuflGlyph.accdnRH3RanksMaster,
        SmuflGlyph.accdnRH3RanksTwoChoirs,
        SmuflGlyph.accdnRH3RanksTremoloLower8ve,
        SmuflGlyph.accdnRH3RanksTremoloUpper8ve,
        SmuflGlyph.accdnRH3RanksDoubleTremoloLower8ve,
        SmuflGlyph.accdnRH3RanksDoubleTremoloUpper8ve,
        SmuflGlyph.accdnRH3RanksFullFactory,
        SmuflGlyph.accdnRH4RanksSoprano,
        SmuflGlyph.accdnRH4RanksAlto,
        SmuflGlyph.accdnRH4RanksTenor,
        SmuflGlyph.accdnRH4RanksMaster,
        SmuflGlyph.accdnRH4RanksSoftBass,
        SmuflGlyph.accdnRH4RanksSoftTenor,
        SmuflGlyph.accdnRH4RanksBassAlto,
        SmuflGlyph.accdnLH2Ranks8Round,
        SmuflGlyph.accdnLH2Ranks16Round,
        SmuflGlyph.accdnLH2Ranks8Plus16Round,
        SmuflGlyph.accdnLH2RanksMasterRound,
        SmuflGlyph.accdnLH2RanksMasterPlus16Round,
        SmuflGlyph.accdnLH2RanksFullMasterRound,
        SmuflGlyph.accdnLH3Ranks8Square,
        SmuflGlyph.accdnLH3Ranks2Square,
        SmuflGlyph.accdnLH3RanksDouble8Square,
        SmuflGlyph.accdnLH3Ranks2Plus8Square,
        SmuflGlyph.accdnLH3RanksTuttiSquare,
        SmuflGlyph.accdnCombRH3RanksEmpty,
        SmuflGlyph.accdnCombRH4RanksEmpty,
        SmuflGlyph.accdnCombLH2RanksEmpty,
        SmuflGlyph.accdnCombLH3RanksEmptySquare,
        SmuflGlyph.accdnCombDot,
        SmuflGlyph.accdnPush,
        SmuflGlyph.accdnPull,
        SmuflGlyph.accdnRicochet2,
        SmuflGlyph.accdnRicochet3,
        SmuflGlyph.accdnRicochet4,
        SmuflGlyph.accdnRicochet5,
        SmuflGlyph.accdnRicochet6,
        SmuflGlyph.accdnRicochetStem2,
        SmuflGlyph.accdnRicochetStem3,
        SmuflGlyph.accdnRicochetStem4,
        SmuflGlyph.accdnRicochetStem5,
        SmuflGlyph.accdnRicochetStem6,
      ];

  static const pictGlsp = SmuflGlyph.pictGlsp;

  static const pictXyl = SmuflGlyph.pictXyl;

  static const pictXylTenor = SmuflGlyph.pictXylTenor;

  static const pictXylBass = SmuflGlyph.pictXylBass;

  static const pictXylTrough = SmuflGlyph.pictXylTrough;

  static const pictXylTenorTrough = SmuflGlyph.pictXylTenorTrough;

  static const pictMar = SmuflGlyph.pictMar;

  static const pictVib = SmuflGlyph.pictVib;

  static const pictVibMotorOff = SmuflGlyph.pictVibMotorOff;

  static const pictEmptyTrap = SmuflGlyph.pictEmptyTrap;

  static const pictGlspSmithBrindle = SmuflGlyph.pictGlspSmithBrindle;

  static const pictXylSmithBrindle = SmuflGlyph.pictXylSmithBrindle;

  static const pictMarSmithBrindle = SmuflGlyph.pictMarSmithBrindle;

  static const pictVibSmithBrindle = SmuflGlyph.pictVibSmithBrindle;

  static const pictCrotales = SmuflGlyph.pictCrotales;

  static const pictSteelDrums = SmuflGlyph.pictSteelDrums;

  static const pictCelesta = SmuflGlyph.pictCelesta;

  static const pictLithophone = SmuflGlyph.pictLithophone;

  static const pictTubaphone = SmuflGlyph.pictTubaphone;

  static const pictTubularBells = SmuflGlyph.pictTubularBells;

  static const pictWindChimesGlass = SmuflGlyph.pictWindChimesGlass;

  static const pictChimes = SmuflGlyph.pictChimes;

  static const pictBambooChimes = SmuflGlyph.pictBambooChimes;

  static const pictShellChimes = SmuflGlyph.pictShellChimes;

  static const pictGlassTubeChimes = SmuflGlyph.pictGlassTubeChimes;

  static const pictGlassPlateChimes = SmuflGlyph.pictGlassPlateChimes;

  static const pictMetalTubeChimes = SmuflGlyph.pictMetalTubeChimes;

  static const pictMetalPlateChimes = SmuflGlyph.pictMetalPlateChimes;

  static const pictTimpani = SmuflGlyph.pictTimpani;

  static const pictSnareDrum = SmuflGlyph.pictSnareDrum;

  static const pictSnareDrumSnaresOff = SmuflGlyph.pictSnareDrumSnaresOff;

  static const pictSnareDrumMilitary = SmuflGlyph.pictSnareDrumMilitary;

  static const pictBassDrum = SmuflGlyph.pictBassDrum;

  static const pictBassDrumOnSide = SmuflGlyph.pictBassDrumOnSide;

  static const pictTenorDrum = SmuflGlyph.pictTenorDrum;

  static const pictTomTom = SmuflGlyph.pictTomTom;

  static const pictTomTomChinese = SmuflGlyph.pictTomTomChinese;

  static const pictTomTomJapanese = SmuflGlyph.pictTomTomJapanese;

  static const pictTomTomIndoAmerican = SmuflGlyph.pictTomTomIndoAmerican;

  static const pictTambourine = SmuflGlyph.pictTambourine;

  static const pictTimbales = SmuflGlyph.pictTimbales;

  static const pictBongos = SmuflGlyph.pictBongos;

  static const pictConga = SmuflGlyph.pictConga;

  static const pictLogDrum = SmuflGlyph.pictLogDrum;

  static const pictSlitDrum = SmuflGlyph.pictSlitDrum;

  static const pictBrakeDrum = SmuflGlyph.pictBrakeDrum;

  static const pictGobletDrum = SmuflGlyph.pictGobletDrum;

  static const pictTabla = SmuflGlyph.pictTabla;

  static const pictCuica = SmuflGlyph.pictCuica;

  static const pictWoodBlock = SmuflGlyph.pictWoodBlock;

  static const pictTempleBlocks = SmuflGlyph.pictTempleBlocks;

  static const pictClaves = SmuflGlyph.pictClaves;

  static const pictGuiro = SmuflGlyph.pictGuiro;

  static const pictRatchet = SmuflGlyph.pictRatchet;

  static const pictFootballRatchet = SmuflGlyph.pictFootballRatchet;

  static const pictWhip = SmuflGlyph.pictWhip;

  static const pictBoardClapper = SmuflGlyph.pictBoardClapper;

  static const pictCastanets = SmuflGlyph.pictCastanets;

  static const pictCastanetsWithHandle = SmuflGlyph.pictCastanetsWithHandle;

  static const pictQuijada = SmuflGlyph.pictQuijada;

  static const pictBambooScraper = SmuflGlyph.pictBambooScraper;

  static const pictRecoReco = SmuflGlyph.pictRecoReco;

  static const pictTriangle = SmuflGlyph.pictTriangle;

  static const pictAnvil = SmuflGlyph.pictAnvil;

  static const pictSleighBell = SmuflGlyph.pictSleighBell;

  static const pictCowBell = SmuflGlyph.pictCowBell;

  static const pictAlmglocken = SmuflGlyph.pictAlmglocken;

  static const pictBellPlate = SmuflGlyph.pictBellPlate;

  static const pictBell = SmuflGlyph.pictBell;

  static const pictHandbell = SmuflGlyph.pictHandbell;

  static const pictCencerro = SmuflGlyph.pictCencerro;

  static const pictAgogo = SmuflGlyph.pictAgogo;

  static const pictShellBells = SmuflGlyph.pictShellBells;

  static const pictJingleBells = SmuflGlyph.pictJingleBells;

  static const pictBellTree = SmuflGlyph.pictBellTree;

  static const pictCrashCymbals = SmuflGlyph.pictCrashCymbals;

  static const pictSuspendedCymbal = SmuflGlyph.pictSuspendedCymbal;

  static const pictHiHat = SmuflGlyph.pictHiHat;

  static const pictHiHatOnStand = SmuflGlyph.pictHiHatOnStand;

  static const pictSizzleCymbal = SmuflGlyph.pictSizzleCymbal;

  static const pictVietnameseHat = SmuflGlyph.pictVietnameseHat;

  static const pictChineseCymbal = SmuflGlyph.pictChineseCymbal;

  static const pictFingerCymbals = SmuflGlyph.pictFingerCymbals;

  static const pictCymbalTongs = SmuflGlyph.pictCymbalTongs;

  static const pictEdgeOfCymbal = SmuflGlyph.pictEdgeOfCymbal;

  static const pictBellOfCymbal = SmuflGlyph.pictBellOfCymbal;

  static const pictTamTam = SmuflGlyph.pictTamTam;

  static const pictTamTamWithBeater = SmuflGlyph.pictTamTamWithBeater;

  static const pictGong = SmuflGlyph.pictGong;

  static const pictGongWithButton = SmuflGlyph.pictGongWithButton;

  static const pictSlideBrushOnGong = SmuflGlyph.pictSlideBrushOnGong;

  static const pictFlexatone = SmuflGlyph.pictFlexatone;

  static const pictMaraca = SmuflGlyph.pictMaraca;

  static const pictMaracas = SmuflGlyph.pictMaracas;

  static const pictCabasa = SmuflGlyph.pictCabasa;

  static const pictThundersheet = SmuflGlyph.pictThundersheet;

  static const pictVibraslap = SmuflGlyph.pictVibraslap;

  static const pictSistrum = SmuflGlyph.pictSistrum;

  static const pictRainstick = SmuflGlyph.pictRainstick;

  static const pictChainRattle = SmuflGlyph.pictChainRattle;

  static const pictSlideWhistle = SmuflGlyph.pictSlideWhistle;

  static const pictBirdWhistle = SmuflGlyph.pictBirdWhistle;

  static const pictPoliceWhistle = SmuflGlyph.pictPoliceWhistle;

  static const pictSiren = SmuflGlyph.pictSiren;

  static const pictWindMachine = SmuflGlyph.pictWindMachine;

  static const pictCarHorn = SmuflGlyph.pictCarHorn;

  static const pictKlaxonHorn = SmuflGlyph.pictKlaxonHorn;

  static const pictDuckCall = SmuflGlyph.pictDuckCall;

  static const pictWindWhistle = SmuflGlyph.pictWindWhistle;

  static const pictMegaphone = SmuflGlyph.pictMegaphone;

  static const pictLotusFlute = SmuflGlyph.pictLotusFlute;

  static const pictPistolShot = SmuflGlyph.pictPistolShot;

  static const pictCannon = SmuflGlyph.pictCannon;

  static const pictSandpaperBlocks = SmuflGlyph.pictSandpaperBlocks;

  static const pictLionsRoar = SmuflGlyph.pictLionsRoar;

  static const pictGlassHarp = SmuflGlyph.pictGlassHarp;

  static const pictGlassHarmonica = SmuflGlyph.pictGlassHarmonica;

  static const pictMusicalSaw = SmuflGlyph.pictMusicalSaw;

  static const pictJawHarp = SmuflGlyph.pictJawHarp;

  static const pictBeaterSoftXylophoneUp = SmuflGlyph.pictBeaterSoftXylophoneUp;

  static const pictBeaterSoftXylophoneDown =
      SmuflGlyph.pictBeaterSoftXylophoneDown;

  static const pictBeaterSoftXylophoneRight =
      SmuflGlyph.pictBeaterSoftXylophoneRight;

  static const pictBeaterSoftXylophoneLeft =
      SmuflGlyph.pictBeaterSoftXylophoneLeft;

  static const pictBeaterMediumXylophoneUp =
      SmuflGlyph.pictBeaterMediumXylophoneUp;

  static const pictBeaterMediumXylophoneDown =
      SmuflGlyph.pictBeaterMediumXylophoneDown;

  static const pictBeaterMediumXylophoneRight =
      SmuflGlyph.pictBeaterMediumXylophoneRight;

  static const pictBeaterMediumXylophoneLeft =
      SmuflGlyph.pictBeaterMediumXylophoneLeft;

  static const pictBeaterHardXylophoneUp = SmuflGlyph.pictBeaterHardXylophoneUp;

  static const pictBeaterHardXylophoneDown =
      SmuflGlyph.pictBeaterHardXylophoneDown;

  static const pictBeaterHardXylophoneRight =
      SmuflGlyph.pictBeaterHardXylophoneRight;

  static const pictBeaterHardXylophoneLeft =
      SmuflGlyph.pictBeaterHardXylophoneLeft;

  static const pictBeaterWoodXylophoneUp = SmuflGlyph.pictBeaterWoodXylophoneUp;

  static const pictBeaterWoodXylophoneDown =
      SmuflGlyph.pictBeaterWoodXylophoneDown;

  static const pictBeaterWoodXylophoneRight =
      SmuflGlyph.pictBeaterWoodXylophoneRight;

  static const pictBeaterWoodXylophoneLeft =
      SmuflGlyph.pictBeaterWoodXylophoneLeft;

  static const pictBeaterSoftGlockenspielUp =
      SmuflGlyph.pictBeaterSoftGlockenspielUp;

  static const pictBeaterSoftGlockenspielDown =
      SmuflGlyph.pictBeaterSoftGlockenspielDown;

  static const pictBeaterSoftGlockenspielRight =
      SmuflGlyph.pictBeaterSoftGlockenspielRight;

  static const pictBeaterSoftGlockenspielLeft =
      SmuflGlyph.pictBeaterSoftGlockenspielLeft;

  static const pictBeaterHardGlockenspielUp =
      SmuflGlyph.pictBeaterHardGlockenspielUp;

  static const pictBeaterHardGlockenspielDown =
      SmuflGlyph.pictBeaterHardGlockenspielDown;

  static const pictBeaterHardGlockenspielRight =
      SmuflGlyph.pictBeaterHardGlockenspielRight;

  static const pictBeaterHardGlockenspielLeft =
      SmuflGlyph.pictBeaterHardGlockenspielLeft;

  static const pictBeaterSoftTimpaniUp = SmuflGlyph.pictBeaterSoftTimpaniUp;

  static const pictBeaterSoftTimpaniDown = SmuflGlyph.pictBeaterSoftTimpaniDown;

  static const pictBeaterSoftTimpaniRight =
      SmuflGlyph.pictBeaterSoftTimpaniRight;

  static const pictBeaterSoftTimpaniLeft = SmuflGlyph.pictBeaterSoftTimpaniLeft;

  static const pictBeaterMediumTimpaniUp = SmuflGlyph.pictBeaterMediumTimpaniUp;

  static const pictBeaterMediumTimpaniDown =
      SmuflGlyph.pictBeaterMediumTimpaniDown;

  static const pictBeaterMediumTimpaniRight =
      SmuflGlyph.pictBeaterMediumTimpaniRight;

  static const pictBeaterMediumTimpaniLeft =
      SmuflGlyph.pictBeaterMediumTimpaniLeft;

  static const pictBeaterHardTimpaniUp = SmuflGlyph.pictBeaterHardTimpaniUp;

  static const pictBeaterHardTimpaniDown = SmuflGlyph.pictBeaterHardTimpaniDown;

  static const pictBeaterHardTimpaniRight =
      SmuflGlyph.pictBeaterHardTimpaniRight;

  static const pictBeaterHardTimpaniLeft = SmuflGlyph.pictBeaterHardTimpaniLeft;

  static const pictBeaterWoodTimpaniUp = SmuflGlyph.pictBeaterWoodTimpaniUp;

  static const pictBeaterWoodTimpaniDown = SmuflGlyph.pictBeaterWoodTimpaniDown;

  static const pictBeaterWoodTimpaniRight =
      SmuflGlyph.pictBeaterWoodTimpaniRight;

  static const pictBeaterWoodTimpaniLeft = SmuflGlyph.pictBeaterWoodTimpaniLeft;

  static const pictBeaterSoftBassDrumUp = SmuflGlyph.pictBeaterSoftBassDrumUp;

  static const pictBeaterSoftBassDrumDown =
      SmuflGlyph.pictBeaterSoftBassDrumDown;

  static const pictBeaterMediumBassDrumUp =
      SmuflGlyph.pictBeaterMediumBassDrumUp;

  static const pictBeaterMediumBassDrumDown =
      SmuflGlyph.pictBeaterMediumBassDrumDown;

  static const pictBeaterHardBassDrumUp = SmuflGlyph.pictBeaterHardBassDrumUp;

  static const pictBeaterHardBassDrumDown =
      SmuflGlyph.pictBeaterHardBassDrumDown;

  static const pictBeaterMetalBassDrumUp = SmuflGlyph.pictBeaterMetalBassDrumUp;

  static const pictBeaterMetalBassDrumDown =
      SmuflGlyph.pictBeaterMetalBassDrumDown;

  static const pictBeaterDoubleBassDrumUp =
      SmuflGlyph.pictBeaterDoubleBassDrumUp;

  static const pictBeaterDoubleBassDrumDown =
      SmuflGlyph.pictBeaterDoubleBassDrumDown;

  static const pictBeaterSoftYarnUp = SmuflGlyph.pictBeaterSoftYarnUp;

  static const pictBeaterSoftYarnDown = SmuflGlyph.pictBeaterSoftYarnDown;

  static const pictBeaterSoftYarnRight = SmuflGlyph.pictBeaterSoftYarnRight;

  static const pictBeaterSoftYarnLeft = SmuflGlyph.pictBeaterSoftYarnLeft;

  static const pictBeaterMediumYarnUp = SmuflGlyph.pictBeaterMediumYarnUp;

  static const pictBeaterMediumYarnDown = SmuflGlyph.pictBeaterMediumYarnDown;

  static const pictBeaterMediumYarnRight = SmuflGlyph.pictBeaterMediumYarnRight;

  static const pictBeaterMediumYarnLeft = SmuflGlyph.pictBeaterMediumYarnLeft;

  static const pictBeaterHardYarnUp = SmuflGlyph.pictBeaterHardYarnUp;

  static const pictBeaterHardYarnDown = SmuflGlyph.pictBeaterHardYarnDown;

  static const pictBeaterHardYarnRight = SmuflGlyph.pictBeaterHardYarnRight;

  static const pictBeaterHardYarnLeft = SmuflGlyph.pictBeaterHardYarnLeft;

  static const pictBeaterSuperballUp = SmuflGlyph.pictBeaterSuperballUp;

  static const pictBeaterSuperballDown = SmuflGlyph.pictBeaterSuperballDown;

  static const pictBeaterSuperballRight = SmuflGlyph.pictBeaterSuperballRight;

  static const pictBeaterSuperballLeft = SmuflGlyph.pictBeaterSuperballLeft;

  static const pictSuperball = SmuflGlyph.pictSuperball;

  static const pictWoundHardUp = SmuflGlyph.pictWoundHardUp;

  static const pictWoundHardDown = SmuflGlyph.pictWoundHardDown;

  static const pictWoundHardRight = SmuflGlyph.pictWoundHardRight;

  static const pictWoundHardLeft = SmuflGlyph.pictWoundHardLeft;

  static const pictWoundSoftUp = SmuflGlyph.pictWoundSoftUp;

  static const pictWoundSoftDown = SmuflGlyph.pictWoundSoftDown;

  static const pictWoundSoftRight = SmuflGlyph.pictWoundSoftRight;

  static const pictWoundSoftLeft = SmuflGlyph.pictWoundSoftLeft;

  static const pictGumSoftUp = SmuflGlyph.pictGumSoftUp;

  static const pictGumSoftDown = SmuflGlyph.pictGumSoftDown;

  static const pictGumSoftRight = SmuflGlyph.pictGumSoftRight;

  static const pictGumSoftLeft = SmuflGlyph.pictGumSoftLeft;

  static const pictGumMediumUp = SmuflGlyph.pictGumMediumUp;

  static const pictGumMediumDown = SmuflGlyph.pictGumMediumDown;

  static const pictGumMediumRight = SmuflGlyph.pictGumMediumRight;

  static const pictGumMediumLeft = SmuflGlyph.pictGumMediumLeft;

  static const pictGumHardUp = SmuflGlyph.pictGumHardUp;

  static const pictGumHardDown = SmuflGlyph.pictGumHardDown;

  static const pictGumHardRight = SmuflGlyph.pictGumHardRight;

  static const pictGumHardLeft = SmuflGlyph.pictGumHardLeft;

  static const pictBeaterMetalUp = SmuflGlyph.pictBeaterMetalUp;

  static const pictBeaterMetalDown = SmuflGlyph.pictBeaterMetalDown;

  static const pictBeaterMetalRight = SmuflGlyph.pictBeaterMetalRight;

  static const pictBeaterMetalLeft = SmuflGlyph.pictBeaterMetalLeft;

  static const pictBeaterHammerWoodUp = SmuflGlyph.pictBeaterHammerWoodUp;

  static const pictBeaterHammerWoodDown = SmuflGlyph.pictBeaterHammerWoodDown;

  static const pictBeaterHammerPlasticUp = SmuflGlyph.pictBeaterHammerPlasticUp;

  static const pictBeaterHammerPlasticDown =
      SmuflGlyph.pictBeaterHammerPlasticDown;

  static const pictBeaterHammerMetalUp = SmuflGlyph.pictBeaterHammerMetalUp;

  static const pictBeaterHammerMetalDown = SmuflGlyph.pictBeaterHammerMetalDown;

  static const pictBeaterSnareSticksUp = SmuflGlyph.pictBeaterSnareSticksUp;

  static const pictBeaterSnareSticksDown = SmuflGlyph.pictBeaterSnareSticksDown;

  static const pictBeaterJazzSticksUp = SmuflGlyph.pictBeaterJazzSticksUp;

  static const pictStickShot = SmuflGlyph.pictStickShot;

  static const pictScrapeCenterToEdge = SmuflGlyph.pictScrapeCenterToEdge;

  static const pictScrapeEdgeToCenter = SmuflGlyph.pictScrapeEdgeToCenter;

  static const pictScrapeAroundRim = SmuflGlyph.pictScrapeAroundRim;

  static const pictOnRim = SmuflGlyph.pictOnRim;

  static const pictOpenRimShot = SmuflGlyph.pictOpenRimShot;

  static const pictHalfOpen1 = SmuflGlyph.pictHalfOpen1;

  static const pictHalfOpen2 = SmuflGlyph.pictHalfOpen2;

  static const pictOpen = SmuflGlyph.pictOpen;

  static const pictDamp1 = SmuflGlyph.pictDamp1;

  static const pictDamp2 = SmuflGlyph.pictDamp2;

  static const pictDamp3 = SmuflGlyph.pictDamp3;

  static const pictDamp4 = SmuflGlyph.pictDamp4;

  static const pictRimShotOnStem = SmuflGlyph.pictRimShotOnStem;

  static const pictCenter1 = SmuflGlyph.pictCenter1;

  static const pictCenter2 = SmuflGlyph.pictCenter2;

  static const pictCenter3 = SmuflGlyph.pictCenter3;

  static const pictRim1 = SmuflGlyph.pictRim1;

  static const pictRim2 = SmuflGlyph.pictRim2;

  static const pictRim3 = SmuflGlyph.pictRim3;

  static const pictNormalPosition = SmuflGlyph.pictNormalPosition;

  static const pictChokeCymbal = SmuflGlyph.pictChokeCymbal;

  static const pictRightHandSquare = SmuflGlyph.pictRightHandSquare;

  static const pictLeftHandCircle = SmuflGlyph.pictLeftHandCircle;

  static const pictSwishStem = SmuflGlyph.pictSwishStem;

  static const pictTurnRightStem = SmuflGlyph.pictTurnRightStem;

  static const pictTurnLeftStem = SmuflGlyph.pictTurnLeftStem;

  static const pictTurnRightLeftStem = SmuflGlyph.pictTurnRightLeftStem;

  static const pictCrushStem = SmuflGlyph.pictCrushStem;

  static const pictDeadNoteStem = SmuflGlyph.pictDeadNoteStem;

  static const accdnRH3RanksPiccolo = SmuflGlyph.accdnRH3RanksPiccolo;

  static const accdnRH3RanksClarinet = SmuflGlyph.accdnRH3RanksClarinet;

  static const accdnRH3RanksUpperTremolo8 =
      SmuflGlyph.accdnRH3RanksUpperTremolo8;

  static const accdnRH3RanksLowerTremolo8 =
      SmuflGlyph.accdnRH3RanksLowerTremolo8;

  static const accdnRH3RanksBassoon = SmuflGlyph.accdnRH3RanksBassoon;

  static const accdnRH3RanksOboe = SmuflGlyph.accdnRH3RanksOboe;

  static const accdnRH3RanksViolin = SmuflGlyph.accdnRH3RanksViolin;

  static const accdnRH3RanksImitationMusette =
      SmuflGlyph.accdnRH3RanksImitationMusette;

  static const accdnRH3RanksAuthenticMusette =
      SmuflGlyph.accdnRH3RanksAuthenticMusette;

  static const accdnRH3RanksOrgan = SmuflGlyph.accdnRH3RanksOrgan;

  static const accdnRH3RanksHarmonium = SmuflGlyph.accdnRH3RanksHarmonium;

  static const accdnRH3RanksBandoneon = SmuflGlyph.accdnRH3RanksBandoneon;

  static const accdnRH3RanksAccordion = SmuflGlyph.accdnRH3RanksAccordion;

  static const accdnRH3RanksMaster = SmuflGlyph.accdnRH3RanksMaster;

  static const accdnRH3RanksTwoChoirs = SmuflGlyph.accdnRH3RanksTwoChoirs;

  static const accdnRH3RanksTremoloLower8ve =
      SmuflGlyph.accdnRH3RanksTremoloLower8ve;

  static const accdnRH3RanksTremoloUpper8ve =
      SmuflGlyph.accdnRH3RanksTremoloUpper8ve;

  static const accdnRH3RanksDoubleTremoloLower8ve =
      SmuflGlyph.accdnRH3RanksDoubleTremoloLower8ve;

  static const accdnRH3RanksDoubleTremoloUpper8ve =
      SmuflGlyph.accdnRH3RanksDoubleTremoloUpper8ve;

  static const accdnRH3RanksFullFactory = SmuflGlyph.accdnRH3RanksFullFactory;

  static const accdnRH4RanksSoprano = SmuflGlyph.accdnRH4RanksSoprano;

  static const accdnRH4RanksAlto = SmuflGlyph.accdnRH4RanksAlto;

  static const accdnRH4RanksTenor = SmuflGlyph.accdnRH4RanksTenor;

  static const accdnRH4RanksMaster = SmuflGlyph.accdnRH4RanksMaster;

  static const accdnRH4RanksSoftBass = SmuflGlyph.accdnRH4RanksSoftBass;

  static const accdnRH4RanksSoftTenor = SmuflGlyph.accdnRH4RanksSoftTenor;

  static const accdnRH4RanksBassAlto = SmuflGlyph.accdnRH4RanksBassAlto;

  static const accdnLH2Ranks8Round = SmuflGlyph.accdnLH2Ranks8Round;

  static const accdnLH2Ranks16Round = SmuflGlyph.accdnLH2Ranks16Round;

  static const accdnLH2Ranks8Plus16Round = SmuflGlyph.accdnLH2Ranks8Plus16Round;

  static const accdnLH2RanksMasterRound = SmuflGlyph.accdnLH2RanksMasterRound;

  static const accdnLH2RanksMasterPlus16Round =
      SmuflGlyph.accdnLH2RanksMasterPlus16Round;

  static const accdnLH2RanksFullMasterRound =
      SmuflGlyph.accdnLH2RanksFullMasterRound;

  static const accdnLH3Ranks8Square = SmuflGlyph.accdnLH3Ranks8Square;

  static const accdnLH3Ranks2Square = SmuflGlyph.accdnLH3Ranks2Square;

  static const accdnLH3RanksDouble8Square =
      SmuflGlyph.accdnLH3RanksDouble8Square;

  static const accdnLH3Ranks2Plus8Square = SmuflGlyph.accdnLH3Ranks2Plus8Square;

  static const accdnLH3RanksTuttiSquare = SmuflGlyph.accdnLH3RanksTuttiSquare;

  static const accdnCombRH3RanksEmpty = SmuflGlyph.accdnCombRH3RanksEmpty;

  static const accdnCombRH4RanksEmpty = SmuflGlyph.accdnCombRH4RanksEmpty;

  static const accdnCombLH2RanksEmpty = SmuflGlyph.accdnCombLH2RanksEmpty;

  static const accdnCombLH3RanksEmptySquare =
      SmuflGlyph.accdnCombLH3RanksEmptySquare;

  static const accdnCombDot = SmuflGlyph.accdnCombDot;

  static const accdnPush = SmuflGlyph.accdnPush;

  static const accdnPull = SmuflGlyph.accdnPull;

  static const accdnRicochet2 = SmuflGlyph.accdnRicochet2;

  static const accdnRicochet3 = SmuflGlyph.accdnRicochet3;

  static const accdnRicochet4 = SmuflGlyph.accdnRicochet4;

  static const accdnRicochet5 = SmuflGlyph.accdnRicochet5;

  static const accdnRicochet6 = SmuflGlyph.accdnRicochet6;

  static const accdnRicochetStem2 = SmuflGlyph.accdnRicochetStem2;

  static const accdnRicochetStem3 = SmuflGlyph.accdnRicochetStem3;

  static const accdnRicochetStem4 = SmuflGlyph.accdnRicochetStem4;

  static const accdnRicochetStem5 = SmuflGlyph.accdnRicochetStem5;

  static const accdnRicochetStem6 = SmuflGlyph.accdnRicochetStem6;
}
