// Generated by tool.

part of "../glyph_class.dart";

class TfZeroWidth extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.staff1Line,
        SmuflGlyph.staff2Lines,
        SmuflGlyph.staff3Lines,
        SmuflGlyph.staff4Lines,
        SmuflGlyph.staff5Lines,
        SmuflGlyph.staff6Lines,
        SmuflGlyph.staff1LineWide,
        SmuflGlyph.staff2LinesWide,
        SmuflGlyph.staff3LinesWide,
        SmuflGlyph.staff4LinesWide,
        SmuflGlyph.staff5LinesWide,
        SmuflGlyph.staff6LinesWide,
        SmuflGlyph.staff1LineNarrow,
        SmuflGlyph.staff2LinesNarrow,
        SmuflGlyph.staff3LinesNarrow,
        SmuflGlyph.staff4LinesNarrow,
        SmuflGlyph.staff5LinesNarrow,
        SmuflGlyph.staff6LinesNarrow,
        SmuflGlyph.legerLine,
        SmuflGlyph.legerLineWide,
        SmuflGlyph.legerLineNarrow,
        SmuflGlyph.timeSig0,
        SmuflGlyph.timeSig1,
        SmuflGlyph.timeSig2,
        SmuflGlyph.timeSig3,
        SmuflGlyph.timeSig4,
        SmuflGlyph.timeSig5,
        SmuflGlyph.timeSig6,
        SmuflGlyph.timeSig7,
        SmuflGlyph.timeSig8,
        SmuflGlyph.timeSig9,
        SmuflGlyph.pictBeaterSoftXylophoneLeft,
        SmuflGlyph.pictBeaterMediumXylophoneLeft,
        SmuflGlyph.pictBeaterHardXylophoneLeft,
        SmuflGlyph.pictBeaterWoodXylophoneLeft,
        SmuflGlyph.pictBeaterSoftGlockenspielLeft,
        SmuflGlyph.pictBeaterHardGlockenspielLeft,
        SmuflGlyph.pictBeaterSoftTimpaniLeft,
        SmuflGlyph.pictBeaterMediumTimpaniLeft,
        SmuflGlyph.pictBeaterHardTimpaniLeft,
        SmuflGlyph.pictBeaterWoodTimpaniLeft,
        SmuflGlyph.pictBeaterSoftYarnLeft,
        SmuflGlyph.pictBeaterMediumYarnLeft,
        SmuflGlyph.pictBeaterHardYarnLeft,
        SmuflGlyph.pictBeaterSuperballLeft,
        SmuflGlyph.pictWoundHardLeft,
        SmuflGlyph.pictWoundSoftLeft,
        SmuflGlyph.pictGumSoftLeft,
        SmuflGlyph.pictGumMediumLeft,
        SmuflGlyph.pictGumHardLeft,
        SmuflGlyph.pictBeaterMetalLeft,
        SmuflGlyph.pictBeaterCombiningParentheses,
        SmuflGlyph.pictBeaterCombiningDashedCircle,
        SmuflGlyph.pictBeaterBox,
        SmuflGlyph.chantStaff,
        SmuflGlyph.chantStaffWide,
        SmuflGlyph.chantStaffNarrow,
        SmuflGlyph.luteStaff6Lines,
        SmuflGlyph.luteStaff6LinesWide,
        SmuflGlyph.luteStaff6LinesNarrow,
      ];

  static const staff1Line = SmuflGlyph.staff1Line;

  static const staff2Lines = SmuflGlyph.staff2Lines;

  static const staff3Lines = SmuflGlyph.staff3Lines;

  static const staff4Lines = SmuflGlyph.staff4Lines;

  static const staff5Lines = SmuflGlyph.staff5Lines;

  static const staff6Lines = SmuflGlyph.staff6Lines;

  static const staff1LineWide = SmuflGlyph.staff1LineWide;

  static const staff2LinesWide = SmuflGlyph.staff2LinesWide;

  static const staff3LinesWide = SmuflGlyph.staff3LinesWide;

  static const staff4LinesWide = SmuflGlyph.staff4LinesWide;

  static const staff5LinesWide = SmuflGlyph.staff5LinesWide;

  static const staff6LinesWide = SmuflGlyph.staff6LinesWide;

  static const staff1LineNarrow = SmuflGlyph.staff1LineNarrow;

  static const staff2LinesNarrow = SmuflGlyph.staff2LinesNarrow;

  static const staff3LinesNarrow = SmuflGlyph.staff3LinesNarrow;

  static const staff4LinesNarrow = SmuflGlyph.staff4LinesNarrow;

  static const staff5LinesNarrow = SmuflGlyph.staff5LinesNarrow;

  static const staff6LinesNarrow = SmuflGlyph.staff6LinesNarrow;

  static const legerLine = SmuflGlyph.legerLine;

  static const legerLineWide = SmuflGlyph.legerLineWide;

  static const legerLineNarrow = SmuflGlyph.legerLineNarrow;

  static const timeSig0 = SmuflGlyph.timeSig0;

  static const timeSig1 = SmuflGlyph.timeSig1;

  static const timeSig2 = SmuflGlyph.timeSig2;

  static const timeSig3 = SmuflGlyph.timeSig3;

  static const timeSig4 = SmuflGlyph.timeSig4;

  static const timeSig5 = SmuflGlyph.timeSig5;

  static const timeSig6 = SmuflGlyph.timeSig6;

  static const timeSig7 = SmuflGlyph.timeSig7;

  static const timeSig8 = SmuflGlyph.timeSig8;

  static const timeSig9 = SmuflGlyph.timeSig9;

  static const pictBeaterSoftXylophoneLeft =
      SmuflGlyph.pictBeaterSoftXylophoneLeft;

  static const pictBeaterMediumXylophoneLeft =
      SmuflGlyph.pictBeaterMediumXylophoneLeft;

  static const pictBeaterHardXylophoneLeft =
      SmuflGlyph.pictBeaterHardXylophoneLeft;

  static const pictBeaterWoodXylophoneLeft =
      SmuflGlyph.pictBeaterWoodXylophoneLeft;

  static const pictBeaterSoftGlockenspielLeft =
      SmuflGlyph.pictBeaterSoftGlockenspielLeft;

  static const pictBeaterHardGlockenspielLeft =
      SmuflGlyph.pictBeaterHardGlockenspielLeft;

  static const pictBeaterSoftTimpaniLeft = SmuflGlyph.pictBeaterSoftTimpaniLeft;

  static const pictBeaterMediumTimpaniLeft =
      SmuflGlyph.pictBeaterMediumTimpaniLeft;

  static const pictBeaterHardTimpaniLeft = SmuflGlyph.pictBeaterHardTimpaniLeft;

  static const pictBeaterWoodTimpaniLeft = SmuflGlyph.pictBeaterWoodTimpaniLeft;

  static const pictBeaterSoftYarnLeft = SmuflGlyph.pictBeaterSoftYarnLeft;

  static const pictBeaterMediumYarnLeft = SmuflGlyph.pictBeaterMediumYarnLeft;

  static const pictBeaterHardYarnLeft = SmuflGlyph.pictBeaterHardYarnLeft;

  static const pictBeaterSuperballLeft = SmuflGlyph.pictBeaterSuperballLeft;

  static const pictWoundHardLeft = SmuflGlyph.pictWoundHardLeft;

  static const pictWoundSoftLeft = SmuflGlyph.pictWoundSoftLeft;

  static const pictGumSoftLeft = SmuflGlyph.pictGumSoftLeft;

  static const pictGumMediumLeft = SmuflGlyph.pictGumMediumLeft;

  static const pictGumHardLeft = SmuflGlyph.pictGumHardLeft;

  static const pictBeaterMetalLeft = SmuflGlyph.pictBeaterMetalLeft;

  static const pictBeaterCombiningParentheses =
      SmuflGlyph.pictBeaterCombiningParentheses;

  static const pictBeaterCombiningDashedCircle =
      SmuflGlyph.pictBeaterCombiningDashedCircle;

  static const pictBeaterBox = SmuflGlyph.pictBeaterBox;

  static const chantStaff = SmuflGlyph.chantStaff;

  static const chantStaffWide = SmuflGlyph.chantStaffWide;

  static const chantStaffNarrow = SmuflGlyph.chantStaffNarrow;

  static const luteStaff6Lines = SmuflGlyph.luteStaff6Lines;

  static const luteStaff6LinesWide = SmuflGlyph.luteStaff6LinesWide;

  static const luteStaff6LinesNarrow = SmuflGlyph.luteStaff6LinesNarrow;
}
