// Generated by tool.

part of "../glyph_class.dart";

class WigglesArpeggiatoDown extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.wiggleArpeggiatoDown,
        SmuflGlyph.wiggleArpeggiatoDownSwash,
        SmuflGlyph.wiggleArpeggiatoDownArrow,
      ];

  static const wiggleArpeggiatoDown = SmuflGlyph.wiggleArpeggiatoDown;

  static const wiggleArpeggiatoDownSwash = SmuflGlyph.wiggleArpeggiatoDownSwash;

  static const wiggleArpeggiatoDownArrow = SmuflGlyph.wiggleArpeggiatoDownArrow;
}
