// Generated by tool.

part of "../glyph_class.dart";

class WigglesTrill extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.wiggleTrillFastest,
        SmuflGlyph.wiggleTrillFasterStill,
        SmuflGlyph.wiggleTrillFaster,
        SmuflGlyph.wiggleTrillFast,
        SmuflGlyph.wiggleTrill,
        SmuflGlyph.wiggleTrillSlow,
        SmuflGlyph.wiggleTrillSlower,
        SmuflGlyph.wiggleTrillSlowerStill,
        SmuflGlyph.wiggleTrillSlowest,
      ];

  static const wiggleTrillFastest = SmuflGlyph.wiggleTrillFastest;

  static const wiggleTrillFasterStill = SmuflGlyph.wiggleTrillFasterStill;

  static const wiggleTrillFaster = SmuflGlyph.wiggleTrillFaster;

  static const wiggleTrillFast = SmuflGlyph.wiggleTrillFast;

  static const wiggleTrill = SmuflGlyph.wiggleTrill;

  static const wiggleTrillSlow = SmuflGlyph.wiggleTrillSlow;

  static const wiggleTrillSlower = SmuflGlyph.wiggleTrillSlower;

  static const wiggleTrillSlowerStill = SmuflGlyph.wiggleTrillSlowerStill;

  static const wiggleTrillSlowest = SmuflGlyph.wiggleTrillSlowest;
}
