// Generated by tool.

part of "../glyph_class.dart";

class WigglesArpeggiatoUp extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.wiggleArpeggiatoUp,
        SmuflGlyph.wiggleArpeggiatoUpSwash,
        SmuflGlyph.wiggleArpeggiatoUpArrow,
      ];

  static const wiggleArpeggiatoUp = SmuflGlyph.wiggleArpeggiatoUp;

  static const wiggleArpeggiatoUpSwash = SmuflGlyph.wiggleArpeggiatoUpSwash;

  static const wiggleArpeggiatoUpArrow = SmuflGlyph.wiggleArpeggiatoUpArrow;
}
