// Generated by tool.

part of "../glyph_class.dart";

class WigglesVibrato extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.wiggleVibrato,
        SmuflGlyph.wiggleVibratoWide,
        SmuflGlyph.guitarVibratoStroke,
        SmuflGlyph.guitarWideVibratoStroke,
      ];

  static const wiggleVibrato = SmuflGlyph.wiggleVibrato;

  static const wiggleVibratoWide = SmuflGlyph.wiggleVibratoWide;

  static const guitarVibratoStroke = SmuflGlyph.guitarVibratoStroke;

  static const guitarWideVibratoStroke = SmuflGlyph.guitarWideVibratoStroke;
}
