// Generated by tool.

part of "../glyph_class.dart";

class WigglesVibratoVariable extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.wiggleVibratoStart,
        SmuflGlyph.wiggleVibratoSmallestFastest,
        SmuflGlyph.wiggleVibratoSmallestFasterStill,
        SmuflGlyph.wiggleVibratoSmallestFaster,
        SmuflGlyph.wiggleVibratoSmallestFast,
        SmuflGlyph.wiggleVibratoSmallestSlow,
        SmuflGlyph.wiggleVibratoSmallestSlower,
        SmuflGlyph.wiggleVibratoSmallestSlowest,
        SmuflGlyph.wiggleVibratoSmallFastest,
        SmuflGlyph.wiggleVibratoSmallFasterStill,
        SmuflGlyph.wiggleVibratoSmallFaster,
        SmuflGlyph.wiggleVibratoSmallFast,
        SmuflGlyph.wiggleVibratoSmallSlow,
        SmuflGlyph.wiggleVibratoSmallSlower,
        SmuflGlyph.wiggleVibratoSmallSlowest,
        SmuflGlyph.wiggleVibratoMediumFastest,
        SmuflGlyph.wiggleVibratoMediumFasterStill,
        SmuflGlyph.wiggleVibratoMediumFaster,
        SmuflGlyph.wiggleVibratoMediumFast,
        SmuflGlyph.wiggleVibratoMediumSlow,
        SmuflGlyph.wiggleVIbratoMediumSlower,
        SmuflGlyph.wiggleVibratoMediumSlowest,
        SmuflGlyph.wiggleVibratoLargeFastest,
        SmuflGlyph.wiggleVibratoLargeFasterStill,
        SmuflGlyph.wiggleVibratoLargeFaster,
        SmuflGlyph.wiggleVibratoLargeFast,
        SmuflGlyph.wiggleVibratoLargeSlow,
        SmuflGlyph.wiggleVibratoLargeSlower,
        SmuflGlyph.wiggleVibratoLargeSlowest,
        SmuflGlyph.wiggleVibratoLargestFastest,
        SmuflGlyph.wiggleVibratoLargestFasterStill,
        SmuflGlyph.wiggleVibratoLargestFaster,
        SmuflGlyph.wiggleVibratoLargestFast,
        SmuflGlyph.wiggleVibratoLargestSlow,
        SmuflGlyph.wiggleVIbratoLargestSlower,
        SmuflGlyph.wiggleVibratoLargestSlowest,
      ];

  static const wiggleVibratoStart = SmuflGlyph.wiggleVibratoStart;

  static const wiggleVibratoSmallestFastest =
      SmuflGlyph.wiggleVibratoSmallestFastest;

  static const wiggleVibratoSmallestFasterStill =
      SmuflGlyph.wiggleVibratoSmallestFasterStill;

  static const wiggleVibratoSmallestFaster =
      SmuflGlyph.wiggleVibratoSmallestFaster;

  static const wiggleVibratoSmallestFast = SmuflGlyph.wiggleVibratoSmallestFast;

  static const wiggleVibratoSmallestSlow = SmuflGlyph.wiggleVibratoSmallestSlow;

  static const wiggleVibratoSmallestSlower =
      SmuflGlyph.wiggleVibratoSmallestSlower;

  static const wiggleVibratoSmallestSlowest =
      SmuflGlyph.wiggleVibratoSmallestSlowest;

  static const wiggleVibratoSmallFastest = SmuflGlyph.wiggleVibratoSmallFastest;

  static const wiggleVibratoSmallFasterStill =
      SmuflGlyph.wiggleVibratoSmallFasterStill;

  static const wiggleVibratoSmallFaster = SmuflGlyph.wiggleVibratoSmallFaster;

  static const wiggleVibratoSmallFast = SmuflGlyph.wiggleVibratoSmallFast;

  static const wiggleVibratoSmallSlow = SmuflGlyph.wiggleVibratoSmallSlow;

  static const wiggleVibratoSmallSlower = SmuflGlyph.wiggleVibratoSmallSlower;

  static const wiggleVibratoSmallSlowest = SmuflGlyph.wiggleVibratoSmallSlowest;

  static const wiggleVibratoMediumFastest =
      SmuflGlyph.wiggleVibratoMediumFastest;

  static const wiggleVibratoMediumFasterStill =
      SmuflGlyph.wiggleVibratoMediumFasterStill;

  static const wiggleVibratoMediumFaster = SmuflGlyph.wiggleVibratoMediumFaster;

  static const wiggleVibratoMediumFast = SmuflGlyph.wiggleVibratoMediumFast;

  static const wiggleVibratoMediumSlow = SmuflGlyph.wiggleVibratoMediumSlow;

  static const wiggleVIbratoMediumSlower = SmuflGlyph.wiggleVIbratoMediumSlower;

  static const wiggleVibratoMediumSlowest =
      SmuflGlyph.wiggleVibratoMediumSlowest;

  static const wiggleVibratoLargeFastest = SmuflGlyph.wiggleVibratoLargeFastest;

  static const wiggleVibratoLargeFasterStill =
      SmuflGlyph.wiggleVibratoLargeFasterStill;

  static const wiggleVibratoLargeFaster = SmuflGlyph.wiggleVibratoLargeFaster;

  static const wiggleVibratoLargeFast = SmuflGlyph.wiggleVibratoLargeFast;

  static const wiggleVibratoLargeSlow = SmuflGlyph.wiggleVibratoLargeSlow;

  static const wiggleVibratoLargeSlower = SmuflGlyph.wiggleVibratoLargeSlower;

  static const wiggleVibratoLargeSlowest = SmuflGlyph.wiggleVibratoLargeSlowest;

  static const wiggleVibratoLargestFastest =
      SmuflGlyph.wiggleVibratoLargestFastest;

  static const wiggleVibratoLargestFasterStill =
      SmuflGlyph.wiggleVibratoLargestFasterStill;

  static const wiggleVibratoLargestFaster =
      SmuflGlyph.wiggleVibratoLargestFaster;

  static const wiggleVibratoLargestFast = SmuflGlyph.wiggleVibratoLargestFast;

  static const wiggleVibratoLargestSlow = SmuflGlyph.wiggleVibratoLargestSlow;

  static const wiggleVIbratoLargestSlower =
      SmuflGlyph.wiggleVIbratoLargestSlower;

  static const wiggleVibratoLargestSlowest =
      SmuflGlyph.wiggleVibratoLargestSlowest;
}
