// Generated by tool.

part of "../glyph_class.dart";

class WigglesCircularMotion extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.wiggleCircularStart,
        SmuflGlyph.wiggleCircularLargest,
        SmuflGlyph.wiggleCircularLargerStill,
        SmuflGlyph.wiggleCircularLarger,
        SmuflGlyph.wiggleCircularLarge,
        SmuflGlyph.wiggleCircular,
        SmuflGlyph.wiggleCircularSmall,
        SmuflGlyph.wiggleCircularEnd,
      ];

  static const wiggleCircularStart = SmuflGlyph.wiggleCircularStart;

  static const wiggleCircularLargest = SmuflGlyph.wiggleCircularLargest;

  static const wiggleCircularLargerStill = SmuflGlyph.wiggleCircularLargerStill;

  static const wiggleCircularLarger = SmuflGlyph.wiggleCircularLarger;

  static const wiggleCircularLarge = SmuflGlyph.wiggleCircularLarge;

  static const wiggleCircular = SmuflGlyph.wiggleCircular;

  static const wiggleCircularSmall = SmuflGlyph.wiggleCircularSmall;

  static const wiggleCircularEnd = SmuflGlyph.wiggleCircularEnd;
}
