// Generated by tool.

part of "../glyph_class.dart";

class WigglesQuasiRandom extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.wiggleRandom1,
        SmuflGlyph.wiggleRandom2,
        SmuflGlyph.wiggleRandom3,
        SmuflGlyph.wiggleRandom4,
      ];

  static const wiggleRandom1 = SmuflGlyph.wiggleRandom1;

  static const wiggleRandom2 = SmuflGlyph.wiggleRandom2;

  static const wiggleRandom3 = SmuflGlyph.wiggleRandom3;

  static const wiggleRandom4 = SmuflGlyph.wiggleRandom4;
}
