// Generated by tool.

part of "../glyph_class.dart";

class WigglesArpeggiato extends GlyphClass {
  @override
  List<SmuflGlyph> get values => [
        SmuflGlyph.wiggleArpeggiatoUp,
        SmuflGlyph.wiggleArpeggiatoDown,
        SmuflGlyph.wiggleArpeggiatoUpSwash,
        SmuflGlyph.wiggleArpeggiatoDownSwash,
        SmuflGlyph.wiggleArpeggiatoUpArrow,
        SmuflGlyph.wiggleArpeggiatoDownArrow,
      ];

  static const wiggleArpeggiatoUp = SmuflGlyph.wiggleArpeggiatoUp;

  static const wiggleArpeggiatoDown = SmuflGlyph.wiggleArpeggiatoDown;

  static const wiggleArpeggiatoUpSwash = SmuflGlyph.wiggleArpeggiatoUpSwash;

  static const wiggleArpeggiatoDownSwash = SmuflGlyph.wiggleArpeggiatoDownSwash;

  static const wiggleArpeggiatoUpArrow = SmuflGlyph.wiggleArpeggiatoUpArrow;

  static const wiggleArpeggiatoDownArrow = SmuflGlyph.wiggleArpeggiatoDownArrow;
}
