name: music_notation
description: A parser for MusicXML files, and a custom renderer to display the parsed music notation in Flutter apps.
version: 0.0.1
homepage: https://github.com/ViliusP/music_notation

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  xml: ^6.5.0

  collection: ^1.18.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  test: ^1.25.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  fonts:
    - family: Sebastian
      fonts:
        - asset: lib/smufl_fonts/Sebastian/Sebastian.otf
    - family: SebastianText
      fonts:
        - asset: lib/smufl_fonts/Sebastian/SebastianText.otf 