name: music_notation
description: A parser for MusicXML files, and a custom renderer to display the parsed music notation in Flutter apps.
version: 0.0.1
homepage: https://github.com/ViliusP/music_notation

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  xml: ^6.2.0

  collection: ^1.17.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.22.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  fonts:
    - family: Sebastian
      fonts:
        - asset: smufl_fonts/sebastian/sebastian.otf
    - family: SebastianText
      fonts:
        - asset: smufl_fonts/sebastianText.ttf