name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  xml: ^6.2.0

  xml_serializable: ^2.2.2

  jinja: ^0.4.2

  collection: ^1.17.2

dev_dependencies:
  lints: ^2.0.0

  test: ^1.24.4